// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_2_0_4_0_0_relu_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
output  [1:0] ap_return_0;
output  [1:0] ap_return_1;
output  [1:0] ap_return_2;
output  [1:0] ap_return_3;
output  [1:0] ap_return_4;
output  [1:0] ap_return_5;
output  [1:0] ap_return_6;
output  [1:0] ap_return_7;
output  [1:0] ap_return_8;
output  [1:0] ap_return_9;
output  [1:0] ap_return_10;
output  [1:0] ap_return_11;
output  [1:0] ap_return_12;
output  [1:0] ap_return_13;
output  [1:0] ap_return_14;
output  [1:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] data_15_val_read_reg_2876;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] data_14_val_read_reg_2882;
reg   [15:0] data_13_val_read_reg_2888;
reg   [15:0] data_12_val_read_reg_2894;
reg   [15:0] data_11_val_read_reg_2900;
reg   [15:0] data_10_val_read_reg_2906;
reg   [15:0] data_9_val_read_reg_2912;
reg   [15:0] data_8_val_read_reg_2918;
reg   [15:0] data_7_val_read_reg_2924;
reg   [15:0] data_6_val_read_reg_2930;
reg   [15:0] data_5_val_read_reg_2936;
reg   [15:0] data_4_val_read_reg_2942;
reg   [15:0] data_3_val_read_reg_2948;
reg   [15:0] data_2_val_read_reg_2954;
reg   [15:0] data_1_val_read_reg_2960;
reg   [15:0] data_0_val_read_reg_2966;
reg   [0:0] tmp_reg_2972;
wire   [1:0] add_ln46_fu_232_p2;
reg   [1:0] add_ln46_reg_2979;
wire   [0:0] icmp_ln46_82_fu_248_p2;
reg   [0:0] icmp_ln46_82_reg_2986;
reg   [0:0] tmp_249_reg_2991;
wire   [1:0] add_ln46_40_fu_314_p2;
reg   [1:0] add_ln46_40_reg_2998;
wire   [0:0] icmp_ln46_84_fu_330_p2;
reg   [0:0] icmp_ln46_84_reg_3005;
reg   [0:0] tmp_254_reg_3010;
wire   [1:0] add_ln46_41_fu_396_p2;
reg   [1:0] add_ln46_41_reg_3017;
wire   [0:0] icmp_ln46_86_fu_412_p2;
reg   [0:0] icmp_ln46_86_reg_3024;
reg   [0:0] tmp_260_reg_3029;
wire   [1:0] add_ln46_42_fu_478_p2;
reg   [1:0] add_ln46_42_reg_3036;
wire   [0:0] icmp_ln46_88_fu_494_p2;
reg   [0:0] icmp_ln46_88_reg_3043;
reg   [0:0] tmp_266_reg_3048;
wire   [1:0] add_ln46_43_fu_560_p2;
reg   [1:0] add_ln46_43_reg_3055;
wire   [0:0] icmp_ln46_90_fu_576_p2;
reg   [0:0] icmp_ln46_90_reg_3062;
reg   [0:0] tmp_272_reg_3067;
wire   [1:0] add_ln46_44_fu_642_p2;
reg   [1:0] add_ln46_44_reg_3074;
wire   [0:0] icmp_ln46_92_fu_658_p2;
reg   [0:0] icmp_ln46_92_reg_3081;
reg   [0:0] tmp_278_reg_3086;
wire   [1:0] add_ln46_45_fu_724_p2;
reg   [1:0] add_ln46_45_reg_3093;
wire   [0:0] icmp_ln46_94_fu_740_p2;
reg   [0:0] icmp_ln46_94_reg_3100;
reg   [0:0] tmp_284_reg_3105;
wire   [1:0] add_ln46_46_fu_806_p2;
reg   [1:0] add_ln46_46_reg_3112;
wire   [0:0] icmp_ln46_96_fu_822_p2;
reg   [0:0] icmp_ln46_96_reg_3119;
reg   [0:0] tmp_290_reg_3124;
wire   [1:0] add_ln46_47_fu_888_p2;
reg   [1:0] add_ln46_47_reg_3131;
wire   [0:0] icmp_ln46_98_fu_904_p2;
reg   [0:0] icmp_ln46_98_reg_3138;
reg   [0:0] tmp_296_reg_3143;
wire   [1:0] add_ln46_48_fu_970_p2;
reg   [1:0] add_ln46_48_reg_3150;
wire   [0:0] icmp_ln46_100_fu_986_p2;
reg   [0:0] icmp_ln46_100_reg_3157;
reg   [0:0] tmp_302_reg_3162;
wire   [1:0] add_ln46_49_fu_1052_p2;
reg   [1:0] add_ln46_49_reg_3169;
wire   [0:0] icmp_ln46_102_fu_1068_p2;
reg   [0:0] icmp_ln46_102_reg_3176;
reg   [0:0] tmp_308_reg_3181;
wire   [1:0] add_ln46_50_fu_1134_p2;
reg   [1:0] add_ln46_50_reg_3188;
wire   [0:0] icmp_ln46_104_fu_1150_p2;
reg   [0:0] icmp_ln46_104_reg_3195;
reg   [0:0] tmp_314_reg_3200;
wire   [1:0] add_ln46_51_fu_1216_p2;
reg   [1:0] add_ln46_51_reg_3207;
wire   [0:0] icmp_ln46_106_fu_1232_p2;
reg   [0:0] icmp_ln46_106_reg_3214;
reg   [0:0] tmp_320_reg_3219;
wire   [1:0] add_ln46_52_fu_1298_p2;
reg   [1:0] add_ln46_52_reg_3226;
wire   [0:0] icmp_ln46_108_fu_1314_p2;
reg   [0:0] icmp_ln46_108_reg_3233;
reg   [0:0] tmp_326_reg_3238;
wire   [1:0] add_ln46_53_fu_1380_p2;
reg   [1:0] add_ln46_53_reg_3245;
wire   [0:0] icmp_ln46_110_fu_1396_p2;
reg   [0:0] icmp_ln46_110_reg_3252;
reg   [0:0] tmp_332_reg_3257;
wire   [1:0] add_ln46_54_fu_1462_p2;
reg   [1:0] add_ln46_54_reg_3264;
wire   [0:0] icmp_ln46_112_fu_1478_p2;
reg   [0:0] icmp_ln46_112_reg_3271;
wire    ap_block_pp0_stage0;
wire   [6:0] trunc_ln46_fu_198_p1;
wire   [0:0] tmp_247_fu_208_p3;
wire   [0:0] icmp_ln46_fu_202_p2;
wire   [0:0] or_ln46_fu_216_p2;
wire   [0:0] tmp_245_fu_190_p3;
wire   [0:0] and_ln46_fu_222_p2;
wire   [1:0] trunc_ln_fu_180_p4;
wire   [1:0] zext_ln46_fu_228_p1;
wire   [5:0] tmp_s_fu_238_p4;
wire   [6:0] trunc_ln46_58_fu_280_p1;
wire   [0:0] tmp_252_fu_290_p3;
wire   [0:0] icmp_ln46_83_fu_284_p2;
wire   [0:0] or_ln46_126_fu_298_p2;
wire   [0:0] tmp_250_fu_272_p3;
wire   [0:0] and_ln46_75_fu_304_p2;
wire   [1:0] trunc_ln46_s_fu_262_p4;
wire   [1:0] zext_ln46_40_fu_310_p1;
wire   [5:0] tmp_244_fu_320_p4;
wire   [6:0] trunc_ln46_59_fu_362_p1;
wire   [0:0] tmp_257_fu_372_p3;
wire   [0:0] icmp_ln46_85_fu_366_p2;
wire   [0:0] or_ln46_129_fu_380_p2;
wire   [0:0] tmp_255_fu_354_p3;
wire   [0:0] and_ln46_76_fu_386_p2;
wire   [1:0] trunc_ln46_37_fu_344_p4;
wire   [1:0] zext_ln46_41_fu_392_p1;
wire   [5:0] tmp_258_fu_402_p4;
wire   [6:0] trunc_ln46_60_fu_444_p1;
wire   [0:0] tmp_263_fu_454_p3;
wire   [0:0] icmp_ln46_87_fu_448_p2;
wire   [0:0] or_ln46_132_fu_462_p2;
wire   [0:0] tmp_261_fu_436_p3;
wire   [0:0] and_ln46_77_fu_468_p2;
wire   [1:0] trunc_ln46_38_fu_426_p4;
wire   [1:0] zext_ln46_42_fu_474_p1;
wire   [5:0] tmp_264_fu_484_p4;
wire   [6:0] trunc_ln46_61_fu_526_p1;
wire   [0:0] tmp_269_fu_536_p3;
wire   [0:0] icmp_ln46_89_fu_530_p2;
wire   [0:0] or_ln46_135_fu_544_p2;
wire   [0:0] tmp_267_fu_518_p3;
wire   [0:0] and_ln46_78_fu_550_p2;
wire   [1:0] trunc_ln46_39_fu_508_p4;
wire   [1:0] zext_ln46_43_fu_556_p1;
wire   [5:0] tmp_270_fu_566_p4;
wire   [6:0] trunc_ln46_62_fu_608_p1;
wire   [0:0] tmp_275_fu_618_p3;
wire   [0:0] icmp_ln46_91_fu_612_p2;
wire   [0:0] or_ln46_138_fu_626_p2;
wire   [0:0] tmp_273_fu_600_p3;
wire   [0:0] and_ln46_79_fu_632_p2;
wire   [1:0] trunc_ln46_40_fu_590_p4;
wire   [1:0] zext_ln46_44_fu_638_p1;
wire   [5:0] tmp_276_fu_648_p4;
wire   [6:0] trunc_ln46_63_fu_690_p1;
wire   [0:0] tmp_281_fu_700_p3;
wire   [0:0] icmp_ln46_93_fu_694_p2;
wire   [0:0] or_ln46_141_fu_708_p2;
wire   [0:0] tmp_279_fu_682_p3;
wire   [0:0] and_ln46_80_fu_714_p2;
wire   [1:0] trunc_ln46_41_fu_672_p4;
wire   [1:0] zext_ln46_45_fu_720_p1;
wire   [5:0] tmp_282_fu_730_p4;
wire   [6:0] trunc_ln46_64_fu_772_p1;
wire   [0:0] tmp_287_fu_782_p3;
wire   [0:0] icmp_ln46_95_fu_776_p2;
wire   [0:0] or_ln46_144_fu_790_p2;
wire   [0:0] tmp_285_fu_764_p3;
wire   [0:0] and_ln46_81_fu_796_p2;
wire   [1:0] trunc_ln46_42_fu_754_p4;
wire   [1:0] zext_ln46_46_fu_802_p1;
wire   [5:0] tmp_288_fu_812_p4;
wire   [6:0] trunc_ln46_65_fu_854_p1;
wire   [0:0] tmp_293_fu_864_p3;
wire   [0:0] icmp_ln46_97_fu_858_p2;
wire   [0:0] or_ln46_147_fu_872_p2;
wire   [0:0] tmp_291_fu_846_p3;
wire   [0:0] and_ln46_83_fu_878_p2;
wire   [1:0] trunc_ln46_43_fu_836_p4;
wire   [1:0] zext_ln46_47_fu_884_p1;
wire   [5:0] tmp_294_fu_894_p4;
wire   [6:0] trunc_ln46_66_fu_936_p1;
wire   [0:0] tmp_299_fu_946_p3;
wire   [0:0] icmp_ln46_99_fu_940_p2;
wire   [0:0] or_ln46_150_fu_954_p2;
wire   [0:0] tmp_297_fu_928_p3;
wire   [0:0] and_ln46_85_fu_960_p2;
wire   [1:0] trunc_ln46_44_fu_918_p4;
wire   [1:0] zext_ln46_48_fu_966_p1;
wire   [5:0] tmp_300_fu_976_p4;
wire   [6:0] trunc_ln46_67_fu_1018_p1;
wire   [0:0] tmp_305_fu_1028_p3;
wire   [0:0] icmp_ln46_101_fu_1022_p2;
wire   [0:0] or_ln46_153_fu_1036_p2;
wire   [0:0] tmp_303_fu_1010_p3;
wire   [0:0] and_ln46_87_fu_1042_p2;
wire   [1:0] trunc_ln46_45_fu_1000_p4;
wire   [1:0] zext_ln46_49_fu_1048_p1;
wire   [5:0] tmp_306_fu_1058_p4;
wire   [6:0] trunc_ln46_68_fu_1100_p1;
wire   [0:0] tmp_311_fu_1110_p3;
wire   [0:0] icmp_ln46_103_fu_1104_p2;
wire   [0:0] or_ln46_156_fu_1118_p2;
wire   [0:0] tmp_309_fu_1092_p3;
wire   [0:0] and_ln46_89_fu_1124_p2;
wire   [1:0] trunc_ln46_46_fu_1082_p4;
wire   [1:0] zext_ln46_50_fu_1130_p1;
wire   [5:0] tmp_312_fu_1140_p4;
wire   [6:0] trunc_ln46_69_fu_1182_p1;
wire   [0:0] tmp_317_fu_1192_p3;
wire   [0:0] icmp_ln46_105_fu_1186_p2;
wire   [0:0] or_ln46_159_fu_1200_p2;
wire   [0:0] tmp_315_fu_1174_p3;
wire   [0:0] and_ln46_91_fu_1206_p2;
wire   [1:0] trunc_ln46_47_fu_1164_p4;
wire   [1:0] zext_ln46_51_fu_1212_p1;
wire   [5:0] tmp_318_fu_1222_p4;
wire   [6:0] trunc_ln46_70_fu_1264_p1;
wire   [0:0] tmp_323_fu_1274_p3;
wire   [0:0] icmp_ln46_107_fu_1268_p2;
wire   [0:0] or_ln46_162_fu_1282_p2;
wire   [0:0] tmp_321_fu_1256_p3;
wire   [0:0] and_ln46_93_fu_1288_p2;
wire   [1:0] trunc_ln46_48_fu_1246_p4;
wire   [1:0] zext_ln46_52_fu_1294_p1;
wire   [5:0] tmp_324_fu_1304_p4;
wire   [6:0] trunc_ln46_71_fu_1346_p1;
wire   [0:0] tmp_329_fu_1356_p3;
wire   [0:0] icmp_ln46_109_fu_1350_p2;
wire   [0:0] or_ln46_165_fu_1364_p2;
wire   [0:0] tmp_327_fu_1338_p3;
wire   [0:0] and_ln46_95_fu_1370_p2;
wire   [1:0] trunc_ln46_49_fu_1328_p4;
wire   [1:0] zext_ln46_53_fu_1376_p1;
wire   [5:0] tmp_330_fu_1386_p4;
wire   [6:0] trunc_ln46_72_fu_1428_p1;
wire   [0:0] tmp_335_fu_1438_p3;
wire   [0:0] icmp_ln46_111_fu_1432_p2;
wire   [0:0] or_ln46_168_fu_1446_p2;
wire   [0:0] tmp_333_fu_1420_p3;
wire   [0:0] and_ln46_97_fu_1452_p2;
wire   [1:0] trunc_ln46_50_fu_1410_p4;
wire   [1:0] zext_ln46_54_fu_1458_p1;
wire   [5:0] tmp_336_fu_1468_p4;
wire   [0:0] tmp_246_fu_1489_p3;
wire   [0:0] tmp_248_fu_1496_p3;
wire   [0:0] not_tmp_290_fu_1503_p2;
wire   [0:0] and_ln46_82_fu_1509_p2;
wire   [0:0] empty_fu_1515_p2;
wire   [0:0] xor_ln46_fu_1525_p2;
wire   [0:0] or_ln46_124_fu_1520_p2;
wire   [1:0] select_ln46_fu_1536_p3;
wire   [0:0] or_ln46_125_fu_1531_p2;
wire   [1:0] select_ln46_124_fu_1542_p3;
wire   [0:0] icmp_ln45_fu_1484_p2;
wire   [1:0] select_ln46_125_fu_1550_p3;
wire   [0:0] tmp_251_fu_1570_p3;
wire   [0:0] tmp_253_fu_1577_p3;
wire   [0:0] not_tmp_297_fu_1584_p2;
wire   [0:0] and_ln46_84_fu_1590_p2;
wire   [0:0] empty_50_fu_1596_p2;
wire   [0:0] xor_ln46_40_fu_1606_p2;
wire   [0:0] or_ln46_127_fu_1601_p2;
wire   [1:0] select_ln46_126_fu_1617_p3;
wire   [0:0] or_ln46_128_fu_1612_p2;
wire   [1:0] select_ln46_127_fu_1623_p3;
wire   [0:0] icmp_ln45_40_fu_1565_p2;
wire   [1:0] select_ln46_128_fu_1631_p3;
wire   [0:0] tmp_256_fu_1651_p3;
wire   [0:0] tmp_259_fu_1658_p3;
wire   [0:0] not_tmp_304_fu_1665_p2;
wire   [0:0] and_ln46_86_fu_1671_p2;
wire   [0:0] empty_51_fu_1677_p2;
wire   [0:0] xor_ln46_41_fu_1687_p2;
wire   [0:0] or_ln46_130_fu_1682_p2;
wire   [1:0] select_ln46_129_fu_1698_p3;
wire   [0:0] or_ln46_131_fu_1693_p2;
wire   [1:0] select_ln46_130_fu_1704_p3;
wire   [0:0] icmp_ln45_41_fu_1646_p2;
wire   [1:0] select_ln46_131_fu_1712_p3;
wire   [0:0] tmp_262_fu_1732_p3;
wire   [0:0] tmp_265_fu_1739_p3;
wire   [0:0] not_tmp_311_fu_1746_p2;
wire   [0:0] and_ln46_88_fu_1752_p2;
wire   [0:0] empty_52_fu_1758_p2;
wire   [0:0] xor_ln46_42_fu_1768_p2;
wire   [0:0] or_ln46_133_fu_1763_p2;
wire   [1:0] select_ln46_132_fu_1779_p3;
wire   [0:0] or_ln46_134_fu_1774_p2;
wire   [1:0] select_ln46_133_fu_1785_p3;
wire   [0:0] icmp_ln45_42_fu_1727_p2;
wire   [1:0] select_ln46_134_fu_1793_p3;
wire   [0:0] tmp_268_fu_1813_p3;
wire   [0:0] tmp_271_fu_1820_p3;
wire   [0:0] not_tmp_318_fu_1827_p2;
wire   [0:0] and_ln46_90_fu_1833_p2;
wire   [0:0] empty_53_fu_1839_p2;
wire   [0:0] xor_ln46_43_fu_1849_p2;
wire   [0:0] or_ln46_136_fu_1844_p2;
wire   [1:0] select_ln46_135_fu_1860_p3;
wire   [0:0] or_ln46_137_fu_1855_p2;
wire   [1:0] select_ln46_136_fu_1866_p3;
wire   [0:0] icmp_ln45_43_fu_1808_p2;
wire   [1:0] select_ln46_137_fu_1874_p3;
wire   [0:0] tmp_274_fu_1894_p3;
wire   [0:0] tmp_277_fu_1901_p3;
wire   [0:0] not_tmp_325_fu_1908_p2;
wire   [0:0] and_ln46_92_fu_1914_p2;
wire   [0:0] empty_54_fu_1920_p2;
wire   [0:0] xor_ln46_44_fu_1930_p2;
wire   [0:0] or_ln46_139_fu_1925_p2;
wire   [1:0] select_ln46_138_fu_1941_p3;
wire   [0:0] or_ln46_140_fu_1936_p2;
wire   [1:0] select_ln46_139_fu_1947_p3;
wire   [0:0] icmp_ln45_44_fu_1889_p2;
wire   [1:0] select_ln46_140_fu_1955_p3;
wire   [0:0] tmp_280_fu_1975_p3;
wire   [0:0] tmp_283_fu_1982_p3;
wire   [0:0] not_tmp_332_fu_1989_p2;
wire   [0:0] and_ln46_94_fu_1995_p2;
wire   [0:0] empty_55_fu_2001_p2;
wire   [0:0] xor_ln46_45_fu_2011_p2;
wire   [0:0] or_ln46_142_fu_2006_p2;
wire   [1:0] select_ln46_141_fu_2022_p3;
wire   [0:0] or_ln46_143_fu_2017_p2;
wire   [1:0] select_ln46_142_fu_2028_p3;
wire   [0:0] icmp_ln45_45_fu_1970_p2;
wire   [1:0] select_ln46_143_fu_2036_p3;
wire   [0:0] tmp_286_fu_2056_p3;
wire   [0:0] tmp_289_fu_2063_p3;
wire   [0:0] not_tmp_339_fu_2070_p2;
wire   [0:0] and_ln46_96_fu_2076_p2;
wire   [0:0] empty_56_fu_2082_p2;
wire   [0:0] xor_ln46_46_fu_2092_p2;
wire   [0:0] or_ln46_145_fu_2087_p2;
wire   [1:0] select_ln46_144_fu_2103_p3;
wire   [0:0] or_ln46_146_fu_2098_p2;
wire   [1:0] select_ln46_145_fu_2109_p3;
wire   [0:0] icmp_ln45_46_fu_2051_p2;
wire   [1:0] select_ln46_146_fu_2117_p3;
wire   [0:0] tmp_292_fu_2137_p3;
wire   [0:0] tmp_295_fu_2144_p3;
wire   [0:0] not_tmp_346_fu_2151_p2;
wire   [0:0] and_ln46_98_fu_2157_p2;
wire   [0:0] empty_57_fu_2163_p2;
wire   [0:0] xor_ln46_47_fu_2173_p2;
wire   [0:0] or_ln46_148_fu_2168_p2;
wire   [1:0] select_ln46_147_fu_2184_p3;
wire   [0:0] or_ln46_149_fu_2179_p2;
wire   [1:0] select_ln46_148_fu_2190_p3;
wire   [0:0] icmp_ln45_47_fu_2132_p2;
wire   [1:0] select_ln46_149_fu_2198_p3;
wire   [0:0] tmp_298_fu_2218_p3;
wire   [0:0] tmp_301_fu_2225_p3;
wire   [0:0] not_tmp_353_fu_2232_p2;
wire   [0:0] and_ln46_100_fu_2238_p2;
wire   [0:0] empty_58_fu_2244_p2;
wire   [0:0] xor_ln46_48_fu_2254_p2;
wire   [0:0] or_ln46_151_fu_2249_p2;
wire   [1:0] select_ln46_150_fu_2265_p3;
wire   [0:0] or_ln46_152_fu_2260_p2;
wire   [1:0] select_ln46_151_fu_2271_p3;
wire   [0:0] icmp_ln45_48_fu_2213_p2;
wire   [1:0] select_ln46_152_fu_2279_p3;
wire   [0:0] tmp_304_fu_2299_p3;
wire   [0:0] tmp_307_fu_2306_p3;
wire   [0:0] not_tmp_360_fu_2313_p2;
wire   [0:0] and_ln46_102_fu_2319_p2;
wire   [0:0] empty_59_fu_2325_p2;
wire   [0:0] xor_ln46_49_fu_2335_p2;
wire   [0:0] or_ln46_154_fu_2330_p2;
wire   [1:0] select_ln46_153_fu_2346_p3;
wire   [0:0] or_ln46_155_fu_2341_p2;
wire   [1:0] select_ln46_154_fu_2352_p3;
wire   [0:0] icmp_ln45_49_fu_2294_p2;
wire   [1:0] select_ln46_155_fu_2360_p3;
wire   [0:0] tmp_310_fu_2380_p3;
wire   [0:0] tmp_313_fu_2387_p3;
wire   [0:0] not_tmp_367_fu_2394_p2;
wire   [0:0] and_ln46_104_fu_2400_p2;
wire   [0:0] empty_60_fu_2406_p2;
wire   [0:0] xor_ln46_50_fu_2416_p2;
wire   [0:0] or_ln46_157_fu_2411_p2;
wire   [1:0] select_ln46_156_fu_2427_p3;
wire   [0:0] or_ln46_158_fu_2422_p2;
wire   [1:0] select_ln46_157_fu_2433_p3;
wire   [0:0] icmp_ln45_50_fu_2375_p2;
wire   [1:0] select_ln46_158_fu_2441_p3;
wire   [0:0] tmp_316_fu_2461_p3;
wire   [0:0] tmp_319_fu_2468_p3;
wire   [0:0] not_tmp_374_fu_2475_p2;
wire   [0:0] and_ln46_106_fu_2481_p2;
wire   [0:0] empty_61_fu_2487_p2;
wire   [0:0] xor_ln46_51_fu_2497_p2;
wire   [0:0] or_ln46_160_fu_2492_p2;
wire   [1:0] select_ln46_159_fu_2508_p3;
wire   [0:0] or_ln46_161_fu_2503_p2;
wire   [1:0] select_ln46_160_fu_2514_p3;
wire   [0:0] icmp_ln45_51_fu_2456_p2;
wire   [1:0] select_ln46_161_fu_2522_p3;
wire   [0:0] tmp_322_fu_2542_p3;
wire   [0:0] tmp_325_fu_2549_p3;
wire   [0:0] not_tmp_381_fu_2556_p2;
wire   [0:0] and_ln46_108_fu_2562_p2;
wire   [0:0] empty_62_fu_2568_p2;
wire   [0:0] xor_ln46_52_fu_2578_p2;
wire   [0:0] or_ln46_163_fu_2573_p2;
wire   [1:0] select_ln46_162_fu_2589_p3;
wire   [0:0] or_ln46_164_fu_2584_p2;
wire   [1:0] select_ln46_163_fu_2595_p3;
wire   [0:0] icmp_ln45_52_fu_2537_p2;
wire   [1:0] select_ln46_164_fu_2603_p3;
wire   [0:0] tmp_328_fu_2623_p3;
wire   [0:0] tmp_331_fu_2630_p3;
wire   [0:0] not_tmp_388_fu_2637_p2;
wire   [0:0] and_ln46_110_fu_2643_p2;
wire   [0:0] empty_63_fu_2649_p2;
wire   [0:0] xor_ln46_53_fu_2659_p2;
wire   [0:0] or_ln46_166_fu_2654_p2;
wire   [1:0] select_ln46_165_fu_2670_p3;
wire   [0:0] or_ln46_167_fu_2665_p2;
wire   [1:0] select_ln46_166_fu_2676_p3;
wire   [0:0] icmp_ln45_53_fu_2618_p2;
wire   [1:0] select_ln46_167_fu_2684_p3;
wire   [0:0] tmp_334_fu_2704_p3;
wire   [0:0] tmp_337_fu_2711_p3;
wire   [0:0] not_tmp_395_fu_2718_p2;
wire   [0:0] and_ln46_112_fu_2724_p2;
wire   [0:0] empty_64_fu_2730_p2;
wire   [0:0] xor_ln46_54_fu_2740_p2;
wire   [0:0] or_ln46_169_fu_2735_p2;
wire   [1:0] select_ln46_168_fu_2751_p3;
wire   [0:0] or_ln46_170_fu_2746_p2;
wire   [1:0] select_ln46_169_fu_2757_p3;
wire   [0:0] icmp_ln45_54_fu_2699_p2;
wire   [1:0] select_ln46_170_fu_2765_p3;
wire   [1:0] res_0_0_fu_1557_p3;
wire   [1:0] res_1_0_fu_1638_p3;
wire   [1:0] res_2_0_fu_1719_p3;
wire   [1:0] res_3_0_fu_1800_p3;
wire   [1:0] res_4_0_fu_1881_p3;
wire   [1:0] res_5_0_fu_1962_p3;
wire   [1:0] res_6_0_fu_2043_p3;
wire   [1:0] res_7_0_fu_2124_p3;
wire   [1:0] res_8_0_fu_2205_p3;
wire   [1:0] res_9_0_fu_2286_p3;
wire   [1:0] res_10_0_fu_2367_p3;
wire   [1:0] res_11_0_fu_2448_p3;
wire   [1:0] res_12_0_fu_2529_p3;
wire   [1:0] res_13_0_fu_2610_p3;
wire   [1:0] res_1445_0_fu_2691_p3;
wire   [1:0] res_15_0_fu_2772_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln46_40_reg_2998 <= add_ln46_40_fu_314_p2;
        add_ln46_41_reg_3017 <= add_ln46_41_fu_396_p2;
        add_ln46_42_reg_3036 <= add_ln46_42_fu_478_p2;
        add_ln46_43_reg_3055 <= add_ln46_43_fu_560_p2;
        add_ln46_44_reg_3074 <= add_ln46_44_fu_642_p2;
        add_ln46_45_reg_3093 <= add_ln46_45_fu_724_p2;
        add_ln46_46_reg_3112 <= add_ln46_46_fu_806_p2;
        add_ln46_47_reg_3131 <= add_ln46_47_fu_888_p2;
        add_ln46_48_reg_3150 <= add_ln46_48_fu_970_p2;
        add_ln46_49_reg_3169 <= add_ln46_49_fu_1052_p2;
        add_ln46_50_reg_3188 <= add_ln46_50_fu_1134_p2;
        add_ln46_51_reg_3207 <= add_ln46_51_fu_1216_p2;
        add_ln46_52_reg_3226 <= add_ln46_52_fu_1298_p2;
        add_ln46_53_reg_3245 <= add_ln46_53_fu_1380_p2;
        add_ln46_54_reg_3264 <= add_ln46_54_fu_1462_p2;
        add_ln46_reg_2979 <= add_ln46_fu_232_p2;
        data_0_val_read_reg_2966 <= data_0_val;
        data_10_val_read_reg_2906 <= data_10_val;
        data_11_val_read_reg_2900 <= data_11_val;
        data_12_val_read_reg_2894 <= data_12_val;
        data_13_val_read_reg_2888 <= data_13_val;
        data_14_val_read_reg_2882 <= data_14_val;
        data_15_val_read_reg_2876 <= data_15_val;
        data_1_val_read_reg_2960 <= data_1_val;
        data_2_val_read_reg_2954 <= data_2_val;
        data_3_val_read_reg_2948 <= data_3_val;
        data_4_val_read_reg_2942 <= data_4_val;
        data_5_val_read_reg_2936 <= data_5_val;
        data_6_val_read_reg_2930 <= data_6_val;
        data_7_val_read_reg_2924 <= data_7_val;
        data_8_val_read_reg_2918 <= data_8_val;
        data_9_val_read_reg_2912 <= data_9_val;
        icmp_ln46_100_reg_3157 <= icmp_ln46_100_fu_986_p2;
        icmp_ln46_102_reg_3176 <= icmp_ln46_102_fu_1068_p2;
        icmp_ln46_104_reg_3195 <= icmp_ln46_104_fu_1150_p2;
        icmp_ln46_106_reg_3214 <= icmp_ln46_106_fu_1232_p2;
        icmp_ln46_108_reg_3233 <= icmp_ln46_108_fu_1314_p2;
        icmp_ln46_110_reg_3252 <= icmp_ln46_110_fu_1396_p2;
        icmp_ln46_112_reg_3271 <= icmp_ln46_112_fu_1478_p2;
        icmp_ln46_82_reg_2986 <= icmp_ln46_82_fu_248_p2;
        icmp_ln46_84_reg_3005 <= icmp_ln46_84_fu_330_p2;
        icmp_ln46_86_reg_3024 <= icmp_ln46_86_fu_412_p2;
        icmp_ln46_88_reg_3043 <= icmp_ln46_88_fu_494_p2;
        icmp_ln46_90_reg_3062 <= icmp_ln46_90_fu_576_p2;
        icmp_ln46_92_reg_3081 <= icmp_ln46_92_fu_658_p2;
        icmp_ln46_94_reg_3100 <= icmp_ln46_94_fu_740_p2;
        icmp_ln46_96_reg_3119 <= icmp_ln46_96_fu_822_p2;
        icmp_ln46_98_reg_3138 <= icmp_ln46_98_fu_904_p2;
        tmp_249_reg_2991 <= data_1_val[32'd15];
        tmp_254_reg_3010 <= data_2_val[32'd15];
        tmp_260_reg_3029 <= data_3_val[32'd15];
        tmp_266_reg_3048 <= data_4_val[32'd15];
        tmp_272_reg_3067 <= data_5_val[32'd15];
        tmp_278_reg_3086 <= data_6_val[32'd15];
        tmp_284_reg_3105 <= data_7_val[32'd15];
        tmp_290_reg_3124 <= data_8_val[32'd15];
        tmp_296_reg_3143 <= data_9_val[32'd15];
        tmp_302_reg_3162 <= data_10_val[32'd15];
        tmp_308_reg_3181 <= data_11_val[32'd15];
        tmp_314_reg_3200 <= data_12_val[32'd15];
        tmp_320_reg_3219 <= data_13_val[32'd15];
        tmp_326_reg_3238 <= data_14_val[32'd15];
        tmp_332_reg_3257 <= data_15_val[32'd15];
        tmp_reg_2972 <= data_0_val[32'd15];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_40_fu_314_p2 = (trunc_ln46_s_fu_262_p4 + zext_ln46_40_fu_310_p1);

assign add_ln46_41_fu_396_p2 = (trunc_ln46_37_fu_344_p4 + zext_ln46_41_fu_392_p1);

assign add_ln46_42_fu_478_p2 = (trunc_ln46_38_fu_426_p4 + zext_ln46_42_fu_474_p1);

assign add_ln46_43_fu_560_p2 = (trunc_ln46_39_fu_508_p4 + zext_ln46_43_fu_556_p1);

assign add_ln46_44_fu_642_p2 = (trunc_ln46_40_fu_590_p4 + zext_ln46_44_fu_638_p1);

assign add_ln46_45_fu_724_p2 = (trunc_ln46_41_fu_672_p4 + zext_ln46_45_fu_720_p1);

assign add_ln46_46_fu_806_p2 = (trunc_ln46_42_fu_754_p4 + zext_ln46_46_fu_802_p1);

assign add_ln46_47_fu_888_p2 = (trunc_ln46_43_fu_836_p4 + zext_ln46_47_fu_884_p1);

assign add_ln46_48_fu_970_p2 = (trunc_ln46_44_fu_918_p4 + zext_ln46_48_fu_966_p1);

assign add_ln46_49_fu_1052_p2 = (trunc_ln46_45_fu_1000_p4 + zext_ln46_49_fu_1048_p1);

assign add_ln46_50_fu_1134_p2 = (trunc_ln46_46_fu_1082_p4 + zext_ln46_50_fu_1130_p1);

assign add_ln46_51_fu_1216_p2 = (trunc_ln46_47_fu_1164_p4 + zext_ln46_51_fu_1212_p1);

assign add_ln46_52_fu_1298_p2 = (trunc_ln46_48_fu_1246_p4 + zext_ln46_52_fu_1294_p1);

assign add_ln46_53_fu_1380_p2 = (trunc_ln46_49_fu_1328_p4 + zext_ln46_53_fu_1376_p1);

assign add_ln46_54_fu_1462_p2 = (trunc_ln46_50_fu_1410_p4 + zext_ln46_54_fu_1458_p1);

assign add_ln46_fu_232_p2 = (trunc_ln_fu_180_p4 + zext_ln46_fu_228_p1);

assign and_ln46_100_fu_2238_p2 = (tmp_301_fu_2225_p3 | not_tmp_353_fu_2232_p2);

assign and_ln46_102_fu_2319_p2 = (tmp_307_fu_2306_p3 | not_tmp_360_fu_2313_p2);

assign and_ln46_104_fu_2400_p2 = (tmp_313_fu_2387_p3 | not_tmp_367_fu_2394_p2);

assign and_ln46_106_fu_2481_p2 = (tmp_319_fu_2468_p3 | not_tmp_374_fu_2475_p2);

assign and_ln46_108_fu_2562_p2 = (tmp_325_fu_2549_p3 | not_tmp_381_fu_2556_p2);

assign and_ln46_110_fu_2643_p2 = (tmp_331_fu_2630_p3 | not_tmp_388_fu_2637_p2);

assign and_ln46_112_fu_2724_p2 = (tmp_337_fu_2711_p3 | not_tmp_395_fu_2718_p2);

assign and_ln46_75_fu_304_p2 = (tmp_250_fu_272_p3 & or_ln46_126_fu_298_p2);

assign and_ln46_76_fu_386_p2 = (tmp_255_fu_354_p3 & or_ln46_129_fu_380_p2);

assign and_ln46_77_fu_468_p2 = (tmp_261_fu_436_p3 & or_ln46_132_fu_462_p2);

assign and_ln46_78_fu_550_p2 = (tmp_267_fu_518_p3 & or_ln46_135_fu_544_p2);

assign and_ln46_79_fu_632_p2 = (tmp_273_fu_600_p3 & or_ln46_138_fu_626_p2);

assign and_ln46_80_fu_714_p2 = (tmp_279_fu_682_p3 & or_ln46_141_fu_708_p2);

assign and_ln46_81_fu_796_p2 = (tmp_285_fu_764_p3 & or_ln46_144_fu_790_p2);

assign and_ln46_82_fu_1509_p2 = (tmp_248_fu_1496_p3 | not_tmp_290_fu_1503_p2);

assign and_ln46_83_fu_878_p2 = (tmp_291_fu_846_p3 & or_ln46_147_fu_872_p2);

assign and_ln46_84_fu_1590_p2 = (tmp_253_fu_1577_p3 | not_tmp_297_fu_1584_p2);

assign and_ln46_85_fu_960_p2 = (tmp_297_fu_928_p3 & or_ln46_150_fu_954_p2);

assign and_ln46_86_fu_1671_p2 = (tmp_259_fu_1658_p3 | not_tmp_304_fu_1665_p2);

assign and_ln46_87_fu_1042_p2 = (tmp_303_fu_1010_p3 & or_ln46_153_fu_1036_p2);

assign and_ln46_88_fu_1752_p2 = (tmp_265_fu_1739_p3 | not_tmp_311_fu_1746_p2);

assign and_ln46_89_fu_1124_p2 = (tmp_309_fu_1092_p3 & or_ln46_156_fu_1118_p2);

assign and_ln46_90_fu_1833_p2 = (tmp_271_fu_1820_p3 | not_tmp_318_fu_1827_p2);

assign and_ln46_91_fu_1206_p2 = (tmp_315_fu_1174_p3 & or_ln46_159_fu_1200_p2);

assign and_ln46_92_fu_1914_p2 = (tmp_277_fu_1901_p3 | not_tmp_325_fu_1908_p2);

assign and_ln46_93_fu_1288_p2 = (tmp_321_fu_1256_p3 & or_ln46_162_fu_1282_p2);

assign and_ln46_94_fu_1995_p2 = (tmp_283_fu_1982_p3 | not_tmp_332_fu_1989_p2);

assign and_ln46_95_fu_1370_p2 = (tmp_327_fu_1338_p3 & or_ln46_165_fu_1364_p2);

assign and_ln46_96_fu_2076_p2 = (tmp_289_fu_2063_p3 | not_tmp_339_fu_2070_p2);

assign and_ln46_97_fu_1452_p2 = (tmp_333_fu_1420_p3 & or_ln46_168_fu_1446_p2);

assign and_ln46_98_fu_2157_p2 = (tmp_295_fu_2144_p3 | not_tmp_346_fu_2151_p2);

assign and_ln46_fu_222_p2 = (tmp_245_fu_190_p3 & or_ln46_fu_216_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = res_0_0_fu_1557_p3;

assign ap_return_1 = res_1_0_fu_1638_p3;

assign ap_return_10 = res_10_0_fu_2367_p3;

assign ap_return_11 = res_11_0_fu_2448_p3;

assign ap_return_12 = res_12_0_fu_2529_p3;

assign ap_return_13 = res_13_0_fu_2610_p3;

assign ap_return_14 = res_1445_0_fu_2691_p3;

assign ap_return_15 = res_15_0_fu_2772_p3;

assign ap_return_2 = res_2_0_fu_1719_p3;

assign ap_return_3 = res_3_0_fu_1800_p3;

assign ap_return_4 = res_4_0_fu_1881_p3;

assign ap_return_5 = res_5_0_fu_1962_p3;

assign ap_return_6 = res_6_0_fu_2043_p3;

assign ap_return_7 = res_7_0_fu_2124_p3;

assign ap_return_8 = res_8_0_fu_2205_p3;

assign ap_return_9 = res_9_0_fu_2286_p3;

assign empty_50_fu_1596_p2 = (icmp_ln46_84_reg_3005 & and_ln46_84_fu_1590_p2);

assign empty_51_fu_1677_p2 = (icmp_ln46_86_reg_3024 & and_ln46_86_fu_1671_p2);

assign empty_52_fu_1758_p2 = (icmp_ln46_88_reg_3043 & and_ln46_88_fu_1752_p2);

assign empty_53_fu_1839_p2 = (icmp_ln46_90_reg_3062 & and_ln46_90_fu_1833_p2);

assign empty_54_fu_1920_p2 = (icmp_ln46_92_reg_3081 & and_ln46_92_fu_1914_p2);

assign empty_55_fu_2001_p2 = (icmp_ln46_94_reg_3100 & and_ln46_94_fu_1995_p2);

assign empty_56_fu_2082_p2 = (icmp_ln46_96_reg_3119 & and_ln46_96_fu_2076_p2);

assign empty_57_fu_2163_p2 = (icmp_ln46_98_reg_3138 & and_ln46_98_fu_2157_p2);

assign empty_58_fu_2244_p2 = (icmp_ln46_100_reg_3157 & and_ln46_100_fu_2238_p2);

assign empty_59_fu_2325_p2 = (icmp_ln46_102_reg_3176 & and_ln46_102_fu_2319_p2);

assign empty_60_fu_2406_p2 = (icmp_ln46_104_reg_3195 & and_ln46_104_fu_2400_p2);

assign empty_61_fu_2487_p2 = (icmp_ln46_106_reg_3214 & and_ln46_106_fu_2481_p2);

assign empty_62_fu_2568_p2 = (icmp_ln46_108_reg_3233 & and_ln46_108_fu_2562_p2);

assign empty_63_fu_2649_p2 = (icmp_ln46_110_reg_3252 & and_ln46_110_fu_2643_p2);

assign empty_64_fu_2730_p2 = (icmp_ln46_112_reg_3271 & and_ln46_112_fu_2724_p2);

assign empty_fu_1515_p2 = (icmp_ln46_82_reg_2986 & and_ln46_82_fu_1509_p2);

assign icmp_ln45_40_fu_1565_p2 = (($signed(data_1_val_read_reg_2960) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_41_fu_1646_p2 = (($signed(data_2_val_read_reg_2954) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_42_fu_1727_p2 = (($signed(data_3_val_read_reg_2948) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_43_fu_1808_p2 = (($signed(data_4_val_read_reg_2942) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_44_fu_1889_p2 = (($signed(data_5_val_read_reg_2936) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_45_fu_1970_p2 = (($signed(data_6_val_read_reg_2930) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_46_fu_2051_p2 = (($signed(data_7_val_read_reg_2924) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_47_fu_2132_p2 = (($signed(data_8_val_read_reg_2918) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_48_fu_2213_p2 = (($signed(data_9_val_read_reg_2912) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_49_fu_2294_p2 = (($signed(data_10_val_read_reg_2906) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_50_fu_2375_p2 = (($signed(data_11_val_read_reg_2900) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_51_fu_2456_p2 = (($signed(data_12_val_read_reg_2894) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_52_fu_2537_p2 = (($signed(data_13_val_read_reg_2888) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_53_fu_2618_p2 = (($signed(data_14_val_read_reg_2882) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_54_fu_2699_p2 = (($signed(data_15_val_read_reg_2876) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_1484_p2 = (($signed(data_0_val_read_reg_2966) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_100_fu_986_p2 = ((tmp_300_fu_976_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_101_fu_1022_p2 = ((trunc_ln46_67_fu_1018_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_102_fu_1068_p2 = ((tmp_306_fu_1058_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_103_fu_1104_p2 = ((trunc_ln46_68_fu_1100_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_104_fu_1150_p2 = ((tmp_312_fu_1140_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_105_fu_1186_p2 = ((trunc_ln46_69_fu_1182_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_106_fu_1232_p2 = ((tmp_318_fu_1222_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_107_fu_1268_p2 = ((trunc_ln46_70_fu_1264_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_108_fu_1314_p2 = ((tmp_324_fu_1304_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_109_fu_1350_p2 = ((trunc_ln46_71_fu_1346_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_110_fu_1396_p2 = ((tmp_330_fu_1386_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_111_fu_1432_p2 = ((trunc_ln46_72_fu_1428_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_112_fu_1478_p2 = ((tmp_336_fu_1468_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_82_fu_248_p2 = ((tmp_s_fu_238_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_83_fu_284_p2 = ((trunc_ln46_58_fu_280_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_84_fu_330_p2 = ((tmp_244_fu_320_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_85_fu_366_p2 = ((trunc_ln46_59_fu_362_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_86_fu_412_p2 = ((tmp_258_fu_402_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_87_fu_448_p2 = ((trunc_ln46_60_fu_444_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_88_fu_494_p2 = ((tmp_264_fu_484_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_89_fu_530_p2 = ((trunc_ln46_61_fu_526_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_90_fu_576_p2 = ((tmp_270_fu_566_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_91_fu_612_p2 = ((trunc_ln46_62_fu_608_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_92_fu_658_p2 = ((tmp_276_fu_648_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_93_fu_694_p2 = ((trunc_ln46_63_fu_690_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_94_fu_740_p2 = ((tmp_282_fu_730_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_95_fu_776_p2 = ((trunc_ln46_64_fu_772_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_96_fu_822_p2 = ((tmp_288_fu_812_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_97_fu_858_p2 = ((trunc_ln46_65_fu_854_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_98_fu_904_p2 = ((tmp_294_fu_894_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_99_fu_940_p2 = ((trunc_ln46_66_fu_936_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_202_p2 = ((trunc_ln46_fu_198_p1 != 7'd0) ? 1'b1 : 1'b0);

assign not_tmp_290_fu_1503_p2 = (tmp_246_fu_1489_p3 ^ 1'd1);

assign not_tmp_297_fu_1584_p2 = (tmp_251_fu_1570_p3 ^ 1'd1);

assign not_tmp_304_fu_1665_p2 = (tmp_256_fu_1651_p3 ^ 1'd1);

assign not_tmp_311_fu_1746_p2 = (tmp_262_fu_1732_p3 ^ 1'd1);

assign not_tmp_318_fu_1827_p2 = (tmp_268_fu_1813_p3 ^ 1'd1);

assign not_tmp_325_fu_1908_p2 = (tmp_274_fu_1894_p3 ^ 1'd1);

assign not_tmp_332_fu_1989_p2 = (tmp_280_fu_1975_p3 ^ 1'd1);

assign not_tmp_339_fu_2070_p2 = (tmp_286_fu_2056_p3 ^ 1'd1);

assign not_tmp_346_fu_2151_p2 = (tmp_292_fu_2137_p3 ^ 1'd1);

assign not_tmp_353_fu_2232_p2 = (tmp_298_fu_2218_p3 ^ 1'd1);

assign not_tmp_360_fu_2313_p2 = (tmp_304_fu_2299_p3 ^ 1'd1);

assign not_tmp_367_fu_2394_p2 = (tmp_310_fu_2380_p3 ^ 1'd1);

assign not_tmp_374_fu_2475_p2 = (tmp_316_fu_2461_p3 ^ 1'd1);

assign not_tmp_381_fu_2556_p2 = (tmp_322_fu_2542_p3 ^ 1'd1);

assign not_tmp_388_fu_2637_p2 = (tmp_328_fu_2623_p3 ^ 1'd1);

assign not_tmp_395_fu_2718_p2 = (tmp_334_fu_2704_p3 ^ 1'd1);

assign or_ln46_124_fu_1520_p2 = (tmp_reg_2972 | empty_fu_1515_p2);

assign or_ln46_125_fu_1531_p2 = (xor_ln46_fu_1525_p2 | tmp_reg_2972);

assign or_ln46_126_fu_298_p2 = (tmp_252_fu_290_p3 | icmp_ln46_83_fu_284_p2);

assign or_ln46_127_fu_1601_p2 = (tmp_249_reg_2991 | empty_50_fu_1596_p2);

assign or_ln46_128_fu_1612_p2 = (xor_ln46_40_fu_1606_p2 | tmp_249_reg_2991);

assign or_ln46_129_fu_380_p2 = (tmp_257_fu_372_p3 | icmp_ln46_85_fu_366_p2);

assign or_ln46_130_fu_1682_p2 = (tmp_254_reg_3010 | empty_51_fu_1677_p2);

assign or_ln46_131_fu_1693_p2 = (xor_ln46_41_fu_1687_p2 | tmp_254_reg_3010);

assign or_ln46_132_fu_462_p2 = (tmp_263_fu_454_p3 | icmp_ln46_87_fu_448_p2);

assign or_ln46_133_fu_1763_p2 = (tmp_260_reg_3029 | empty_52_fu_1758_p2);

assign or_ln46_134_fu_1774_p2 = (xor_ln46_42_fu_1768_p2 | tmp_260_reg_3029);

assign or_ln46_135_fu_544_p2 = (tmp_269_fu_536_p3 | icmp_ln46_89_fu_530_p2);

assign or_ln46_136_fu_1844_p2 = (tmp_266_reg_3048 | empty_53_fu_1839_p2);

assign or_ln46_137_fu_1855_p2 = (xor_ln46_43_fu_1849_p2 | tmp_266_reg_3048);

assign or_ln46_138_fu_626_p2 = (tmp_275_fu_618_p3 | icmp_ln46_91_fu_612_p2);

assign or_ln46_139_fu_1925_p2 = (tmp_272_reg_3067 | empty_54_fu_1920_p2);

assign or_ln46_140_fu_1936_p2 = (xor_ln46_44_fu_1930_p2 | tmp_272_reg_3067);

assign or_ln46_141_fu_708_p2 = (tmp_281_fu_700_p3 | icmp_ln46_93_fu_694_p2);

assign or_ln46_142_fu_2006_p2 = (tmp_278_reg_3086 | empty_55_fu_2001_p2);

assign or_ln46_143_fu_2017_p2 = (xor_ln46_45_fu_2011_p2 | tmp_278_reg_3086);

assign or_ln46_144_fu_790_p2 = (tmp_287_fu_782_p3 | icmp_ln46_95_fu_776_p2);

assign or_ln46_145_fu_2087_p2 = (tmp_284_reg_3105 | empty_56_fu_2082_p2);

assign or_ln46_146_fu_2098_p2 = (xor_ln46_46_fu_2092_p2 | tmp_284_reg_3105);

assign or_ln46_147_fu_872_p2 = (tmp_293_fu_864_p3 | icmp_ln46_97_fu_858_p2);

assign or_ln46_148_fu_2168_p2 = (tmp_290_reg_3124 | empty_57_fu_2163_p2);

assign or_ln46_149_fu_2179_p2 = (xor_ln46_47_fu_2173_p2 | tmp_290_reg_3124);

assign or_ln46_150_fu_954_p2 = (tmp_299_fu_946_p3 | icmp_ln46_99_fu_940_p2);

assign or_ln46_151_fu_2249_p2 = (tmp_296_reg_3143 | empty_58_fu_2244_p2);

assign or_ln46_152_fu_2260_p2 = (xor_ln46_48_fu_2254_p2 | tmp_296_reg_3143);

assign or_ln46_153_fu_1036_p2 = (tmp_305_fu_1028_p3 | icmp_ln46_101_fu_1022_p2);

assign or_ln46_154_fu_2330_p2 = (tmp_302_reg_3162 | empty_59_fu_2325_p2);

assign or_ln46_155_fu_2341_p2 = (xor_ln46_49_fu_2335_p2 | tmp_302_reg_3162);

assign or_ln46_156_fu_1118_p2 = (tmp_311_fu_1110_p3 | icmp_ln46_103_fu_1104_p2);

assign or_ln46_157_fu_2411_p2 = (tmp_308_reg_3181 | empty_60_fu_2406_p2);

assign or_ln46_158_fu_2422_p2 = (xor_ln46_50_fu_2416_p2 | tmp_308_reg_3181);

assign or_ln46_159_fu_1200_p2 = (tmp_317_fu_1192_p3 | icmp_ln46_105_fu_1186_p2);

assign or_ln46_160_fu_2492_p2 = (tmp_314_reg_3200 | empty_61_fu_2487_p2);

assign or_ln46_161_fu_2503_p2 = (xor_ln46_51_fu_2497_p2 | tmp_314_reg_3200);

assign or_ln46_162_fu_1282_p2 = (tmp_323_fu_1274_p3 | icmp_ln46_107_fu_1268_p2);

assign or_ln46_163_fu_2573_p2 = (tmp_320_reg_3219 | empty_62_fu_2568_p2);

assign or_ln46_164_fu_2584_p2 = (xor_ln46_52_fu_2578_p2 | tmp_320_reg_3219);

assign or_ln46_165_fu_1364_p2 = (tmp_329_fu_1356_p3 | icmp_ln46_109_fu_1350_p2);

assign or_ln46_166_fu_2654_p2 = (tmp_326_reg_3238 | empty_63_fu_2649_p2);

assign or_ln46_167_fu_2665_p2 = (xor_ln46_53_fu_2659_p2 | tmp_326_reg_3238);

assign or_ln46_168_fu_1446_p2 = (tmp_335_fu_1438_p3 | icmp_ln46_111_fu_1432_p2);

assign or_ln46_169_fu_2735_p2 = (tmp_332_reg_3257 | empty_64_fu_2730_p2);

assign or_ln46_170_fu_2746_p2 = (xor_ln46_54_fu_2740_p2 | tmp_332_reg_3257);

assign or_ln46_fu_216_p2 = (tmp_247_fu_208_p3 | icmp_ln46_fu_202_p2);

assign res_0_0_fu_1557_p3 = ((icmp_ln45_fu_1484_p2[0:0] == 1'b1) ? select_ln46_125_fu_1550_p3 : 2'd0);

assign res_10_0_fu_2367_p3 = ((icmp_ln45_49_fu_2294_p2[0:0] == 1'b1) ? select_ln46_155_fu_2360_p3 : 2'd0);

assign res_11_0_fu_2448_p3 = ((icmp_ln45_50_fu_2375_p2[0:0] == 1'b1) ? select_ln46_158_fu_2441_p3 : 2'd0);

assign res_12_0_fu_2529_p3 = ((icmp_ln45_51_fu_2456_p2[0:0] == 1'b1) ? select_ln46_161_fu_2522_p3 : 2'd0);

assign res_13_0_fu_2610_p3 = ((icmp_ln45_52_fu_2537_p2[0:0] == 1'b1) ? select_ln46_164_fu_2603_p3 : 2'd0);

assign res_1445_0_fu_2691_p3 = ((icmp_ln45_53_fu_2618_p2[0:0] == 1'b1) ? select_ln46_167_fu_2684_p3 : 2'd0);

assign res_15_0_fu_2772_p3 = ((icmp_ln45_54_fu_2699_p2[0:0] == 1'b1) ? select_ln46_170_fu_2765_p3 : 2'd0);

assign res_1_0_fu_1638_p3 = ((icmp_ln45_40_fu_1565_p2[0:0] == 1'b1) ? select_ln46_128_fu_1631_p3 : 2'd0);

assign res_2_0_fu_1719_p3 = ((icmp_ln45_41_fu_1646_p2[0:0] == 1'b1) ? select_ln46_131_fu_1712_p3 : 2'd0);

assign res_3_0_fu_1800_p3 = ((icmp_ln45_42_fu_1727_p2[0:0] == 1'b1) ? select_ln46_134_fu_1793_p3 : 2'd0);

assign res_4_0_fu_1881_p3 = ((icmp_ln45_43_fu_1808_p2[0:0] == 1'b1) ? select_ln46_137_fu_1874_p3 : 2'd0);

assign res_5_0_fu_1962_p3 = ((icmp_ln45_44_fu_1889_p2[0:0] == 1'b1) ? select_ln46_140_fu_1955_p3 : 2'd0);

assign res_6_0_fu_2043_p3 = ((icmp_ln45_45_fu_1970_p2[0:0] == 1'b1) ? select_ln46_143_fu_2036_p3 : 2'd0);

assign res_7_0_fu_2124_p3 = ((icmp_ln45_46_fu_2051_p2[0:0] == 1'b1) ? select_ln46_146_fu_2117_p3 : 2'd0);

assign res_8_0_fu_2205_p3 = ((icmp_ln45_47_fu_2132_p2[0:0] == 1'b1) ? select_ln46_149_fu_2198_p3 : 2'd0);

assign res_9_0_fu_2286_p3 = ((icmp_ln45_48_fu_2213_p2[0:0] == 1'b1) ? select_ln46_152_fu_2279_p3 : 2'd0);

assign select_ln46_124_fu_1542_p3 = ((or_ln46_124_fu_1520_p2[0:0] == 1'b1) ? select_ln46_fu_1536_p3 : 2'd3);

assign select_ln46_125_fu_1550_p3 = ((or_ln46_125_fu_1531_p2[0:0] == 1'b1) ? select_ln46_124_fu_1542_p3 : add_ln46_reg_2979);

assign select_ln46_126_fu_1617_p3 = ((tmp_249_reg_2991[0:0] == 1'b1) ? 2'd0 : add_ln46_40_reg_2998);

assign select_ln46_127_fu_1623_p3 = ((or_ln46_127_fu_1601_p2[0:0] == 1'b1) ? select_ln46_126_fu_1617_p3 : 2'd3);

assign select_ln46_128_fu_1631_p3 = ((or_ln46_128_fu_1612_p2[0:0] == 1'b1) ? select_ln46_127_fu_1623_p3 : add_ln46_40_reg_2998);

assign select_ln46_129_fu_1698_p3 = ((tmp_254_reg_3010[0:0] == 1'b1) ? 2'd0 : add_ln46_41_reg_3017);

assign select_ln46_130_fu_1704_p3 = ((or_ln46_130_fu_1682_p2[0:0] == 1'b1) ? select_ln46_129_fu_1698_p3 : 2'd3);

assign select_ln46_131_fu_1712_p3 = ((or_ln46_131_fu_1693_p2[0:0] == 1'b1) ? select_ln46_130_fu_1704_p3 : add_ln46_41_reg_3017);

assign select_ln46_132_fu_1779_p3 = ((tmp_260_reg_3029[0:0] == 1'b1) ? 2'd0 : add_ln46_42_reg_3036);

assign select_ln46_133_fu_1785_p3 = ((or_ln46_133_fu_1763_p2[0:0] == 1'b1) ? select_ln46_132_fu_1779_p3 : 2'd3);

assign select_ln46_134_fu_1793_p3 = ((or_ln46_134_fu_1774_p2[0:0] == 1'b1) ? select_ln46_133_fu_1785_p3 : add_ln46_42_reg_3036);

assign select_ln46_135_fu_1860_p3 = ((tmp_266_reg_3048[0:0] == 1'b1) ? 2'd0 : add_ln46_43_reg_3055);

assign select_ln46_136_fu_1866_p3 = ((or_ln46_136_fu_1844_p2[0:0] == 1'b1) ? select_ln46_135_fu_1860_p3 : 2'd3);

assign select_ln46_137_fu_1874_p3 = ((or_ln46_137_fu_1855_p2[0:0] == 1'b1) ? select_ln46_136_fu_1866_p3 : add_ln46_43_reg_3055);

assign select_ln46_138_fu_1941_p3 = ((tmp_272_reg_3067[0:0] == 1'b1) ? 2'd0 : add_ln46_44_reg_3074);

assign select_ln46_139_fu_1947_p3 = ((or_ln46_139_fu_1925_p2[0:0] == 1'b1) ? select_ln46_138_fu_1941_p3 : 2'd3);

assign select_ln46_140_fu_1955_p3 = ((or_ln46_140_fu_1936_p2[0:0] == 1'b1) ? select_ln46_139_fu_1947_p3 : add_ln46_44_reg_3074);

assign select_ln46_141_fu_2022_p3 = ((tmp_278_reg_3086[0:0] == 1'b1) ? 2'd0 : add_ln46_45_reg_3093);

assign select_ln46_142_fu_2028_p3 = ((or_ln46_142_fu_2006_p2[0:0] == 1'b1) ? select_ln46_141_fu_2022_p3 : 2'd3);

assign select_ln46_143_fu_2036_p3 = ((or_ln46_143_fu_2017_p2[0:0] == 1'b1) ? select_ln46_142_fu_2028_p3 : add_ln46_45_reg_3093);

assign select_ln46_144_fu_2103_p3 = ((tmp_284_reg_3105[0:0] == 1'b1) ? 2'd0 : add_ln46_46_reg_3112);

assign select_ln46_145_fu_2109_p3 = ((or_ln46_145_fu_2087_p2[0:0] == 1'b1) ? select_ln46_144_fu_2103_p3 : 2'd3);

assign select_ln46_146_fu_2117_p3 = ((or_ln46_146_fu_2098_p2[0:0] == 1'b1) ? select_ln46_145_fu_2109_p3 : add_ln46_46_reg_3112);

assign select_ln46_147_fu_2184_p3 = ((tmp_290_reg_3124[0:0] == 1'b1) ? 2'd0 : add_ln46_47_reg_3131);

assign select_ln46_148_fu_2190_p3 = ((or_ln46_148_fu_2168_p2[0:0] == 1'b1) ? select_ln46_147_fu_2184_p3 : 2'd3);

assign select_ln46_149_fu_2198_p3 = ((or_ln46_149_fu_2179_p2[0:0] == 1'b1) ? select_ln46_148_fu_2190_p3 : add_ln46_47_reg_3131);

assign select_ln46_150_fu_2265_p3 = ((tmp_296_reg_3143[0:0] == 1'b1) ? 2'd0 : add_ln46_48_reg_3150);

assign select_ln46_151_fu_2271_p3 = ((or_ln46_151_fu_2249_p2[0:0] == 1'b1) ? select_ln46_150_fu_2265_p3 : 2'd3);

assign select_ln46_152_fu_2279_p3 = ((or_ln46_152_fu_2260_p2[0:0] == 1'b1) ? select_ln46_151_fu_2271_p3 : add_ln46_48_reg_3150);

assign select_ln46_153_fu_2346_p3 = ((tmp_302_reg_3162[0:0] == 1'b1) ? 2'd0 : add_ln46_49_reg_3169);

assign select_ln46_154_fu_2352_p3 = ((or_ln46_154_fu_2330_p2[0:0] == 1'b1) ? select_ln46_153_fu_2346_p3 : 2'd3);

assign select_ln46_155_fu_2360_p3 = ((or_ln46_155_fu_2341_p2[0:0] == 1'b1) ? select_ln46_154_fu_2352_p3 : add_ln46_49_reg_3169);

assign select_ln46_156_fu_2427_p3 = ((tmp_308_reg_3181[0:0] == 1'b1) ? 2'd0 : add_ln46_50_reg_3188);

assign select_ln46_157_fu_2433_p3 = ((or_ln46_157_fu_2411_p2[0:0] == 1'b1) ? select_ln46_156_fu_2427_p3 : 2'd3);

assign select_ln46_158_fu_2441_p3 = ((or_ln46_158_fu_2422_p2[0:0] == 1'b1) ? select_ln46_157_fu_2433_p3 : add_ln46_50_reg_3188);

assign select_ln46_159_fu_2508_p3 = ((tmp_314_reg_3200[0:0] == 1'b1) ? 2'd0 : add_ln46_51_reg_3207);

assign select_ln46_160_fu_2514_p3 = ((or_ln46_160_fu_2492_p2[0:0] == 1'b1) ? select_ln46_159_fu_2508_p3 : 2'd3);

assign select_ln46_161_fu_2522_p3 = ((or_ln46_161_fu_2503_p2[0:0] == 1'b1) ? select_ln46_160_fu_2514_p3 : add_ln46_51_reg_3207);

assign select_ln46_162_fu_2589_p3 = ((tmp_320_reg_3219[0:0] == 1'b1) ? 2'd0 : add_ln46_52_reg_3226);

assign select_ln46_163_fu_2595_p3 = ((or_ln46_163_fu_2573_p2[0:0] == 1'b1) ? select_ln46_162_fu_2589_p3 : 2'd3);

assign select_ln46_164_fu_2603_p3 = ((or_ln46_164_fu_2584_p2[0:0] == 1'b1) ? select_ln46_163_fu_2595_p3 : add_ln46_52_reg_3226);

assign select_ln46_165_fu_2670_p3 = ((tmp_326_reg_3238[0:0] == 1'b1) ? 2'd0 : add_ln46_53_reg_3245);

assign select_ln46_166_fu_2676_p3 = ((or_ln46_166_fu_2654_p2[0:0] == 1'b1) ? select_ln46_165_fu_2670_p3 : 2'd3);

assign select_ln46_167_fu_2684_p3 = ((or_ln46_167_fu_2665_p2[0:0] == 1'b1) ? select_ln46_166_fu_2676_p3 : add_ln46_53_reg_3245);

assign select_ln46_168_fu_2751_p3 = ((tmp_332_reg_3257[0:0] == 1'b1) ? 2'd0 : add_ln46_54_reg_3264);

assign select_ln46_169_fu_2757_p3 = ((or_ln46_169_fu_2735_p2[0:0] == 1'b1) ? select_ln46_168_fu_2751_p3 : 2'd3);

assign select_ln46_170_fu_2765_p3 = ((or_ln46_170_fu_2746_p2[0:0] == 1'b1) ? select_ln46_169_fu_2757_p3 : add_ln46_54_reg_3264);

assign select_ln46_fu_1536_p3 = ((tmp_reg_2972[0:0] == 1'b1) ? 2'd0 : add_ln46_reg_2979);

assign tmp_244_fu_320_p4 = {{data_1_val[15:10]}};

assign tmp_245_fu_190_p3 = data_0_val[32'd7];

assign tmp_246_fu_1489_p3 = data_0_val_read_reg_2966[32'd9];

assign tmp_247_fu_208_p3 = data_0_val[32'd8];

assign tmp_248_fu_1496_p3 = add_ln46_reg_2979[32'd1];

assign tmp_250_fu_272_p3 = data_1_val[32'd7];

assign tmp_251_fu_1570_p3 = data_1_val_read_reg_2960[32'd9];

assign tmp_252_fu_290_p3 = data_1_val[32'd8];

assign tmp_253_fu_1577_p3 = add_ln46_40_reg_2998[32'd1];

assign tmp_255_fu_354_p3 = data_2_val[32'd7];

assign tmp_256_fu_1651_p3 = data_2_val_read_reg_2954[32'd9];

assign tmp_257_fu_372_p3 = data_2_val[32'd8];

assign tmp_258_fu_402_p4 = {{data_2_val[15:10]}};

assign tmp_259_fu_1658_p3 = add_ln46_41_reg_3017[32'd1];

assign tmp_261_fu_436_p3 = data_3_val[32'd7];

assign tmp_262_fu_1732_p3 = data_3_val_read_reg_2948[32'd9];

assign tmp_263_fu_454_p3 = data_3_val[32'd8];

assign tmp_264_fu_484_p4 = {{data_3_val[15:10]}};

assign tmp_265_fu_1739_p3 = add_ln46_42_reg_3036[32'd1];

assign tmp_267_fu_518_p3 = data_4_val[32'd7];

assign tmp_268_fu_1813_p3 = data_4_val_read_reg_2942[32'd9];

assign tmp_269_fu_536_p3 = data_4_val[32'd8];

assign tmp_270_fu_566_p4 = {{data_4_val[15:10]}};

assign tmp_271_fu_1820_p3 = add_ln46_43_reg_3055[32'd1];

assign tmp_273_fu_600_p3 = data_5_val[32'd7];

assign tmp_274_fu_1894_p3 = data_5_val_read_reg_2936[32'd9];

assign tmp_275_fu_618_p3 = data_5_val[32'd8];

assign tmp_276_fu_648_p4 = {{data_5_val[15:10]}};

assign tmp_277_fu_1901_p3 = add_ln46_44_reg_3074[32'd1];

assign tmp_279_fu_682_p3 = data_6_val[32'd7];

assign tmp_280_fu_1975_p3 = data_6_val_read_reg_2930[32'd9];

assign tmp_281_fu_700_p3 = data_6_val[32'd8];

assign tmp_282_fu_730_p4 = {{data_6_val[15:10]}};

assign tmp_283_fu_1982_p3 = add_ln46_45_reg_3093[32'd1];

assign tmp_285_fu_764_p3 = data_7_val[32'd7];

assign tmp_286_fu_2056_p3 = data_7_val_read_reg_2924[32'd9];

assign tmp_287_fu_782_p3 = data_7_val[32'd8];

assign tmp_288_fu_812_p4 = {{data_7_val[15:10]}};

assign tmp_289_fu_2063_p3 = add_ln46_46_reg_3112[32'd1];

assign tmp_291_fu_846_p3 = data_8_val[32'd7];

assign tmp_292_fu_2137_p3 = data_8_val_read_reg_2918[32'd9];

assign tmp_293_fu_864_p3 = data_8_val[32'd8];

assign tmp_294_fu_894_p4 = {{data_8_val[15:10]}};

assign tmp_295_fu_2144_p3 = add_ln46_47_reg_3131[32'd1];

assign tmp_297_fu_928_p3 = data_9_val[32'd7];

assign tmp_298_fu_2218_p3 = data_9_val_read_reg_2912[32'd9];

assign tmp_299_fu_946_p3 = data_9_val[32'd8];

assign tmp_300_fu_976_p4 = {{data_9_val[15:10]}};

assign tmp_301_fu_2225_p3 = add_ln46_48_reg_3150[32'd1];

assign tmp_303_fu_1010_p3 = data_10_val[32'd7];

assign tmp_304_fu_2299_p3 = data_10_val_read_reg_2906[32'd9];

assign tmp_305_fu_1028_p3 = data_10_val[32'd8];

assign tmp_306_fu_1058_p4 = {{data_10_val[15:10]}};

assign tmp_307_fu_2306_p3 = add_ln46_49_reg_3169[32'd1];

assign tmp_309_fu_1092_p3 = data_11_val[32'd7];

assign tmp_310_fu_2380_p3 = data_11_val_read_reg_2900[32'd9];

assign tmp_311_fu_1110_p3 = data_11_val[32'd8];

assign tmp_312_fu_1140_p4 = {{data_11_val[15:10]}};

assign tmp_313_fu_2387_p3 = add_ln46_50_reg_3188[32'd1];

assign tmp_315_fu_1174_p3 = data_12_val[32'd7];

assign tmp_316_fu_2461_p3 = data_12_val_read_reg_2894[32'd9];

assign tmp_317_fu_1192_p3 = data_12_val[32'd8];

assign tmp_318_fu_1222_p4 = {{data_12_val[15:10]}};

assign tmp_319_fu_2468_p3 = add_ln46_51_reg_3207[32'd1];

assign tmp_321_fu_1256_p3 = data_13_val[32'd7];

assign tmp_322_fu_2542_p3 = data_13_val_read_reg_2888[32'd9];

assign tmp_323_fu_1274_p3 = data_13_val[32'd8];

assign tmp_324_fu_1304_p4 = {{data_13_val[15:10]}};

assign tmp_325_fu_2549_p3 = add_ln46_52_reg_3226[32'd1];

assign tmp_327_fu_1338_p3 = data_14_val[32'd7];

assign tmp_328_fu_2623_p3 = data_14_val_read_reg_2882[32'd9];

assign tmp_329_fu_1356_p3 = data_14_val[32'd8];

assign tmp_330_fu_1386_p4 = {{data_14_val[15:10]}};

assign tmp_331_fu_2630_p3 = add_ln46_53_reg_3245[32'd1];

assign tmp_333_fu_1420_p3 = data_15_val[32'd7];

assign tmp_334_fu_2704_p3 = data_15_val_read_reg_2876[32'd9];

assign tmp_335_fu_1438_p3 = data_15_val[32'd8];

assign tmp_336_fu_1468_p4 = {{data_15_val[15:10]}};

assign tmp_337_fu_2711_p3 = add_ln46_54_reg_3264[32'd1];

assign tmp_s_fu_238_p4 = {{data_0_val[15:10]}};

assign trunc_ln46_37_fu_344_p4 = {{data_2_val[9:8]}};

assign trunc_ln46_38_fu_426_p4 = {{data_3_val[9:8]}};

assign trunc_ln46_39_fu_508_p4 = {{data_4_val[9:8]}};

assign trunc_ln46_40_fu_590_p4 = {{data_5_val[9:8]}};

assign trunc_ln46_41_fu_672_p4 = {{data_6_val[9:8]}};

assign trunc_ln46_42_fu_754_p4 = {{data_7_val[9:8]}};

assign trunc_ln46_43_fu_836_p4 = {{data_8_val[9:8]}};

assign trunc_ln46_44_fu_918_p4 = {{data_9_val[9:8]}};

assign trunc_ln46_45_fu_1000_p4 = {{data_10_val[9:8]}};

assign trunc_ln46_46_fu_1082_p4 = {{data_11_val[9:8]}};

assign trunc_ln46_47_fu_1164_p4 = {{data_12_val[9:8]}};

assign trunc_ln46_48_fu_1246_p4 = {{data_13_val[9:8]}};

assign trunc_ln46_49_fu_1328_p4 = {{data_14_val[9:8]}};

assign trunc_ln46_50_fu_1410_p4 = {{data_15_val[9:8]}};

assign trunc_ln46_58_fu_280_p1 = data_1_val[6:0];

assign trunc_ln46_59_fu_362_p1 = data_2_val[6:0];

assign trunc_ln46_60_fu_444_p1 = data_3_val[6:0];

assign trunc_ln46_61_fu_526_p1 = data_4_val[6:0];

assign trunc_ln46_62_fu_608_p1 = data_5_val[6:0];

assign trunc_ln46_63_fu_690_p1 = data_6_val[6:0];

assign trunc_ln46_64_fu_772_p1 = data_7_val[6:0];

assign trunc_ln46_65_fu_854_p1 = data_8_val[6:0];

assign trunc_ln46_66_fu_936_p1 = data_9_val[6:0];

assign trunc_ln46_67_fu_1018_p1 = data_10_val[6:0];

assign trunc_ln46_68_fu_1100_p1 = data_11_val[6:0];

assign trunc_ln46_69_fu_1182_p1 = data_12_val[6:0];

assign trunc_ln46_70_fu_1264_p1 = data_13_val[6:0];

assign trunc_ln46_71_fu_1346_p1 = data_14_val[6:0];

assign trunc_ln46_72_fu_1428_p1 = data_15_val[6:0];

assign trunc_ln46_fu_198_p1 = data_0_val[6:0];

assign trunc_ln46_s_fu_262_p4 = {{data_1_val[9:8]}};

assign trunc_ln_fu_180_p4 = {{data_0_val[9:8]}};

assign xor_ln46_40_fu_1606_p2 = (empty_50_fu_1596_p2 ^ 1'd1);

assign xor_ln46_41_fu_1687_p2 = (empty_51_fu_1677_p2 ^ 1'd1);

assign xor_ln46_42_fu_1768_p2 = (empty_52_fu_1758_p2 ^ 1'd1);

assign xor_ln46_43_fu_1849_p2 = (empty_53_fu_1839_p2 ^ 1'd1);

assign xor_ln46_44_fu_1930_p2 = (empty_54_fu_1920_p2 ^ 1'd1);

assign xor_ln46_45_fu_2011_p2 = (empty_55_fu_2001_p2 ^ 1'd1);

assign xor_ln46_46_fu_2092_p2 = (empty_56_fu_2082_p2 ^ 1'd1);

assign xor_ln46_47_fu_2173_p2 = (empty_57_fu_2163_p2 ^ 1'd1);

assign xor_ln46_48_fu_2254_p2 = (empty_58_fu_2244_p2 ^ 1'd1);

assign xor_ln46_49_fu_2335_p2 = (empty_59_fu_2325_p2 ^ 1'd1);

assign xor_ln46_50_fu_2416_p2 = (empty_60_fu_2406_p2 ^ 1'd1);

assign xor_ln46_51_fu_2497_p2 = (empty_61_fu_2487_p2 ^ 1'd1);

assign xor_ln46_52_fu_2578_p2 = (empty_62_fu_2568_p2 ^ 1'd1);

assign xor_ln46_53_fu_2659_p2 = (empty_63_fu_2649_p2 ^ 1'd1);

assign xor_ln46_54_fu_2740_p2 = (empty_64_fu_2730_p2 ^ 1'd1);

assign xor_ln46_fu_1525_p2 = (empty_fu_1515_p2 ^ 1'd1);

assign zext_ln46_40_fu_310_p1 = and_ln46_75_fu_304_p2;

assign zext_ln46_41_fu_392_p1 = and_ln46_76_fu_386_p2;

assign zext_ln46_42_fu_474_p1 = and_ln46_77_fu_468_p2;

assign zext_ln46_43_fu_556_p1 = and_ln46_78_fu_550_p2;

assign zext_ln46_44_fu_638_p1 = and_ln46_79_fu_632_p2;

assign zext_ln46_45_fu_720_p1 = and_ln46_80_fu_714_p2;

assign zext_ln46_46_fu_802_p1 = and_ln46_81_fu_796_p2;

assign zext_ln46_47_fu_884_p1 = and_ln46_83_fu_878_p2;

assign zext_ln46_48_fu_966_p1 = and_ln46_85_fu_960_p2;

assign zext_ln46_49_fu_1048_p1 = and_ln46_87_fu_1042_p2;

assign zext_ln46_50_fu_1130_p1 = and_ln46_89_fu_1124_p2;

assign zext_ln46_51_fu_1212_p1 = and_ln46_91_fu_1206_p2;

assign zext_ln46_52_fu_1294_p1 = and_ln46_93_fu_1288_p2;

assign zext_ln46_53_fu_1376_p1 = and_ln46_95_fu_1370_p2;

assign zext_ln46_54_fu_1458_p1 = and_ln46_97_fu_1452_p2;

assign zext_ln46_fu_228_p1 = and_ln46_fu_222_p2;

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_2_0_4_0_0_relu_config15_s
