-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config22_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (14 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (14 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_normalize_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config22_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal trunc_ln_fu_262_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln_fu_166_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_1_fu_174_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_2_fu_182_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_3_fu_190_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_4_fu_198_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_5_fu_206_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_6_fu_214_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_7_fu_222_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_8_fu_230_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_9_fu_238_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_s_fu_246_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_10_fu_254_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln54_fu_272_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_11_fu_276_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_12_fu_284_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln54_13_fu_292_p3 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= shl_ln_fu_166_p3;
    ap_return_1 <= shl_ln54_1_fu_174_p3;
    ap_return_10 <= shl_ln54_s_fu_246_p3;
    ap_return_11 <= shl_ln54_10_fu_254_p3;
    ap_return_12 <= sext_ln54_fu_272_p1;
    ap_return_13 <= shl_ln54_11_fu_276_p3;
    ap_return_14 <= shl_ln54_12_fu_284_p3;
    ap_return_15 <= data_15_val;
    ap_return_16 <= shl_ln54_13_fu_292_p3;
    ap_return_2 <= shl_ln54_2_fu_182_p3;
    ap_return_3 <= shl_ln54_3_fu_190_p3;
    ap_return_4 <= shl_ln54_4_fu_198_p3;
    ap_return_5 <= shl_ln54_5_fu_206_p3;
    ap_return_6 <= shl_ln54_6_fu_214_p3;
    ap_return_7 <= shl_ln54_7_fu_222_p3;
    ap_return_8 <= shl_ln54_8_fu_230_p3;
    ap_return_9 <= shl_ln54_9_fu_238_p3;
        sext_ln54_fu_272_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_262_p4),16));

    shl_ln54_10_fu_254_p3 <= (data_11_val & ap_const_lv1_0);
    shl_ln54_11_fu_276_p3 <= (data_13_val & ap_const_lv1_0);
    shl_ln54_12_fu_284_p3 <= (data_14_val & ap_const_lv1_0);
    shl_ln54_13_fu_292_p3 <= (data_16_val & ap_const_lv1_0);
    shl_ln54_1_fu_174_p3 <= (data_1_val & ap_const_lv1_0);
    shl_ln54_2_fu_182_p3 <= (data_2_val & ap_const_lv1_0);
    shl_ln54_3_fu_190_p3 <= (data_3_val & ap_const_lv1_0);
    shl_ln54_4_fu_198_p3 <= (data_4_val & ap_const_lv1_0);
    shl_ln54_5_fu_206_p3 <= (data_5_val & ap_const_lv1_0);
    shl_ln54_6_fu_214_p3 <= (data_6_val & ap_const_lv1_0);
    shl_ln54_7_fu_222_p3 <= (data_7_val & ap_const_lv1_0);
    shl_ln54_8_fu_230_p3 <= (data_8_val & ap_const_lv1_0);
    shl_ln54_9_fu_238_p3 <= (data_9_val & ap_const_lv1_0);
    shl_ln54_s_fu_246_p3 <= (data_10_val & ap_const_lv1_0);
    shl_ln_fu_166_p3 <= (data_0_val & ap_const_lv1_0);
    trunc_ln_fu_262_p4 <= data_12_val(15 downto 2);
end behav;
