Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    dense1:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    dense1_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense2:
      Precision:
        bias: fixed<4,1>
        result: fixed<16,6>
        weight: fixed<4,1>
      Trace: false
    dense2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    input1:
      Precision:
        result: fixed<16,6>
      Trace: false
    linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: ufixed<8,0,RND_CONV,SAT>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model './hlsTmp/keras_model.h5'
OutputDir: ./hlsTmp
OutputPredictions: null
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
Stamp: 90ccDaF3
Version: 1.0.0
