// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_concatenate1d_ap_fixed_ap_fixed_ap_fixed_16_6_5_3_0_config3_s (
        ap_ready,
        data1_val,
        data2_val,
        ap_return_0,
        ap_return_1,
        ap_rst
);


output   ap_ready;
input  [15:0] data1_val;
input  [15:0] data2_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
input   ap_rst;

assign ap_ready = 1'b1;

assign ap_return_0 = data1_val;

assign ap_return_1 = data2_val;

endmodule //myproject_concatenate1d_ap_fixed_ap_fixed_ap_fixed_16_6_5_3_0_config3_s
