// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_2_0_4_0_0_relu_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
output  [1:0] ap_return_0;
output  [1:0] ap_return_1;
output  [1:0] ap_return_2;
output  [1:0] ap_return_3;
output  [1:0] ap_return_4;
output  [1:0] ap_return_5;
output  [1:0] ap_return_6;
output  [1:0] ap_return_7;
output  [1:0] ap_return_8;
output  [1:0] ap_return_9;
output  [1:0] ap_return_10;
output  [1:0] ap_return_11;
output  [1:0] ap_return_12;
output  [1:0] ap_return_13;
output  [1:0] ap_return_14;
output  [1:0] ap_return_15;
output  [1:0] ap_return_16;
output  [1:0] ap_return_17;
output  [1:0] ap_return_18;
output  [1:0] ap_return_19;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] data_19_val_read_reg_3584;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] data_18_val_read_reg_3590;
reg   [15:0] data_17_val_read_reg_3596;
reg   [15:0] data_16_val_read_reg_3602;
reg   [15:0] data_15_val_read_reg_3608;
reg   [15:0] data_14_val_read_reg_3614;
reg   [15:0] data_13_val_read_reg_3620;
reg   [15:0] data_12_val_read_reg_3626;
reg   [15:0] data_11_val_read_reg_3632;
reg   [15:0] data_10_val_read_reg_3638;
reg   [15:0] data_9_val_read_reg_3644;
reg   [15:0] data_8_val_read_reg_3650;
reg   [15:0] data_7_val_read_reg_3656;
reg   [15:0] data_6_val_read_reg_3662;
reg   [15:0] data_5_val_read_reg_3668;
reg   [15:0] data_4_val_read_reg_3674;
reg   [15:0] data_3_val_read_reg_3680;
reg   [15:0] data_2_val_read_reg_3686;
reg   [15:0] data_1_val_read_reg_3692;
reg   [15:0] data_0_val_read_reg_3698;
reg   [0:0] tmp_reg_3704;
wire   [1:0] add_ln46_fu_264_p2;
reg   [1:0] add_ln46_reg_3711;
wire   [0:0] icmp_ln46_1_fu_280_p2;
reg   [0:0] icmp_ln46_1_reg_3718;
reg   [0:0] tmp_5_reg_3723;
wire   [1:0] add_ln46_1_fu_346_p2;
reg   [1:0] add_ln46_1_reg_3730;
wire   [0:0] icmp_ln46_3_fu_362_p2;
reg   [0:0] icmp_ln46_3_reg_3737;
reg   [0:0] tmp_11_reg_3742;
wire   [1:0] add_ln46_2_fu_428_p2;
reg   [1:0] add_ln46_2_reg_3749;
wire   [0:0] icmp_ln46_5_fu_444_p2;
reg   [0:0] icmp_ln46_5_reg_3756;
reg   [0:0] tmp_17_reg_3761;
wire   [1:0] add_ln46_3_fu_510_p2;
reg   [1:0] add_ln46_3_reg_3768;
wire   [0:0] icmp_ln46_7_fu_526_p2;
reg   [0:0] icmp_ln46_7_reg_3775;
reg   [0:0] tmp_23_reg_3780;
wire   [1:0] add_ln46_4_fu_592_p2;
reg   [1:0] add_ln46_4_reg_3787;
wire   [0:0] icmp_ln46_9_fu_608_p2;
reg   [0:0] icmp_ln46_9_reg_3794;
reg   [0:0] tmp_29_reg_3799;
wire   [1:0] add_ln46_5_fu_674_p2;
reg   [1:0] add_ln46_5_reg_3806;
wire   [0:0] icmp_ln46_11_fu_690_p2;
reg   [0:0] icmp_ln46_11_reg_3813;
reg   [0:0] tmp_35_reg_3818;
wire   [1:0] add_ln46_6_fu_756_p2;
reg   [1:0] add_ln46_6_reg_3825;
wire   [0:0] icmp_ln46_13_fu_772_p2;
reg   [0:0] icmp_ln46_13_reg_3832;
reg   [0:0] tmp_41_reg_3837;
wire   [1:0] add_ln46_7_fu_838_p2;
reg   [1:0] add_ln46_7_reg_3844;
wire   [0:0] icmp_ln46_15_fu_854_p2;
reg   [0:0] icmp_ln46_15_reg_3851;
reg   [0:0] tmp_47_reg_3856;
wire   [1:0] add_ln46_8_fu_920_p2;
reg   [1:0] add_ln46_8_reg_3863;
wire   [0:0] icmp_ln46_17_fu_936_p2;
reg   [0:0] icmp_ln46_17_reg_3870;
reg   [0:0] tmp_53_reg_3875;
wire   [1:0] add_ln46_9_fu_1002_p2;
reg   [1:0] add_ln46_9_reg_3882;
wire   [0:0] icmp_ln46_19_fu_1018_p2;
reg   [0:0] icmp_ln46_19_reg_3889;
reg   [0:0] tmp_59_reg_3894;
wire   [1:0] add_ln46_10_fu_1084_p2;
reg   [1:0] add_ln46_10_reg_3901;
wire   [0:0] icmp_ln46_21_fu_1100_p2;
reg   [0:0] icmp_ln46_21_reg_3908;
reg   [0:0] tmp_65_reg_3913;
wire   [1:0] add_ln46_11_fu_1166_p2;
reg   [1:0] add_ln46_11_reg_3920;
wire   [0:0] icmp_ln46_23_fu_1182_p2;
reg   [0:0] icmp_ln46_23_reg_3927;
reg   [0:0] tmp_71_reg_3932;
wire   [1:0] add_ln46_12_fu_1248_p2;
reg   [1:0] add_ln46_12_reg_3939;
wire   [0:0] icmp_ln46_25_fu_1264_p2;
reg   [0:0] icmp_ln46_25_reg_3946;
reg   [0:0] tmp_77_reg_3951;
wire   [1:0] add_ln46_13_fu_1330_p2;
reg   [1:0] add_ln46_13_reg_3958;
wire   [0:0] icmp_ln46_27_fu_1346_p2;
reg   [0:0] icmp_ln46_27_reg_3965;
reg   [0:0] tmp_83_reg_3970;
wire   [1:0] add_ln46_14_fu_1412_p2;
reg   [1:0] add_ln46_14_reg_3977;
wire   [0:0] icmp_ln46_29_fu_1428_p2;
reg   [0:0] icmp_ln46_29_reg_3984;
reg   [0:0] tmp_89_reg_3989;
wire   [1:0] add_ln46_15_fu_1494_p2;
reg   [1:0] add_ln46_15_reg_3996;
wire   [0:0] icmp_ln46_31_fu_1510_p2;
reg   [0:0] icmp_ln46_31_reg_4003;
reg   [0:0] tmp_95_reg_4008;
wire   [1:0] add_ln46_16_fu_1576_p2;
reg   [1:0] add_ln46_16_reg_4015;
wire   [0:0] icmp_ln46_33_fu_1592_p2;
reg   [0:0] icmp_ln46_33_reg_4022;
reg   [0:0] tmp_101_reg_4027;
wire   [1:0] add_ln46_17_fu_1658_p2;
reg   [1:0] add_ln46_17_reg_4034;
wire   [0:0] icmp_ln46_35_fu_1674_p2;
reg   [0:0] icmp_ln46_35_reg_4041;
reg   [0:0] tmp_107_reg_4046;
wire   [1:0] add_ln46_18_fu_1740_p2;
reg   [1:0] add_ln46_18_reg_4053;
wire   [0:0] icmp_ln46_37_fu_1756_p2;
reg   [0:0] icmp_ln46_37_reg_4060;
reg   [0:0] tmp_113_reg_4065;
wire   [1:0] add_ln46_19_fu_1822_p2;
reg   [1:0] add_ln46_19_reg_4072;
wire   [0:0] icmp_ln46_39_fu_1838_p2;
reg   [0:0] icmp_ln46_39_reg_4079;
wire    ap_block_pp0_stage0;
wire   [6:0] trunc_ln46_fu_230_p1;
wire   [0:0] tmp_3_fu_240_p3;
wire   [0:0] icmp_ln46_fu_234_p2;
wire   [0:0] or_ln46_fu_248_p2;
wire   [0:0] tmp_1_fu_222_p3;
wire   [0:0] and_ln46_fu_254_p2;
wire   [1:0] trunc_ln_fu_212_p4;
wire   [1:0] zext_ln46_fu_260_p1;
wire   [5:0] tmp_s_fu_270_p4;
wire   [6:0] trunc_ln46_19_fu_312_p1;
wire   [0:0] tmp_8_fu_322_p3;
wire   [0:0] icmp_ln46_2_fu_316_p2;
wire   [0:0] or_ln46_3_fu_330_p2;
wire   [0:0] tmp_6_fu_304_p3;
wire   [0:0] and_ln46_2_fu_336_p2;
wire   [1:0] trunc_ln46_1_fu_294_p4;
wire   [1:0] zext_ln46_1_fu_342_p1;
wire   [5:0] tmp_9_fu_352_p4;
wire   [6:0] trunc_ln46_20_fu_394_p1;
wire   [0:0] tmp_14_fu_404_p3;
wire   [0:0] icmp_ln46_4_fu_398_p2;
wire   [0:0] or_ln46_6_fu_412_p2;
wire   [0:0] tmp_12_fu_386_p3;
wire   [0:0] and_ln46_4_fu_418_p2;
wire   [1:0] trunc_ln46_2_fu_376_p4;
wire   [1:0] zext_ln46_2_fu_424_p1;
wire   [5:0] tmp_15_fu_434_p4;
wire   [6:0] trunc_ln46_21_fu_476_p1;
wire   [0:0] tmp_20_fu_486_p3;
wire   [0:0] icmp_ln46_6_fu_480_p2;
wire   [0:0] or_ln46_9_fu_494_p2;
wire   [0:0] tmp_18_fu_468_p3;
wire   [0:0] and_ln46_6_fu_500_p2;
wire   [1:0] trunc_ln46_3_fu_458_p4;
wire   [1:0] zext_ln46_3_fu_506_p1;
wire   [5:0] tmp_21_fu_516_p4;
wire   [6:0] trunc_ln46_22_fu_558_p1;
wire   [0:0] tmp_26_fu_568_p3;
wire   [0:0] icmp_ln46_8_fu_562_p2;
wire   [0:0] or_ln46_12_fu_576_p2;
wire   [0:0] tmp_24_fu_550_p3;
wire   [0:0] and_ln46_8_fu_582_p2;
wire   [1:0] trunc_ln46_4_fu_540_p4;
wire   [1:0] zext_ln46_4_fu_588_p1;
wire   [5:0] tmp_27_fu_598_p4;
wire   [6:0] trunc_ln46_23_fu_640_p1;
wire   [0:0] tmp_32_fu_650_p3;
wire   [0:0] icmp_ln46_10_fu_644_p2;
wire   [0:0] or_ln46_15_fu_658_p2;
wire   [0:0] tmp_30_fu_632_p3;
wire   [0:0] and_ln46_10_fu_664_p2;
wire   [1:0] trunc_ln46_5_fu_622_p4;
wire   [1:0] zext_ln46_5_fu_670_p1;
wire   [5:0] tmp_33_fu_680_p4;
wire   [6:0] trunc_ln46_24_fu_722_p1;
wire   [0:0] tmp_38_fu_732_p3;
wire   [0:0] icmp_ln46_12_fu_726_p2;
wire   [0:0] or_ln46_18_fu_740_p2;
wire   [0:0] tmp_36_fu_714_p3;
wire   [0:0] and_ln46_12_fu_746_p2;
wire   [1:0] trunc_ln46_6_fu_704_p4;
wire   [1:0] zext_ln46_6_fu_752_p1;
wire   [5:0] tmp_39_fu_762_p4;
wire   [6:0] trunc_ln46_25_fu_804_p1;
wire   [0:0] tmp_44_fu_814_p3;
wire   [0:0] icmp_ln46_14_fu_808_p2;
wire   [0:0] or_ln46_21_fu_822_p2;
wire   [0:0] tmp_42_fu_796_p3;
wire   [0:0] and_ln46_14_fu_828_p2;
wire   [1:0] trunc_ln46_7_fu_786_p4;
wire   [1:0] zext_ln46_7_fu_834_p1;
wire   [5:0] tmp_45_fu_844_p4;
wire   [6:0] trunc_ln46_26_fu_886_p1;
wire   [0:0] tmp_50_fu_896_p3;
wire   [0:0] icmp_ln46_16_fu_890_p2;
wire   [0:0] or_ln46_24_fu_904_p2;
wire   [0:0] tmp_48_fu_878_p3;
wire   [0:0] and_ln46_16_fu_910_p2;
wire   [1:0] trunc_ln46_8_fu_868_p4;
wire   [1:0] zext_ln46_8_fu_916_p1;
wire   [5:0] tmp_51_fu_926_p4;
wire   [6:0] trunc_ln46_27_fu_968_p1;
wire   [0:0] tmp_56_fu_978_p3;
wire   [0:0] icmp_ln46_18_fu_972_p2;
wire   [0:0] or_ln46_27_fu_986_p2;
wire   [0:0] tmp_54_fu_960_p3;
wire   [0:0] and_ln46_18_fu_992_p2;
wire   [1:0] trunc_ln46_9_fu_950_p4;
wire   [1:0] zext_ln46_9_fu_998_p1;
wire   [5:0] tmp_57_fu_1008_p4;
wire   [6:0] trunc_ln46_28_fu_1050_p1;
wire   [0:0] tmp_62_fu_1060_p3;
wire   [0:0] icmp_ln46_20_fu_1054_p2;
wire   [0:0] or_ln46_30_fu_1068_p2;
wire   [0:0] tmp_60_fu_1042_p3;
wire   [0:0] and_ln46_20_fu_1074_p2;
wire   [1:0] trunc_ln46_s_fu_1032_p4;
wire   [1:0] zext_ln46_10_fu_1080_p1;
wire   [5:0] tmp_63_fu_1090_p4;
wire   [6:0] trunc_ln46_29_fu_1132_p1;
wire   [0:0] tmp_68_fu_1142_p3;
wire   [0:0] icmp_ln46_22_fu_1136_p2;
wire   [0:0] or_ln46_33_fu_1150_p2;
wire   [0:0] tmp_66_fu_1124_p3;
wire   [0:0] and_ln46_22_fu_1156_p2;
wire   [1:0] trunc_ln46_10_fu_1114_p4;
wire   [1:0] zext_ln46_11_fu_1162_p1;
wire   [5:0] tmp_69_fu_1172_p4;
wire   [6:0] trunc_ln46_30_fu_1214_p1;
wire   [0:0] tmp_74_fu_1224_p3;
wire   [0:0] icmp_ln46_24_fu_1218_p2;
wire   [0:0] or_ln46_36_fu_1232_p2;
wire   [0:0] tmp_72_fu_1206_p3;
wire   [0:0] and_ln46_24_fu_1238_p2;
wire   [1:0] trunc_ln46_11_fu_1196_p4;
wire   [1:0] zext_ln46_12_fu_1244_p1;
wire   [5:0] tmp_75_fu_1254_p4;
wire   [6:0] trunc_ln46_31_fu_1296_p1;
wire   [0:0] tmp_80_fu_1306_p3;
wire   [0:0] icmp_ln46_26_fu_1300_p2;
wire   [0:0] or_ln46_39_fu_1314_p2;
wire   [0:0] tmp_78_fu_1288_p3;
wire   [0:0] and_ln46_26_fu_1320_p2;
wire   [1:0] trunc_ln46_12_fu_1278_p4;
wire   [1:0] zext_ln46_13_fu_1326_p1;
wire   [5:0] tmp_81_fu_1336_p4;
wire   [6:0] trunc_ln46_32_fu_1378_p1;
wire   [0:0] tmp_86_fu_1388_p3;
wire   [0:0] icmp_ln46_28_fu_1382_p2;
wire   [0:0] or_ln46_42_fu_1396_p2;
wire   [0:0] tmp_84_fu_1370_p3;
wire   [0:0] and_ln46_28_fu_1402_p2;
wire   [1:0] trunc_ln46_13_fu_1360_p4;
wire   [1:0] zext_ln46_14_fu_1408_p1;
wire   [5:0] tmp_87_fu_1418_p4;
wire   [6:0] trunc_ln46_33_fu_1460_p1;
wire   [0:0] tmp_92_fu_1470_p3;
wire   [0:0] icmp_ln46_30_fu_1464_p2;
wire   [0:0] or_ln46_45_fu_1478_p2;
wire   [0:0] tmp_90_fu_1452_p3;
wire   [0:0] and_ln46_30_fu_1484_p2;
wire   [1:0] trunc_ln46_14_fu_1442_p4;
wire   [1:0] zext_ln46_15_fu_1490_p1;
wire   [5:0] tmp_93_fu_1500_p4;
wire   [6:0] trunc_ln46_34_fu_1542_p1;
wire   [0:0] tmp_98_fu_1552_p3;
wire   [0:0] icmp_ln46_32_fu_1546_p2;
wire   [0:0] or_ln46_48_fu_1560_p2;
wire   [0:0] tmp_96_fu_1534_p3;
wire   [0:0] and_ln46_32_fu_1566_p2;
wire   [1:0] trunc_ln46_15_fu_1524_p4;
wire   [1:0] zext_ln46_16_fu_1572_p1;
wire   [5:0] tmp_99_fu_1582_p4;
wire   [6:0] trunc_ln46_35_fu_1624_p1;
wire   [0:0] tmp_104_fu_1634_p3;
wire   [0:0] icmp_ln46_34_fu_1628_p2;
wire   [0:0] or_ln46_51_fu_1642_p2;
wire   [0:0] tmp_102_fu_1616_p3;
wire   [0:0] and_ln46_34_fu_1648_p2;
wire   [1:0] trunc_ln46_16_fu_1606_p4;
wire   [1:0] zext_ln46_17_fu_1654_p1;
wire   [5:0] tmp_105_fu_1664_p4;
wire   [6:0] trunc_ln46_36_fu_1706_p1;
wire   [0:0] tmp_110_fu_1716_p3;
wire   [0:0] icmp_ln46_36_fu_1710_p2;
wire   [0:0] or_ln46_54_fu_1724_p2;
wire   [0:0] tmp_108_fu_1698_p3;
wire   [0:0] and_ln46_36_fu_1730_p2;
wire   [1:0] trunc_ln46_17_fu_1688_p4;
wire   [1:0] zext_ln46_18_fu_1736_p1;
wire   [5:0] tmp_111_fu_1746_p4;
wire   [6:0] trunc_ln46_37_fu_1788_p1;
wire   [0:0] tmp_116_fu_1798_p3;
wire   [0:0] icmp_ln46_38_fu_1792_p2;
wire   [0:0] or_ln46_57_fu_1806_p2;
wire   [0:0] tmp_114_fu_1780_p3;
wire   [0:0] and_ln46_38_fu_1812_p2;
wire   [1:0] trunc_ln46_18_fu_1770_p4;
wire   [1:0] zext_ln46_19_fu_1818_p1;
wire   [5:0] tmp_117_fu_1828_p4;
wire   [0:0] tmp_2_fu_1849_p3;
wire   [0:0] tmp_4_fu_1856_p3;
wire   [0:0] not_tmp_3_fu_1863_p2;
wire   [0:0] and_ln46_1_fu_1869_p2;
wire   [0:0] empty_fu_1875_p2;
wire   [0:0] xor_ln46_fu_1885_p2;
wire   [0:0] or_ln46_1_fu_1880_p2;
wire   [1:0] select_ln46_fu_1896_p3;
wire   [0:0] or_ln46_2_fu_1891_p2;
wire   [1:0] select_ln46_1_fu_1902_p3;
wire   [0:0] icmp_ln45_fu_1844_p2;
wire   [1:0] select_ln46_2_fu_1910_p3;
wire   [0:0] tmp_7_fu_1930_p3;
wire   [0:0] tmp_10_fu_1937_p3;
wire   [0:0] not_tmp_s_fu_1944_p2;
wire   [0:0] and_ln46_3_fu_1950_p2;
wire   [0:0] empty_11_fu_1956_p2;
wire   [0:0] xor_ln46_1_fu_1966_p2;
wire   [0:0] or_ln46_4_fu_1961_p2;
wire   [1:0] select_ln46_3_fu_1977_p3;
wire   [0:0] or_ln46_5_fu_1972_p2;
wire   [1:0] select_ln46_4_fu_1983_p3;
wire   [0:0] icmp_ln45_1_fu_1925_p2;
wire   [1:0] select_ln46_5_fu_1991_p3;
wire   [0:0] tmp_13_fu_2011_p3;
wire   [0:0] tmp_16_fu_2018_p3;
wire   [0:0] not_tmp_16_fu_2025_p2;
wire   [0:0] and_ln46_5_fu_2031_p2;
wire   [0:0] empty_12_fu_2037_p2;
wire   [0:0] xor_ln46_2_fu_2047_p2;
wire   [0:0] or_ln46_7_fu_2042_p2;
wire   [1:0] select_ln46_6_fu_2058_p3;
wire   [0:0] or_ln46_8_fu_2053_p2;
wire   [1:0] select_ln46_7_fu_2064_p3;
wire   [0:0] icmp_ln45_2_fu_2006_p2;
wire   [1:0] select_ln46_8_fu_2072_p3;
wire   [0:0] tmp_19_fu_2092_p3;
wire   [0:0] tmp_22_fu_2099_p3;
wire   [0:0] not_tmp_23_fu_2106_p2;
wire   [0:0] and_ln46_7_fu_2112_p2;
wire   [0:0] empty_13_fu_2118_p2;
wire   [0:0] xor_ln46_3_fu_2128_p2;
wire   [0:0] or_ln46_10_fu_2123_p2;
wire   [1:0] select_ln46_9_fu_2139_p3;
wire   [0:0] or_ln46_11_fu_2134_p2;
wire   [1:0] select_ln46_10_fu_2145_p3;
wire   [0:0] icmp_ln45_3_fu_2087_p2;
wire   [1:0] select_ln46_11_fu_2153_p3;
wire   [0:0] tmp_25_fu_2173_p3;
wire   [0:0] tmp_28_fu_2180_p3;
wire   [0:0] not_tmp_30_fu_2187_p2;
wire   [0:0] and_ln46_9_fu_2193_p2;
wire   [0:0] empty_14_fu_2199_p2;
wire   [0:0] xor_ln46_4_fu_2209_p2;
wire   [0:0] or_ln46_13_fu_2204_p2;
wire   [1:0] select_ln46_12_fu_2220_p3;
wire   [0:0] or_ln46_14_fu_2215_p2;
wire   [1:0] select_ln46_13_fu_2226_p3;
wire   [0:0] icmp_ln45_4_fu_2168_p2;
wire   [1:0] select_ln46_14_fu_2234_p3;
wire   [0:0] tmp_31_fu_2254_p3;
wire   [0:0] tmp_34_fu_2261_p3;
wire   [0:0] not_tmp_37_fu_2268_p2;
wire   [0:0] and_ln46_11_fu_2274_p2;
wire   [0:0] empty_15_fu_2280_p2;
wire   [0:0] xor_ln46_5_fu_2290_p2;
wire   [0:0] or_ln46_16_fu_2285_p2;
wire   [1:0] select_ln46_15_fu_2301_p3;
wire   [0:0] or_ln46_17_fu_2296_p2;
wire   [1:0] select_ln46_16_fu_2307_p3;
wire   [0:0] icmp_ln45_5_fu_2249_p2;
wire   [1:0] select_ln46_17_fu_2315_p3;
wire   [0:0] tmp_37_fu_2335_p3;
wire   [0:0] tmp_40_fu_2342_p3;
wire   [0:0] not_tmp_44_fu_2349_p2;
wire   [0:0] and_ln46_13_fu_2355_p2;
wire   [0:0] empty_16_fu_2361_p2;
wire   [0:0] xor_ln46_6_fu_2371_p2;
wire   [0:0] or_ln46_19_fu_2366_p2;
wire   [1:0] select_ln46_18_fu_2382_p3;
wire   [0:0] or_ln46_20_fu_2377_p2;
wire   [1:0] select_ln46_19_fu_2388_p3;
wire   [0:0] icmp_ln45_6_fu_2330_p2;
wire   [1:0] select_ln46_20_fu_2396_p3;
wire   [0:0] tmp_43_fu_2416_p3;
wire   [0:0] tmp_46_fu_2423_p3;
wire   [0:0] not_tmp_51_fu_2430_p2;
wire   [0:0] and_ln46_15_fu_2436_p2;
wire   [0:0] empty_17_fu_2442_p2;
wire   [0:0] xor_ln46_7_fu_2452_p2;
wire   [0:0] or_ln46_22_fu_2447_p2;
wire   [1:0] select_ln46_21_fu_2463_p3;
wire   [0:0] or_ln46_23_fu_2458_p2;
wire   [1:0] select_ln46_22_fu_2469_p3;
wire   [0:0] icmp_ln45_7_fu_2411_p2;
wire   [1:0] select_ln46_23_fu_2477_p3;
wire   [0:0] tmp_49_fu_2497_p3;
wire   [0:0] tmp_52_fu_2504_p3;
wire   [0:0] not_tmp_58_fu_2511_p2;
wire   [0:0] and_ln46_17_fu_2517_p2;
wire   [0:0] empty_18_fu_2523_p2;
wire   [0:0] xor_ln46_8_fu_2533_p2;
wire   [0:0] or_ln46_25_fu_2528_p2;
wire   [1:0] select_ln46_24_fu_2544_p3;
wire   [0:0] or_ln46_26_fu_2539_p2;
wire   [1:0] select_ln46_25_fu_2550_p3;
wire   [0:0] icmp_ln45_8_fu_2492_p2;
wire   [1:0] select_ln46_26_fu_2558_p3;
wire   [0:0] tmp_55_fu_2578_p3;
wire   [0:0] tmp_58_fu_2585_p3;
wire   [0:0] not_tmp_65_fu_2592_p2;
wire   [0:0] and_ln46_19_fu_2598_p2;
wire   [0:0] empty_19_fu_2604_p2;
wire   [0:0] xor_ln46_9_fu_2614_p2;
wire   [0:0] or_ln46_28_fu_2609_p2;
wire   [1:0] select_ln46_27_fu_2625_p3;
wire   [0:0] or_ln46_29_fu_2620_p2;
wire   [1:0] select_ln46_28_fu_2631_p3;
wire   [0:0] icmp_ln45_9_fu_2573_p2;
wire   [1:0] select_ln46_29_fu_2639_p3;
wire   [0:0] tmp_61_fu_2659_p3;
wire   [0:0] tmp_64_fu_2666_p3;
wire   [0:0] not_tmp_72_fu_2673_p2;
wire   [0:0] and_ln46_21_fu_2679_p2;
wire   [0:0] empty_20_fu_2685_p2;
wire   [0:0] xor_ln46_10_fu_2695_p2;
wire   [0:0] or_ln46_31_fu_2690_p2;
wire   [1:0] select_ln46_30_fu_2706_p3;
wire   [0:0] or_ln46_32_fu_2701_p2;
wire   [1:0] select_ln46_31_fu_2712_p3;
wire   [0:0] icmp_ln45_10_fu_2654_p2;
wire   [1:0] select_ln46_32_fu_2720_p3;
wire   [0:0] tmp_67_fu_2740_p3;
wire   [0:0] tmp_70_fu_2747_p3;
wire   [0:0] not_tmp_79_fu_2754_p2;
wire   [0:0] and_ln46_23_fu_2760_p2;
wire   [0:0] empty_21_fu_2766_p2;
wire   [0:0] xor_ln46_11_fu_2776_p2;
wire   [0:0] or_ln46_34_fu_2771_p2;
wire   [1:0] select_ln46_33_fu_2787_p3;
wire   [0:0] or_ln46_35_fu_2782_p2;
wire   [1:0] select_ln46_34_fu_2793_p3;
wire   [0:0] icmp_ln45_11_fu_2735_p2;
wire   [1:0] select_ln46_35_fu_2801_p3;
wire   [0:0] tmp_73_fu_2821_p3;
wire   [0:0] tmp_76_fu_2828_p3;
wire   [0:0] not_tmp_86_fu_2835_p2;
wire   [0:0] and_ln46_25_fu_2841_p2;
wire   [0:0] empty_22_fu_2847_p2;
wire   [0:0] xor_ln46_12_fu_2857_p2;
wire   [0:0] or_ln46_37_fu_2852_p2;
wire   [1:0] select_ln46_36_fu_2868_p3;
wire   [0:0] or_ln46_38_fu_2863_p2;
wire   [1:0] select_ln46_37_fu_2874_p3;
wire   [0:0] icmp_ln45_12_fu_2816_p2;
wire   [1:0] select_ln46_38_fu_2882_p3;
wire   [0:0] tmp_79_fu_2902_p3;
wire   [0:0] tmp_82_fu_2909_p3;
wire   [0:0] not_tmp_93_fu_2916_p2;
wire   [0:0] and_ln46_27_fu_2922_p2;
wire   [0:0] empty_23_fu_2928_p2;
wire   [0:0] xor_ln46_13_fu_2938_p2;
wire   [0:0] or_ln46_40_fu_2933_p2;
wire   [1:0] select_ln46_39_fu_2949_p3;
wire   [0:0] or_ln46_41_fu_2944_p2;
wire   [1:0] select_ln46_40_fu_2955_p3;
wire   [0:0] icmp_ln45_13_fu_2897_p2;
wire   [1:0] select_ln46_41_fu_2963_p3;
wire   [0:0] tmp_85_fu_2983_p3;
wire   [0:0] tmp_88_fu_2990_p3;
wire   [0:0] not_tmp_100_fu_2997_p2;
wire   [0:0] and_ln46_29_fu_3003_p2;
wire   [0:0] empty_24_fu_3009_p2;
wire   [0:0] xor_ln46_14_fu_3019_p2;
wire   [0:0] or_ln46_43_fu_3014_p2;
wire   [1:0] select_ln46_42_fu_3030_p3;
wire   [0:0] or_ln46_44_fu_3025_p2;
wire   [1:0] select_ln46_43_fu_3036_p3;
wire   [0:0] icmp_ln45_14_fu_2978_p2;
wire   [1:0] select_ln46_44_fu_3044_p3;
wire   [0:0] tmp_91_fu_3064_p3;
wire   [0:0] tmp_94_fu_3071_p3;
wire   [0:0] not_tmp_107_fu_3078_p2;
wire   [0:0] and_ln46_31_fu_3084_p2;
wire   [0:0] empty_25_fu_3090_p2;
wire   [0:0] xor_ln46_15_fu_3100_p2;
wire   [0:0] or_ln46_46_fu_3095_p2;
wire   [1:0] select_ln46_45_fu_3111_p3;
wire   [0:0] or_ln46_47_fu_3106_p2;
wire   [1:0] select_ln46_46_fu_3117_p3;
wire   [0:0] icmp_ln45_15_fu_3059_p2;
wire   [1:0] select_ln46_47_fu_3125_p3;
wire   [0:0] tmp_97_fu_3145_p3;
wire   [0:0] tmp_100_fu_3152_p3;
wire   [0:0] not_tmp_114_fu_3159_p2;
wire   [0:0] and_ln46_33_fu_3165_p2;
wire   [0:0] empty_26_fu_3171_p2;
wire   [0:0] xor_ln46_16_fu_3181_p2;
wire   [0:0] or_ln46_49_fu_3176_p2;
wire   [1:0] select_ln46_48_fu_3192_p3;
wire   [0:0] or_ln46_50_fu_3187_p2;
wire   [1:0] select_ln46_49_fu_3198_p3;
wire   [0:0] icmp_ln45_16_fu_3140_p2;
wire   [1:0] select_ln46_50_fu_3206_p3;
wire   [0:0] tmp_103_fu_3226_p3;
wire   [0:0] tmp_106_fu_3233_p3;
wire   [0:0] not_tmp_121_fu_3240_p2;
wire   [0:0] and_ln46_35_fu_3246_p2;
wire   [0:0] empty_27_fu_3252_p2;
wire   [0:0] xor_ln46_17_fu_3262_p2;
wire   [0:0] or_ln46_52_fu_3257_p2;
wire   [1:0] select_ln46_51_fu_3273_p3;
wire   [0:0] or_ln46_53_fu_3268_p2;
wire   [1:0] select_ln46_52_fu_3279_p3;
wire   [0:0] icmp_ln45_17_fu_3221_p2;
wire   [1:0] select_ln46_53_fu_3287_p3;
wire   [0:0] tmp_109_fu_3307_p3;
wire   [0:0] tmp_112_fu_3314_p3;
wire   [0:0] not_tmp_128_fu_3321_p2;
wire   [0:0] and_ln46_37_fu_3327_p2;
wire   [0:0] empty_28_fu_3333_p2;
wire   [0:0] xor_ln46_18_fu_3343_p2;
wire   [0:0] or_ln46_55_fu_3338_p2;
wire   [1:0] select_ln46_54_fu_3354_p3;
wire   [0:0] or_ln46_56_fu_3349_p2;
wire   [1:0] select_ln46_55_fu_3360_p3;
wire   [0:0] icmp_ln45_18_fu_3302_p2;
wire   [1:0] select_ln46_56_fu_3368_p3;
wire   [0:0] tmp_115_fu_3388_p3;
wire   [0:0] tmp_118_fu_3395_p3;
wire   [0:0] not_tmp_135_fu_3402_p2;
wire   [0:0] and_ln46_39_fu_3408_p2;
wire   [0:0] empty_29_fu_3414_p2;
wire   [0:0] xor_ln46_19_fu_3424_p2;
wire   [0:0] or_ln46_58_fu_3419_p2;
wire   [1:0] select_ln46_57_fu_3435_p3;
wire   [0:0] or_ln46_59_fu_3430_p2;
wire   [1:0] select_ln46_58_fu_3441_p3;
wire   [0:0] icmp_ln45_19_fu_3383_p2;
wire   [1:0] select_ln46_59_fu_3449_p3;
wire   [1:0] res_0_0_fu_1917_p3;
wire   [1:0] res_1_0_fu_1998_p3;
wire   [1:0] res_2_0_fu_2079_p3;
wire   [1:0] res_3_0_fu_2160_p3;
wire   [1:0] res_4_0_fu_2241_p3;
wire   [1:0] res_5_0_fu_2322_p3;
wire   [1:0] res_6_0_fu_2403_p3;
wire   [1:0] res_7_0_fu_2484_p3;
wire   [1:0] res_8_0_fu_2565_p3;
wire   [1:0] res_9_0_fu_2646_p3;
wire   [1:0] res_10_0_fu_2727_p3;
wire   [1:0] res_11_0_fu_2808_p3;
wire   [1:0] res_12_0_fu_2889_p3;
wire   [1:0] res_13_0_fu_2970_p3;
wire   [1:0] res_1445_0_fu_3051_p3;
wire   [1:0] res_15_0_fu_3132_p3;
wire   [1:0] res_16_0_fu_3213_p3;
wire   [1:0] res_17_0_fu_3294_p3;
wire   [1:0] res_18_0_fu_3375_p3;
wire   [1:0] res_19_0_fu_3456_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln46_10_reg_3901 <= add_ln46_10_fu_1084_p2;
        add_ln46_11_reg_3920 <= add_ln46_11_fu_1166_p2;
        add_ln46_12_reg_3939 <= add_ln46_12_fu_1248_p2;
        add_ln46_13_reg_3958 <= add_ln46_13_fu_1330_p2;
        add_ln46_14_reg_3977 <= add_ln46_14_fu_1412_p2;
        add_ln46_15_reg_3996 <= add_ln46_15_fu_1494_p2;
        add_ln46_16_reg_4015 <= add_ln46_16_fu_1576_p2;
        add_ln46_17_reg_4034 <= add_ln46_17_fu_1658_p2;
        add_ln46_18_reg_4053 <= add_ln46_18_fu_1740_p2;
        add_ln46_19_reg_4072 <= add_ln46_19_fu_1822_p2;
        add_ln46_1_reg_3730 <= add_ln46_1_fu_346_p2;
        add_ln46_2_reg_3749 <= add_ln46_2_fu_428_p2;
        add_ln46_3_reg_3768 <= add_ln46_3_fu_510_p2;
        add_ln46_4_reg_3787 <= add_ln46_4_fu_592_p2;
        add_ln46_5_reg_3806 <= add_ln46_5_fu_674_p2;
        add_ln46_6_reg_3825 <= add_ln46_6_fu_756_p2;
        add_ln46_7_reg_3844 <= add_ln46_7_fu_838_p2;
        add_ln46_8_reg_3863 <= add_ln46_8_fu_920_p2;
        add_ln46_9_reg_3882 <= add_ln46_9_fu_1002_p2;
        add_ln46_reg_3711 <= add_ln46_fu_264_p2;
        data_0_val_read_reg_3698 <= data_0_val;
        data_10_val_read_reg_3638 <= data_10_val;
        data_11_val_read_reg_3632 <= data_11_val;
        data_12_val_read_reg_3626 <= data_12_val;
        data_13_val_read_reg_3620 <= data_13_val;
        data_14_val_read_reg_3614 <= data_14_val;
        data_15_val_read_reg_3608 <= data_15_val;
        data_16_val_read_reg_3602 <= data_16_val;
        data_17_val_read_reg_3596 <= data_17_val;
        data_18_val_read_reg_3590 <= data_18_val;
        data_19_val_read_reg_3584 <= data_19_val;
        data_1_val_read_reg_3692 <= data_1_val;
        data_2_val_read_reg_3686 <= data_2_val;
        data_3_val_read_reg_3680 <= data_3_val;
        data_4_val_read_reg_3674 <= data_4_val;
        data_5_val_read_reg_3668 <= data_5_val;
        data_6_val_read_reg_3662 <= data_6_val;
        data_7_val_read_reg_3656 <= data_7_val;
        data_8_val_read_reg_3650 <= data_8_val;
        data_9_val_read_reg_3644 <= data_9_val;
        icmp_ln46_11_reg_3813 <= icmp_ln46_11_fu_690_p2;
        icmp_ln46_13_reg_3832 <= icmp_ln46_13_fu_772_p2;
        icmp_ln46_15_reg_3851 <= icmp_ln46_15_fu_854_p2;
        icmp_ln46_17_reg_3870 <= icmp_ln46_17_fu_936_p2;
        icmp_ln46_19_reg_3889 <= icmp_ln46_19_fu_1018_p2;
        icmp_ln46_1_reg_3718 <= icmp_ln46_1_fu_280_p2;
        icmp_ln46_21_reg_3908 <= icmp_ln46_21_fu_1100_p2;
        icmp_ln46_23_reg_3927 <= icmp_ln46_23_fu_1182_p2;
        icmp_ln46_25_reg_3946 <= icmp_ln46_25_fu_1264_p2;
        icmp_ln46_27_reg_3965 <= icmp_ln46_27_fu_1346_p2;
        icmp_ln46_29_reg_3984 <= icmp_ln46_29_fu_1428_p2;
        icmp_ln46_31_reg_4003 <= icmp_ln46_31_fu_1510_p2;
        icmp_ln46_33_reg_4022 <= icmp_ln46_33_fu_1592_p2;
        icmp_ln46_35_reg_4041 <= icmp_ln46_35_fu_1674_p2;
        icmp_ln46_37_reg_4060 <= icmp_ln46_37_fu_1756_p2;
        icmp_ln46_39_reg_4079 <= icmp_ln46_39_fu_1838_p2;
        icmp_ln46_3_reg_3737 <= icmp_ln46_3_fu_362_p2;
        icmp_ln46_5_reg_3756 <= icmp_ln46_5_fu_444_p2;
        icmp_ln46_7_reg_3775 <= icmp_ln46_7_fu_526_p2;
        icmp_ln46_9_reg_3794 <= icmp_ln46_9_fu_608_p2;
        tmp_101_reg_4027 <= data_17_val[32'd15];
        tmp_107_reg_4046 <= data_18_val[32'd15];
        tmp_113_reg_4065 <= data_19_val[32'd15];
        tmp_11_reg_3742 <= data_2_val[32'd15];
        tmp_17_reg_3761 <= data_3_val[32'd15];
        tmp_23_reg_3780 <= data_4_val[32'd15];
        tmp_29_reg_3799 <= data_5_val[32'd15];
        tmp_35_reg_3818 <= data_6_val[32'd15];
        tmp_41_reg_3837 <= data_7_val[32'd15];
        tmp_47_reg_3856 <= data_8_val[32'd15];
        tmp_53_reg_3875 <= data_9_val[32'd15];
        tmp_59_reg_3894 <= data_10_val[32'd15];
        tmp_5_reg_3723 <= data_1_val[32'd15];
        tmp_65_reg_3913 <= data_11_val[32'd15];
        tmp_71_reg_3932 <= data_12_val[32'd15];
        tmp_77_reg_3951 <= data_13_val[32'd15];
        tmp_83_reg_3970 <= data_14_val[32'd15];
        tmp_89_reg_3989 <= data_15_val[32'd15];
        tmp_95_reg_4008 <= data_16_val[32'd15];
        tmp_reg_3704 <= data_0_val[32'd15];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln46_10_fu_1084_p2 = (trunc_ln46_s_fu_1032_p4 + zext_ln46_10_fu_1080_p1);

assign add_ln46_11_fu_1166_p2 = (trunc_ln46_10_fu_1114_p4 + zext_ln46_11_fu_1162_p1);

assign add_ln46_12_fu_1248_p2 = (trunc_ln46_11_fu_1196_p4 + zext_ln46_12_fu_1244_p1);

assign add_ln46_13_fu_1330_p2 = (trunc_ln46_12_fu_1278_p4 + zext_ln46_13_fu_1326_p1);

assign add_ln46_14_fu_1412_p2 = (trunc_ln46_13_fu_1360_p4 + zext_ln46_14_fu_1408_p1);

assign add_ln46_15_fu_1494_p2 = (trunc_ln46_14_fu_1442_p4 + zext_ln46_15_fu_1490_p1);

assign add_ln46_16_fu_1576_p2 = (trunc_ln46_15_fu_1524_p4 + zext_ln46_16_fu_1572_p1);

assign add_ln46_17_fu_1658_p2 = (trunc_ln46_16_fu_1606_p4 + zext_ln46_17_fu_1654_p1);

assign add_ln46_18_fu_1740_p2 = (trunc_ln46_17_fu_1688_p4 + zext_ln46_18_fu_1736_p1);

assign add_ln46_19_fu_1822_p2 = (trunc_ln46_18_fu_1770_p4 + zext_ln46_19_fu_1818_p1);

assign add_ln46_1_fu_346_p2 = (trunc_ln46_1_fu_294_p4 + zext_ln46_1_fu_342_p1);

assign add_ln46_2_fu_428_p2 = (trunc_ln46_2_fu_376_p4 + zext_ln46_2_fu_424_p1);

assign add_ln46_3_fu_510_p2 = (trunc_ln46_3_fu_458_p4 + zext_ln46_3_fu_506_p1);

assign add_ln46_4_fu_592_p2 = (trunc_ln46_4_fu_540_p4 + zext_ln46_4_fu_588_p1);

assign add_ln46_5_fu_674_p2 = (trunc_ln46_5_fu_622_p4 + zext_ln46_5_fu_670_p1);

assign add_ln46_6_fu_756_p2 = (trunc_ln46_6_fu_704_p4 + zext_ln46_6_fu_752_p1);

assign add_ln46_7_fu_838_p2 = (trunc_ln46_7_fu_786_p4 + zext_ln46_7_fu_834_p1);

assign add_ln46_8_fu_920_p2 = (trunc_ln46_8_fu_868_p4 + zext_ln46_8_fu_916_p1);

assign add_ln46_9_fu_1002_p2 = (trunc_ln46_9_fu_950_p4 + zext_ln46_9_fu_998_p1);

assign add_ln46_fu_264_p2 = (trunc_ln_fu_212_p4 + zext_ln46_fu_260_p1);

assign and_ln46_10_fu_664_p2 = (tmp_30_fu_632_p3 & or_ln46_15_fu_658_p2);

assign and_ln46_11_fu_2274_p2 = (tmp_34_fu_2261_p3 | not_tmp_37_fu_2268_p2);

assign and_ln46_12_fu_746_p2 = (tmp_36_fu_714_p3 & or_ln46_18_fu_740_p2);

assign and_ln46_13_fu_2355_p2 = (tmp_40_fu_2342_p3 | not_tmp_44_fu_2349_p2);

assign and_ln46_14_fu_828_p2 = (tmp_42_fu_796_p3 & or_ln46_21_fu_822_p2);

assign and_ln46_15_fu_2436_p2 = (tmp_46_fu_2423_p3 | not_tmp_51_fu_2430_p2);

assign and_ln46_16_fu_910_p2 = (tmp_48_fu_878_p3 & or_ln46_24_fu_904_p2);

assign and_ln46_17_fu_2517_p2 = (tmp_52_fu_2504_p3 | not_tmp_58_fu_2511_p2);

assign and_ln46_18_fu_992_p2 = (tmp_54_fu_960_p3 & or_ln46_27_fu_986_p2);

assign and_ln46_19_fu_2598_p2 = (tmp_58_fu_2585_p3 | not_tmp_65_fu_2592_p2);

assign and_ln46_1_fu_1869_p2 = (tmp_4_fu_1856_p3 | not_tmp_3_fu_1863_p2);

assign and_ln46_20_fu_1074_p2 = (tmp_60_fu_1042_p3 & or_ln46_30_fu_1068_p2);

assign and_ln46_21_fu_2679_p2 = (tmp_64_fu_2666_p3 | not_tmp_72_fu_2673_p2);

assign and_ln46_22_fu_1156_p2 = (tmp_66_fu_1124_p3 & or_ln46_33_fu_1150_p2);

assign and_ln46_23_fu_2760_p2 = (tmp_70_fu_2747_p3 | not_tmp_79_fu_2754_p2);

assign and_ln46_24_fu_1238_p2 = (tmp_72_fu_1206_p3 & or_ln46_36_fu_1232_p2);

assign and_ln46_25_fu_2841_p2 = (tmp_76_fu_2828_p3 | not_tmp_86_fu_2835_p2);

assign and_ln46_26_fu_1320_p2 = (tmp_78_fu_1288_p3 & or_ln46_39_fu_1314_p2);

assign and_ln46_27_fu_2922_p2 = (tmp_82_fu_2909_p3 | not_tmp_93_fu_2916_p2);

assign and_ln46_28_fu_1402_p2 = (tmp_84_fu_1370_p3 & or_ln46_42_fu_1396_p2);

assign and_ln46_29_fu_3003_p2 = (tmp_88_fu_2990_p3 | not_tmp_100_fu_2997_p2);

assign and_ln46_2_fu_336_p2 = (tmp_6_fu_304_p3 & or_ln46_3_fu_330_p2);

assign and_ln46_30_fu_1484_p2 = (tmp_90_fu_1452_p3 & or_ln46_45_fu_1478_p2);

assign and_ln46_31_fu_3084_p2 = (tmp_94_fu_3071_p3 | not_tmp_107_fu_3078_p2);

assign and_ln46_32_fu_1566_p2 = (tmp_96_fu_1534_p3 & or_ln46_48_fu_1560_p2);

assign and_ln46_33_fu_3165_p2 = (tmp_100_fu_3152_p3 | not_tmp_114_fu_3159_p2);

assign and_ln46_34_fu_1648_p2 = (tmp_102_fu_1616_p3 & or_ln46_51_fu_1642_p2);

assign and_ln46_35_fu_3246_p2 = (tmp_106_fu_3233_p3 | not_tmp_121_fu_3240_p2);

assign and_ln46_36_fu_1730_p2 = (tmp_108_fu_1698_p3 & or_ln46_54_fu_1724_p2);

assign and_ln46_37_fu_3327_p2 = (tmp_112_fu_3314_p3 | not_tmp_128_fu_3321_p2);

assign and_ln46_38_fu_1812_p2 = (tmp_114_fu_1780_p3 & or_ln46_57_fu_1806_p2);

assign and_ln46_39_fu_3408_p2 = (tmp_118_fu_3395_p3 | not_tmp_135_fu_3402_p2);

assign and_ln46_3_fu_1950_p2 = (tmp_10_fu_1937_p3 | not_tmp_s_fu_1944_p2);

assign and_ln46_4_fu_418_p2 = (tmp_12_fu_386_p3 & or_ln46_6_fu_412_p2);

assign and_ln46_5_fu_2031_p2 = (tmp_16_fu_2018_p3 | not_tmp_16_fu_2025_p2);

assign and_ln46_6_fu_500_p2 = (tmp_18_fu_468_p3 & or_ln46_9_fu_494_p2);

assign and_ln46_7_fu_2112_p2 = (tmp_22_fu_2099_p3 | not_tmp_23_fu_2106_p2);

assign and_ln46_8_fu_582_p2 = (tmp_24_fu_550_p3 & or_ln46_12_fu_576_p2);

assign and_ln46_9_fu_2193_p2 = (tmp_28_fu_2180_p3 | not_tmp_30_fu_2187_p2);

assign and_ln46_fu_254_p2 = (tmp_1_fu_222_p3 & or_ln46_fu_248_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = res_0_0_fu_1917_p3;

assign ap_return_1 = res_1_0_fu_1998_p3;

assign ap_return_10 = res_10_0_fu_2727_p3;

assign ap_return_11 = res_11_0_fu_2808_p3;

assign ap_return_12 = res_12_0_fu_2889_p3;

assign ap_return_13 = res_13_0_fu_2970_p3;

assign ap_return_14 = res_1445_0_fu_3051_p3;

assign ap_return_15 = res_15_0_fu_3132_p3;

assign ap_return_16 = res_16_0_fu_3213_p3;

assign ap_return_17 = res_17_0_fu_3294_p3;

assign ap_return_18 = res_18_0_fu_3375_p3;

assign ap_return_19 = res_19_0_fu_3456_p3;

assign ap_return_2 = res_2_0_fu_2079_p3;

assign ap_return_3 = res_3_0_fu_2160_p3;

assign ap_return_4 = res_4_0_fu_2241_p3;

assign ap_return_5 = res_5_0_fu_2322_p3;

assign ap_return_6 = res_6_0_fu_2403_p3;

assign ap_return_7 = res_7_0_fu_2484_p3;

assign ap_return_8 = res_8_0_fu_2565_p3;

assign ap_return_9 = res_9_0_fu_2646_p3;

assign empty_11_fu_1956_p2 = (icmp_ln46_3_reg_3737 & and_ln46_3_fu_1950_p2);

assign empty_12_fu_2037_p2 = (icmp_ln46_5_reg_3756 & and_ln46_5_fu_2031_p2);

assign empty_13_fu_2118_p2 = (icmp_ln46_7_reg_3775 & and_ln46_7_fu_2112_p2);

assign empty_14_fu_2199_p2 = (icmp_ln46_9_reg_3794 & and_ln46_9_fu_2193_p2);

assign empty_15_fu_2280_p2 = (icmp_ln46_11_reg_3813 & and_ln46_11_fu_2274_p2);

assign empty_16_fu_2361_p2 = (icmp_ln46_13_reg_3832 & and_ln46_13_fu_2355_p2);

assign empty_17_fu_2442_p2 = (icmp_ln46_15_reg_3851 & and_ln46_15_fu_2436_p2);

assign empty_18_fu_2523_p2 = (icmp_ln46_17_reg_3870 & and_ln46_17_fu_2517_p2);

assign empty_19_fu_2604_p2 = (icmp_ln46_19_reg_3889 & and_ln46_19_fu_2598_p2);

assign empty_20_fu_2685_p2 = (icmp_ln46_21_reg_3908 & and_ln46_21_fu_2679_p2);

assign empty_21_fu_2766_p2 = (icmp_ln46_23_reg_3927 & and_ln46_23_fu_2760_p2);

assign empty_22_fu_2847_p2 = (icmp_ln46_25_reg_3946 & and_ln46_25_fu_2841_p2);

assign empty_23_fu_2928_p2 = (icmp_ln46_27_reg_3965 & and_ln46_27_fu_2922_p2);

assign empty_24_fu_3009_p2 = (icmp_ln46_29_reg_3984 & and_ln46_29_fu_3003_p2);

assign empty_25_fu_3090_p2 = (icmp_ln46_31_reg_4003 & and_ln46_31_fu_3084_p2);

assign empty_26_fu_3171_p2 = (icmp_ln46_33_reg_4022 & and_ln46_33_fu_3165_p2);

assign empty_27_fu_3252_p2 = (icmp_ln46_35_reg_4041 & and_ln46_35_fu_3246_p2);

assign empty_28_fu_3333_p2 = (icmp_ln46_37_reg_4060 & and_ln46_37_fu_3327_p2);

assign empty_29_fu_3414_p2 = (icmp_ln46_39_reg_4079 & and_ln46_39_fu_3408_p2);

assign empty_fu_1875_p2 = (icmp_ln46_1_reg_3718 & and_ln46_1_fu_1869_p2);

assign icmp_ln45_10_fu_2654_p2 = (($signed(data_10_val_read_reg_3638) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_2735_p2 = (($signed(data_11_val_read_reg_3632) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_2816_p2 = (($signed(data_12_val_read_reg_3626) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_2897_p2 = (($signed(data_13_val_read_reg_3620) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_2978_p2 = (($signed(data_14_val_read_reg_3614) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_3059_p2 = (($signed(data_15_val_read_reg_3608) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_16_fu_3140_p2 = (($signed(data_16_val_read_reg_3602) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_17_fu_3221_p2 = (($signed(data_17_val_read_reg_3596) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_18_fu_3302_p2 = (($signed(data_18_val_read_reg_3590) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_19_fu_3383_p2 = (($signed(data_19_val_read_reg_3584) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_1925_p2 = (($signed(data_1_val_read_reg_3692) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_2006_p2 = (($signed(data_2_val_read_reg_3686) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_2087_p2 = (($signed(data_3_val_read_reg_3680) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_2168_p2 = (($signed(data_4_val_read_reg_3674) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_2249_p2 = (($signed(data_5_val_read_reg_3668) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_2330_p2 = (($signed(data_6_val_read_reg_3662) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_2411_p2 = (($signed(data_7_val_read_reg_3656) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_2492_p2 = (($signed(data_8_val_read_reg_3650) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_2573_p2 = (($signed(data_9_val_read_reg_3644) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_1844_p2 = (($signed(data_0_val_read_reg_3698) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln46_10_fu_644_p2 = ((trunc_ln46_23_fu_640_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_11_fu_690_p2 = ((tmp_33_fu_680_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_12_fu_726_p2 = ((trunc_ln46_24_fu_722_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_13_fu_772_p2 = ((tmp_39_fu_762_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_14_fu_808_p2 = ((trunc_ln46_25_fu_804_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_15_fu_854_p2 = ((tmp_45_fu_844_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_16_fu_890_p2 = ((trunc_ln46_26_fu_886_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_17_fu_936_p2 = ((tmp_51_fu_926_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_18_fu_972_p2 = ((trunc_ln46_27_fu_968_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_19_fu_1018_p2 = ((tmp_57_fu_1008_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_1_fu_280_p2 = ((tmp_s_fu_270_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_20_fu_1054_p2 = ((trunc_ln46_28_fu_1050_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_21_fu_1100_p2 = ((tmp_63_fu_1090_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_22_fu_1136_p2 = ((trunc_ln46_29_fu_1132_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_23_fu_1182_p2 = ((tmp_69_fu_1172_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_24_fu_1218_p2 = ((trunc_ln46_30_fu_1214_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_25_fu_1264_p2 = ((tmp_75_fu_1254_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_26_fu_1300_p2 = ((trunc_ln46_31_fu_1296_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_27_fu_1346_p2 = ((tmp_81_fu_1336_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_28_fu_1382_p2 = ((trunc_ln46_32_fu_1378_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_29_fu_1428_p2 = ((tmp_87_fu_1418_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_2_fu_316_p2 = ((trunc_ln46_19_fu_312_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_30_fu_1464_p2 = ((trunc_ln46_33_fu_1460_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_31_fu_1510_p2 = ((tmp_93_fu_1500_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_32_fu_1546_p2 = ((trunc_ln46_34_fu_1542_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_33_fu_1592_p2 = ((tmp_99_fu_1582_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_34_fu_1628_p2 = ((trunc_ln46_35_fu_1624_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_35_fu_1674_p2 = ((tmp_105_fu_1664_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_36_fu_1710_p2 = ((trunc_ln46_36_fu_1706_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_37_fu_1756_p2 = ((tmp_111_fu_1746_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_38_fu_1792_p2 = ((trunc_ln46_37_fu_1788_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_39_fu_1838_p2 = ((tmp_117_fu_1828_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_3_fu_362_p2 = ((tmp_9_fu_352_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_4_fu_398_p2 = ((trunc_ln46_20_fu_394_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_5_fu_444_p2 = ((tmp_15_fu_434_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_6_fu_480_p2 = ((trunc_ln46_21_fu_476_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_7_fu_526_p2 = ((tmp_21_fu_516_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_8_fu_562_p2 = ((trunc_ln46_22_fu_558_p1 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_9_fu_608_p2 = ((tmp_27_fu_598_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_234_p2 = ((trunc_ln46_fu_230_p1 != 7'd0) ? 1'b1 : 1'b0);

assign not_tmp_100_fu_2997_p2 = (tmp_85_fu_2983_p3 ^ 1'd1);

assign not_tmp_107_fu_3078_p2 = (tmp_91_fu_3064_p3 ^ 1'd1);

assign not_tmp_114_fu_3159_p2 = (tmp_97_fu_3145_p3 ^ 1'd1);

assign not_tmp_121_fu_3240_p2 = (tmp_103_fu_3226_p3 ^ 1'd1);

assign not_tmp_128_fu_3321_p2 = (tmp_109_fu_3307_p3 ^ 1'd1);

assign not_tmp_135_fu_3402_p2 = (tmp_115_fu_3388_p3 ^ 1'd1);

assign not_tmp_16_fu_2025_p2 = (tmp_13_fu_2011_p3 ^ 1'd1);

assign not_tmp_23_fu_2106_p2 = (tmp_19_fu_2092_p3 ^ 1'd1);

assign not_tmp_30_fu_2187_p2 = (tmp_25_fu_2173_p3 ^ 1'd1);

assign not_tmp_37_fu_2268_p2 = (tmp_31_fu_2254_p3 ^ 1'd1);

assign not_tmp_3_fu_1863_p2 = (tmp_2_fu_1849_p3 ^ 1'd1);

assign not_tmp_44_fu_2349_p2 = (tmp_37_fu_2335_p3 ^ 1'd1);

assign not_tmp_51_fu_2430_p2 = (tmp_43_fu_2416_p3 ^ 1'd1);

assign not_tmp_58_fu_2511_p2 = (tmp_49_fu_2497_p3 ^ 1'd1);

assign not_tmp_65_fu_2592_p2 = (tmp_55_fu_2578_p3 ^ 1'd1);

assign not_tmp_72_fu_2673_p2 = (tmp_61_fu_2659_p3 ^ 1'd1);

assign not_tmp_79_fu_2754_p2 = (tmp_67_fu_2740_p3 ^ 1'd1);

assign not_tmp_86_fu_2835_p2 = (tmp_73_fu_2821_p3 ^ 1'd1);

assign not_tmp_93_fu_2916_p2 = (tmp_79_fu_2902_p3 ^ 1'd1);

assign not_tmp_s_fu_1944_p2 = (tmp_7_fu_1930_p3 ^ 1'd1);

assign or_ln46_10_fu_2123_p2 = (tmp_17_reg_3761 | empty_13_fu_2118_p2);

assign or_ln46_11_fu_2134_p2 = (xor_ln46_3_fu_2128_p2 | tmp_17_reg_3761);

assign or_ln46_12_fu_576_p2 = (tmp_26_fu_568_p3 | icmp_ln46_8_fu_562_p2);

assign or_ln46_13_fu_2204_p2 = (tmp_23_reg_3780 | empty_14_fu_2199_p2);

assign or_ln46_14_fu_2215_p2 = (xor_ln46_4_fu_2209_p2 | tmp_23_reg_3780);

assign or_ln46_15_fu_658_p2 = (tmp_32_fu_650_p3 | icmp_ln46_10_fu_644_p2);

assign or_ln46_16_fu_2285_p2 = (tmp_29_reg_3799 | empty_15_fu_2280_p2);

assign or_ln46_17_fu_2296_p2 = (xor_ln46_5_fu_2290_p2 | tmp_29_reg_3799);

assign or_ln46_18_fu_740_p2 = (tmp_38_fu_732_p3 | icmp_ln46_12_fu_726_p2);

assign or_ln46_19_fu_2366_p2 = (tmp_35_reg_3818 | empty_16_fu_2361_p2);

assign or_ln46_1_fu_1880_p2 = (tmp_reg_3704 | empty_fu_1875_p2);

assign or_ln46_20_fu_2377_p2 = (xor_ln46_6_fu_2371_p2 | tmp_35_reg_3818);

assign or_ln46_21_fu_822_p2 = (tmp_44_fu_814_p3 | icmp_ln46_14_fu_808_p2);

assign or_ln46_22_fu_2447_p2 = (tmp_41_reg_3837 | empty_17_fu_2442_p2);

assign or_ln46_23_fu_2458_p2 = (xor_ln46_7_fu_2452_p2 | tmp_41_reg_3837);

assign or_ln46_24_fu_904_p2 = (tmp_50_fu_896_p3 | icmp_ln46_16_fu_890_p2);

assign or_ln46_25_fu_2528_p2 = (tmp_47_reg_3856 | empty_18_fu_2523_p2);

assign or_ln46_26_fu_2539_p2 = (xor_ln46_8_fu_2533_p2 | tmp_47_reg_3856);

assign or_ln46_27_fu_986_p2 = (tmp_56_fu_978_p3 | icmp_ln46_18_fu_972_p2);

assign or_ln46_28_fu_2609_p2 = (tmp_53_reg_3875 | empty_19_fu_2604_p2);

assign or_ln46_29_fu_2620_p2 = (xor_ln46_9_fu_2614_p2 | tmp_53_reg_3875);

assign or_ln46_2_fu_1891_p2 = (xor_ln46_fu_1885_p2 | tmp_reg_3704);

assign or_ln46_30_fu_1068_p2 = (tmp_62_fu_1060_p3 | icmp_ln46_20_fu_1054_p2);

assign or_ln46_31_fu_2690_p2 = (tmp_59_reg_3894 | empty_20_fu_2685_p2);

assign or_ln46_32_fu_2701_p2 = (xor_ln46_10_fu_2695_p2 | tmp_59_reg_3894);

assign or_ln46_33_fu_1150_p2 = (tmp_68_fu_1142_p3 | icmp_ln46_22_fu_1136_p2);

assign or_ln46_34_fu_2771_p2 = (tmp_65_reg_3913 | empty_21_fu_2766_p2);

assign or_ln46_35_fu_2782_p2 = (xor_ln46_11_fu_2776_p2 | tmp_65_reg_3913);

assign or_ln46_36_fu_1232_p2 = (tmp_74_fu_1224_p3 | icmp_ln46_24_fu_1218_p2);

assign or_ln46_37_fu_2852_p2 = (tmp_71_reg_3932 | empty_22_fu_2847_p2);

assign or_ln46_38_fu_2863_p2 = (xor_ln46_12_fu_2857_p2 | tmp_71_reg_3932);

assign or_ln46_39_fu_1314_p2 = (tmp_80_fu_1306_p3 | icmp_ln46_26_fu_1300_p2);

assign or_ln46_3_fu_330_p2 = (tmp_8_fu_322_p3 | icmp_ln46_2_fu_316_p2);

assign or_ln46_40_fu_2933_p2 = (tmp_77_reg_3951 | empty_23_fu_2928_p2);

assign or_ln46_41_fu_2944_p2 = (xor_ln46_13_fu_2938_p2 | tmp_77_reg_3951);

assign or_ln46_42_fu_1396_p2 = (tmp_86_fu_1388_p3 | icmp_ln46_28_fu_1382_p2);

assign or_ln46_43_fu_3014_p2 = (tmp_83_reg_3970 | empty_24_fu_3009_p2);

assign or_ln46_44_fu_3025_p2 = (xor_ln46_14_fu_3019_p2 | tmp_83_reg_3970);

assign or_ln46_45_fu_1478_p2 = (tmp_92_fu_1470_p3 | icmp_ln46_30_fu_1464_p2);

assign or_ln46_46_fu_3095_p2 = (tmp_89_reg_3989 | empty_25_fu_3090_p2);

assign or_ln46_47_fu_3106_p2 = (xor_ln46_15_fu_3100_p2 | tmp_89_reg_3989);

assign or_ln46_48_fu_1560_p2 = (tmp_98_fu_1552_p3 | icmp_ln46_32_fu_1546_p2);

assign or_ln46_49_fu_3176_p2 = (tmp_95_reg_4008 | empty_26_fu_3171_p2);

assign or_ln46_4_fu_1961_p2 = (tmp_5_reg_3723 | empty_11_fu_1956_p2);

assign or_ln46_50_fu_3187_p2 = (xor_ln46_16_fu_3181_p2 | tmp_95_reg_4008);

assign or_ln46_51_fu_1642_p2 = (tmp_104_fu_1634_p3 | icmp_ln46_34_fu_1628_p2);

assign or_ln46_52_fu_3257_p2 = (tmp_101_reg_4027 | empty_27_fu_3252_p2);

assign or_ln46_53_fu_3268_p2 = (xor_ln46_17_fu_3262_p2 | tmp_101_reg_4027);

assign or_ln46_54_fu_1724_p2 = (tmp_110_fu_1716_p3 | icmp_ln46_36_fu_1710_p2);

assign or_ln46_55_fu_3338_p2 = (tmp_107_reg_4046 | empty_28_fu_3333_p2);

assign or_ln46_56_fu_3349_p2 = (xor_ln46_18_fu_3343_p2 | tmp_107_reg_4046);

assign or_ln46_57_fu_1806_p2 = (tmp_116_fu_1798_p3 | icmp_ln46_38_fu_1792_p2);

assign or_ln46_58_fu_3419_p2 = (tmp_113_reg_4065 | empty_29_fu_3414_p2);

assign or_ln46_59_fu_3430_p2 = (xor_ln46_19_fu_3424_p2 | tmp_113_reg_4065);

assign or_ln46_5_fu_1972_p2 = (xor_ln46_1_fu_1966_p2 | tmp_5_reg_3723);

assign or_ln46_6_fu_412_p2 = (tmp_14_fu_404_p3 | icmp_ln46_4_fu_398_p2);

assign or_ln46_7_fu_2042_p2 = (tmp_11_reg_3742 | empty_12_fu_2037_p2);

assign or_ln46_8_fu_2053_p2 = (xor_ln46_2_fu_2047_p2 | tmp_11_reg_3742);

assign or_ln46_9_fu_494_p2 = (tmp_20_fu_486_p3 | icmp_ln46_6_fu_480_p2);

assign or_ln46_fu_248_p2 = (tmp_3_fu_240_p3 | icmp_ln46_fu_234_p2);

assign res_0_0_fu_1917_p3 = ((icmp_ln45_fu_1844_p2[0:0] == 1'b1) ? select_ln46_2_fu_1910_p3 : 2'd0);

assign res_10_0_fu_2727_p3 = ((icmp_ln45_10_fu_2654_p2[0:0] == 1'b1) ? select_ln46_32_fu_2720_p3 : 2'd0);

assign res_11_0_fu_2808_p3 = ((icmp_ln45_11_fu_2735_p2[0:0] == 1'b1) ? select_ln46_35_fu_2801_p3 : 2'd0);

assign res_12_0_fu_2889_p3 = ((icmp_ln45_12_fu_2816_p2[0:0] == 1'b1) ? select_ln46_38_fu_2882_p3 : 2'd0);

assign res_13_0_fu_2970_p3 = ((icmp_ln45_13_fu_2897_p2[0:0] == 1'b1) ? select_ln46_41_fu_2963_p3 : 2'd0);

assign res_1445_0_fu_3051_p3 = ((icmp_ln45_14_fu_2978_p2[0:0] == 1'b1) ? select_ln46_44_fu_3044_p3 : 2'd0);

assign res_15_0_fu_3132_p3 = ((icmp_ln45_15_fu_3059_p2[0:0] == 1'b1) ? select_ln46_47_fu_3125_p3 : 2'd0);

assign res_16_0_fu_3213_p3 = ((icmp_ln45_16_fu_3140_p2[0:0] == 1'b1) ? select_ln46_50_fu_3206_p3 : 2'd0);

assign res_17_0_fu_3294_p3 = ((icmp_ln45_17_fu_3221_p2[0:0] == 1'b1) ? select_ln46_53_fu_3287_p3 : 2'd0);

assign res_18_0_fu_3375_p3 = ((icmp_ln45_18_fu_3302_p2[0:0] == 1'b1) ? select_ln46_56_fu_3368_p3 : 2'd0);

assign res_19_0_fu_3456_p3 = ((icmp_ln45_19_fu_3383_p2[0:0] == 1'b1) ? select_ln46_59_fu_3449_p3 : 2'd0);

assign res_1_0_fu_1998_p3 = ((icmp_ln45_1_fu_1925_p2[0:0] == 1'b1) ? select_ln46_5_fu_1991_p3 : 2'd0);

assign res_2_0_fu_2079_p3 = ((icmp_ln45_2_fu_2006_p2[0:0] == 1'b1) ? select_ln46_8_fu_2072_p3 : 2'd0);

assign res_3_0_fu_2160_p3 = ((icmp_ln45_3_fu_2087_p2[0:0] == 1'b1) ? select_ln46_11_fu_2153_p3 : 2'd0);

assign res_4_0_fu_2241_p3 = ((icmp_ln45_4_fu_2168_p2[0:0] == 1'b1) ? select_ln46_14_fu_2234_p3 : 2'd0);

assign res_5_0_fu_2322_p3 = ((icmp_ln45_5_fu_2249_p2[0:0] == 1'b1) ? select_ln46_17_fu_2315_p3 : 2'd0);

assign res_6_0_fu_2403_p3 = ((icmp_ln45_6_fu_2330_p2[0:0] == 1'b1) ? select_ln46_20_fu_2396_p3 : 2'd0);

assign res_7_0_fu_2484_p3 = ((icmp_ln45_7_fu_2411_p2[0:0] == 1'b1) ? select_ln46_23_fu_2477_p3 : 2'd0);

assign res_8_0_fu_2565_p3 = ((icmp_ln45_8_fu_2492_p2[0:0] == 1'b1) ? select_ln46_26_fu_2558_p3 : 2'd0);

assign res_9_0_fu_2646_p3 = ((icmp_ln45_9_fu_2573_p2[0:0] == 1'b1) ? select_ln46_29_fu_2639_p3 : 2'd0);

assign select_ln46_10_fu_2145_p3 = ((or_ln46_10_fu_2123_p2[0:0] == 1'b1) ? select_ln46_9_fu_2139_p3 : 2'd3);

assign select_ln46_11_fu_2153_p3 = ((or_ln46_11_fu_2134_p2[0:0] == 1'b1) ? select_ln46_10_fu_2145_p3 : add_ln46_3_reg_3768);

assign select_ln46_12_fu_2220_p3 = ((tmp_23_reg_3780[0:0] == 1'b1) ? 2'd0 : add_ln46_4_reg_3787);

assign select_ln46_13_fu_2226_p3 = ((or_ln46_13_fu_2204_p2[0:0] == 1'b1) ? select_ln46_12_fu_2220_p3 : 2'd3);

assign select_ln46_14_fu_2234_p3 = ((or_ln46_14_fu_2215_p2[0:0] == 1'b1) ? select_ln46_13_fu_2226_p3 : add_ln46_4_reg_3787);

assign select_ln46_15_fu_2301_p3 = ((tmp_29_reg_3799[0:0] == 1'b1) ? 2'd0 : add_ln46_5_reg_3806);

assign select_ln46_16_fu_2307_p3 = ((or_ln46_16_fu_2285_p2[0:0] == 1'b1) ? select_ln46_15_fu_2301_p3 : 2'd3);

assign select_ln46_17_fu_2315_p3 = ((or_ln46_17_fu_2296_p2[0:0] == 1'b1) ? select_ln46_16_fu_2307_p3 : add_ln46_5_reg_3806);

assign select_ln46_18_fu_2382_p3 = ((tmp_35_reg_3818[0:0] == 1'b1) ? 2'd0 : add_ln46_6_reg_3825);

assign select_ln46_19_fu_2388_p3 = ((or_ln46_19_fu_2366_p2[0:0] == 1'b1) ? select_ln46_18_fu_2382_p3 : 2'd3);

assign select_ln46_1_fu_1902_p3 = ((or_ln46_1_fu_1880_p2[0:0] == 1'b1) ? select_ln46_fu_1896_p3 : 2'd3);

assign select_ln46_20_fu_2396_p3 = ((or_ln46_20_fu_2377_p2[0:0] == 1'b1) ? select_ln46_19_fu_2388_p3 : add_ln46_6_reg_3825);

assign select_ln46_21_fu_2463_p3 = ((tmp_41_reg_3837[0:0] == 1'b1) ? 2'd0 : add_ln46_7_reg_3844);

assign select_ln46_22_fu_2469_p3 = ((or_ln46_22_fu_2447_p2[0:0] == 1'b1) ? select_ln46_21_fu_2463_p3 : 2'd3);

assign select_ln46_23_fu_2477_p3 = ((or_ln46_23_fu_2458_p2[0:0] == 1'b1) ? select_ln46_22_fu_2469_p3 : add_ln46_7_reg_3844);

assign select_ln46_24_fu_2544_p3 = ((tmp_47_reg_3856[0:0] == 1'b1) ? 2'd0 : add_ln46_8_reg_3863);

assign select_ln46_25_fu_2550_p3 = ((or_ln46_25_fu_2528_p2[0:0] == 1'b1) ? select_ln46_24_fu_2544_p3 : 2'd3);

assign select_ln46_26_fu_2558_p3 = ((or_ln46_26_fu_2539_p2[0:0] == 1'b1) ? select_ln46_25_fu_2550_p3 : add_ln46_8_reg_3863);

assign select_ln46_27_fu_2625_p3 = ((tmp_53_reg_3875[0:0] == 1'b1) ? 2'd0 : add_ln46_9_reg_3882);

assign select_ln46_28_fu_2631_p3 = ((or_ln46_28_fu_2609_p2[0:0] == 1'b1) ? select_ln46_27_fu_2625_p3 : 2'd3);

assign select_ln46_29_fu_2639_p3 = ((or_ln46_29_fu_2620_p2[0:0] == 1'b1) ? select_ln46_28_fu_2631_p3 : add_ln46_9_reg_3882);

assign select_ln46_2_fu_1910_p3 = ((or_ln46_2_fu_1891_p2[0:0] == 1'b1) ? select_ln46_1_fu_1902_p3 : add_ln46_reg_3711);

assign select_ln46_30_fu_2706_p3 = ((tmp_59_reg_3894[0:0] == 1'b1) ? 2'd0 : add_ln46_10_reg_3901);

assign select_ln46_31_fu_2712_p3 = ((or_ln46_31_fu_2690_p2[0:0] == 1'b1) ? select_ln46_30_fu_2706_p3 : 2'd3);

assign select_ln46_32_fu_2720_p3 = ((or_ln46_32_fu_2701_p2[0:0] == 1'b1) ? select_ln46_31_fu_2712_p3 : add_ln46_10_reg_3901);

assign select_ln46_33_fu_2787_p3 = ((tmp_65_reg_3913[0:0] == 1'b1) ? 2'd0 : add_ln46_11_reg_3920);

assign select_ln46_34_fu_2793_p3 = ((or_ln46_34_fu_2771_p2[0:0] == 1'b1) ? select_ln46_33_fu_2787_p3 : 2'd3);

assign select_ln46_35_fu_2801_p3 = ((or_ln46_35_fu_2782_p2[0:0] == 1'b1) ? select_ln46_34_fu_2793_p3 : add_ln46_11_reg_3920);

assign select_ln46_36_fu_2868_p3 = ((tmp_71_reg_3932[0:0] == 1'b1) ? 2'd0 : add_ln46_12_reg_3939);

assign select_ln46_37_fu_2874_p3 = ((or_ln46_37_fu_2852_p2[0:0] == 1'b1) ? select_ln46_36_fu_2868_p3 : 2'd3);

assign select_ln46_38_fu_2882_p3 = ((or_ln46_38_fu_2863_p2[0:0] == 1'b1) ? select_ln46_37_fu_2874_p3 : add_ln46_12_reg_3939);

assign select_ln46_39_fu_2949_p3 = ((tmp_77_reg_3951[0:0] == 1'b1) ? 2'd0 : add_ln46_13_reg_3958);

assign select_ln46_3_fu_1977_p3 = ((tmp_5_reg_3723[0:0] == 1'b1) ? 2'd0 : add_ln46_1_reg_3730);

assign select_ln46_40_fu_2955_p3 = ((or_ln46_40_fu_2933_p2[0:0] == 1'b1) ? select_ln46_39_fu_2949_p3 : 2'd3);

assign select_ln46_41_fu_2963_p3 = ((or_ln46_41_fu_2944_p2[0:0] == 1'b1) ? select_ln46_40_fu_2955_p3 : add_ln46_13_reg_3958);

assign select_ln46_42_fu_3030_p3 = ((tmp_83_reg_3970[0:0] == 1'b1) ? 2'd0 : add_ln46_14_reg_3977);

assign select_ln46_43_fu_3036_p3 = ((or_ln46_43_fu_3014_p2[0:0] == 1'b1) ? select_ln46_42_fu_3030_p3 : 2'd3);

assign select_ln46_44_fu_3044_p3 = ((or_ln46_44_fu_3025_p2[0:0] == 1'b1) ? select_ln46_43_fu_3036_p3 : add_ln46_14_reg_3977);

assign select_ln46_45_fu_3111_p3 = ((tmp_89_reg_3989[0:0] == 1'b1) ? 2'd0 : add_ln46_15_reg_3996);

assign select_ln46_46_fu_3117_p3 = ((or_ln46_46_fu_3095_p2[0:0] == 1'b1) ? select_ln46_45_fu_3111_p3 : 2'd3);

assign select_ln46_47_fu_3125_p3 = ((or_ln46_47_fu_3106_p2[0:0] == 1'b1) ? select_ln46_46_fu_3117_p3 : add_ln46_15_reg_3996);

assign select_ln46_48_fu_3192_p3 = ((tmp_95_reg_4008[0:0] == 1'b1) ? 2'd0 : add_ln46_16_reg_4015);

assign select_ln46_49_fu_3198_p3 = ((or_ln46_49_fu_3176_p2[0:0] == 1'b1) ? select_ln46_48_fu_3192_p3 : 2'd3);

assign select_ln46_4_fu_1983_p3 = ((or_ln46_4_fu_1961_p2[0:0] == 1'b1) ? select_ln46_3_fu_1977_p3 : 2'd3);

assign select_ln46_50_fu_3206_p3 = ((or_ln46_50_fu_3187_p2[0:0] == 1'b1) ? select_ln46_49_fu_3198_p3 : add_ln46_16_reg_4015);

assign select_ln46_51_fu_3273_p3 = ((tmp_101_reg_4027[0:0] == 1'b1) ? 2'd0 : add_ln46_17_reg_4034);

assign select_ln46_52_fu_3279_p3 = ((or_ln46_52_fu_3257_p2[0:0] == 1'b1) ? select_ln46_51_fu_3273_p3 : 2'd3);

assign select_ln46_53_fu_3287_p3 = ((or_ln46_53_fu_3268_p2[0:0] == 1'b1) ? select_ln46_52_fu_3279_p3 : add_ln46_17_reg_4034);

assign select_ln46_54_fu_3354_p3 = ((tmp_107_reg_4046[0:0] == 1'b1) ? 2'd0 : add_ln46_18_reg_4053);

assign select_ln46_55_fu_3360_p3 = ((or_ln46_55_fu_3338_p2[0:0] == 1'b1) ? select_ln46_54_fu_3354_p3 : 2'd3);

assign select_ln46_56_fu_3368_p3 = ((or_ln46_56_fu_3349_p2[0:0] == 1'b1) ? select_ln46_55_fu_3360_p3 : add_ln46_18_reg_4053);

assign select_ln46_57_fu_3435_p3 = ((tmp_113_reg_4065[0:0] == 1'b1) ? 2'd0 : add_ln46_19_reg_4072);

assign select_ln46_58_fu_3441_p3 = ((or_ln46_58_fu_3419_p2[0:0] == 1'b1) ? select_ln46_57_fu_3435_p3 : 2'd3);

assign select_ln46_59_fu_3449_p3 = ((or_ln46_59_fu_3430_p2[0:0] == 1'b1) ? select_ln46_58_fu_3441_p3 : add_ln46_19_reg_4072);

assign select_ln46_5_fu_1991_p3 = ((or_ln46_5_fu_1972_p2[0:0] == 1'b1) ? select_ln46_4_fu_1983_p3 : add_ln46_1_reg_3730);

assign select_ln46_6_fu_2058_p3 = ((tmp_11_reg_3742[0:0] == 1'b1) ? 2'd0 : add_ln46_2_reg_3749);

assign select_ln46_7_fu_2064_p3 = ((or_ln46_7_fu_2042_p2[0:0] == 1'b1) ? select_ln46_6_fu_2058_p3 : 2'd3);

assign select_ln46_8_fu_2072_p3 = ((or_ln46_8_fu_2053_p2[0:0] == 1'b1) ? select_ln46_7_fu_2064_p3 : add_ln46_2_reg_3749);

assign select_ln46_9_fu_2139_p3 = ((tmp_17_reg_3761[0:0] == 1'b1) ? 2'd0 : add_ln46_3_reg_3768);

assign select_ln46_fu_1896_p3 = ((tmp_reg_3704[0:0] == 1'b1) ? 2'd0 : add_ln46_reg_3711);

assign tmp_100_fu_3152_p3 = add_ln46_16_reg_4015[32'd1];

assign tmp_102_fu_1616_p3 = data_17_val[32'd7];

assign tmp_103_fu_3226_p3 = data_17_val_read_reg_3596[32'd9];

assign tmp_104_fu_1634_p3 = data_17_val[32'd8];

assign tmp_105_fu_1664_p4 = {{data_17_val[15:10]}};

assign tmp_106_fu_3233_p3 = add_ln46_17_reg_4034[32'd1];

assign tmp_108_fu_1698_p3 = data_18_val[32'd7];

assign tmp_109_fu_3307_p3 = data_18_val_read_reg_3590[32'd9];

assign tmp_10_fu_1937_p3 = add_ln46_1_reg_3730[32'd1];

assign tmp_110_fu_1716_p3 = data_18_val[32'd8];

assign tmp_111_fu_1746_p4 = {{data_18_val[15:10]}};

assign tmp_112_fu_3314_p3 = add_ln46_18_reg_4053[32'd1];

assign tmp_114_fu_1780_p3 = data_19_val[32'd7];

assign tmp_115_fu_3388_p3 = data_19_val_read_reg_3584[32'd9];

assign tmp_116_fu_1798_p3 = data_19_val[32'd8];

assign tmp_117_fu_1828_p4 = {{data_19_val[15:10]}};

assign tmp_118_fu_3395_p3 = add_ln46_19_reg_4072[32'd1];

assign tmp_12_fu_386_p3 = data_2_val[32'd7];

assign tmp_13_fu_2011_p3 = data_2_val_read_reg_3686[32'd9];

assign tmp_14_fu_404_p3 = data_2_val[32'd8];

assign tmp_15_fu_434_p4 = {{data_2_val[15:10]}};

assign tmp_16_fu_2018_p3 = add_ln46_2_reg_3749[32'd1];

assign tmp_18_fu_468_p3 = data_3_val[32'd7];

assign tmp_19_fu_2092_p3 = data_3_val_read_reg_3680[32'd9];

assign tmp_1_fu_222_p3 = data_0_val[32'd7];

assign tmp_20_fu_486_p3 = data_3_val[32'd8];

assign tmp_21_fu_516_p4 = {{data_3_val[15:10]}};

assign tmp_22_fu_2099_p3 = add_ln46_3_reg_3768[32'd1];

assign tmp_24_fu_550_p3 = data_4_val[32'd7];

assign tmp_25_fu_2173_p3 = data_4_val_read_reg_3674[32'd9];

assign tmp_26_fu_568_p3 = data_4_val[32'd8];

assign tmp_27_fu_598_p4 = {{data_4_val[15:10]}};

assign tmp_28_fu_2180_p3 = add_ln46_4_reg_3787[32'd1];

assign tmp_2_fu_1849_p3 = data_0_val_read_reg_3698[32'd9];

assign tmp_30_fu_632_p3 = data_5_val[32'd7];

assign tmp_31_fu_2254_p3 = data_5_val_read_reg_3668[32'd9];

assign tmp_32_fu_650_p3 = data_5_val[32'd8];

assign tmp_33_fu_680_p4 = {{data_5_val[15:10]}};

assign tmp_34_fu_2261_p3 = add_ln46_5_reg_3806[32'd1];

assign tmp_36_fu_714_p3 = data_6_val[32'd7];

assign tmp_37_fu_2335_p3 = data_6_val_read_reg_3662[32'd9];

assign tmp_38_fu_732_p3 = data_6_val[32'd8];

assign tmp_39_fu_762_p4 = {{data_6_val[15:10]}};

assign tmp_3_fu_240_p3 = data_0_val[32'd8];

assign tmp_40_fu_2342_p3 = add_ln46_6_reg_3825[32'd1];

assign tmp_42_fu_796_p3 = data_7_val[32'd7];

assign tmp_43_fu_2416_p3 = data_7_val_read_reg_3656[32'd9];

assign tmp_44_fu_814_p3 = data_7_val[32'd8];

assign tmp_45_fu_844_p4 = {{data_7_val[15:10]}};

assign tmp_46_fu_2423_p3 = add_ln46_7_reg_3844[32'd1];

assign tmp_48_fu_878_p3 = data_8_val[32'd7];

assign tmp_49_fu_2497_p3 = data_8_val_read_reg_3650[32'd9];

assign tmp_4_fu_1856_p3 = add_ln46_reg_3711[32'd1];

assign tmp_50_fu_896_p3 = data_8_val[32'd8];

assign tmp_51_fu_926_p4 = {{data_8_val[15:10]}};

assign tmp_52_fu_2504_p3 = add_ln46_8_reg_3863[32'd1];

assign tmp_54_fu_960_p3 = data_9_val[32'd7];

assign tmp_55_fu_2578_p3 = data_9_val_read_reg_3644[32'd9];

assign tmp_56_fu_978_p3 = data_9_val[32'd8];

assign tmp_57_fu_1008_p4 = {{data_9_val[15:10]}};

assign tmp_58_fu_2585_p3 = add_ln46_9_reg_3882[32'd1];

assign tmp_60_fu_1042_p3 = data_10_val[32'd7];

assign tmp_61_fu_2659_p3 = data_10_val_read_reg_3638[32'd9];

assign tmp_62_fu_1060_p3 = data_10_val[32'd8];

assign tmp_63_fu_1090_p4 = {{data_10_val[15:10]}};

assign tmp_64_fu_2666_p3 = add_ln46_10_reg_3901[32'd1];

assign tmp_66_fu_1124_p3 = data_11_val[32'd7];

assign tmp_67_fu_2740_p3 = data_11_val_read_reg_3632[32'd9];

assign tmp_68_fu_1142_p3 = data_11_val[32'd8];

assign tmp_69_fu_1172_p4 = {{data_11_val[15:10]}};

assign tmp_6_fu_304_p3 = data_1_val[32'd7];

assign tmp_70_fu_2747_p3 = add_ln46_11_reg_3920[32'd1];

assign tmp_72_fu_1206_p3 = data_12_val[32'd7];

assign tmp_73_fu_2821_p3 = data_12_val_read_reg_3626[32'd9];

assign tmp_74_fu_1224_p3 = data_12_val[32'd8];

assign tmp_75_fu_1254_p4 = {{data_12_val[15:10]}};

assign tmp_76_fu_2828_p3 = add_ln46_12_reg_3939[32'd1];

assign tmp_78_fu_1288_p3 = data_13_val[32'd7];

assign tmp_79_fu_2902_p3 = data_13_val_read_reg_3620[32'd9];

assign tmp_7_fu_1930_p3 = data_1_val_read_reg_3692[32'd9];

assign tmp_80_fu_1306_p3 = data_13_val[32'd8];

assign tmp_81_fu_1336_p4 = {{data_13_val[15:10]}};

assign tmp_82_fu_2909_p3 = add_ln46_13_reg_3958[32'd1];

assign tmp_84_fu_1370_p3 = data_14_val[32'd7];

assign tmp_85_fu_2983_p3 = data_14_val_read_reg_3614[32'd9];

assign tmp_86_fu_1388_p3 = data_14_val[32'd8];

assign tmp_87_fu_1418_p4 = {{data_14_val[15:10]}};

assign tmp_88_fu_2990_p3 = add_ln46_14_reg_3977[32'd1];

assign tmp_8_fu_322_p3 = data_1_val[32'd8];

assign tmp_90_fu_1452_p3 = data_15_val[32'd7];

assign tmp_91_fu_3064_p3 = data_15_val_read_reg_3608[32'd9];

assign tmp_92_fu_1470_p3 = data_15_val[32'd8];

assign tmp_93_fu_1500_p4 = {{data_15_val[15:10]}};

assign tmp_94_fu_3071_p3 = add_ln46_15_reg_3996[32'd1];

assign tmp_96_fu_1534_p3 = data_16_val[32'd7];

assign tmp_97_fu_3145_p3 = data_16_val_read_reg_3602[32'd9];

assign tmp_98_fu_1552_p3 = data_16_val[32'd8];

assign tmp_99_fu_1582_p4 = {{data_16_val[15:10]}};

assign tmp_9_fu_352_p4 = {{data_1_val[15:10]}};

assign tmp_s_fu_270_p4 = {{data_0_val[15:10]}};

assign trunc_ln46_10_fu_1114_p4 = {{data_11_val[9:8]}};

assign trunc_ln46_11_fu_1196_p4 = {{data_12_val[9:8]}};

assign trunc_ln46_12_fu_1278_p4 = {{data_13_val[9:8]}};

assign trunc_ln46_13_fu_1360_p4 = {{data_14_val[9:8]}};

assign trunc_ln46_14_fu_1442_p4 = {{data_15_val[9:8]}};

assign trunc_ln46_15_fu_1524_p4 = {{data_16_val[9:8]}};

assign trunc_ln46_16_fu_1606_p4 = {{data_17_val[9:8]}};

assign trunc_ln46_17_fu_1688_p4 = {{data_18_val[9:8]}};

assign trunc_ln46_18_fu_1770_p4 = {{data_19_val[9:8]}};

assign trunc_ln46_19_fu_312_p1 = data_1_val[6:0];

assign trunc_ln46_1_fu_294_p4 = {{data_1_val[9:8]}};

assign trunc_ln46_20_fu_394_p1 = data_2_val[6:0];

assign trunc_ln46_21_fu_476_p1 = data_3_val[6:0];

assign trunc_ln46_22_fu_558_p1 = data_4_val[6:0];

assign trunc_ln46_23_fu_640_p1 = data_5_val[6:0];

assign trunc_ln46_24_fu_722_p1 = data_6_val[6:0];

assign trunc_ln46_25_fu_804_p1 = data_7_val[6:0];

assign trunc_ln46_26_fu_886_p1 = data_8_val[6:0];

assign trunc_ln46_27_fu_968_p1 = data_9_val[6:0];

assign trunc_ln46_28_fu_1050_p1 = data_10_val[6:0];

assign trunc_ln46_29_fu_1132_p1 = data_11_val[6:0];

assign trunc_ln46_2_fu_376_p4 = {{data_2_val[9:8]}};

assign trunc_ln46_30_fu_1214_p1 = data_12_val[6:0];

assign trunc_ln46_31_fu_1296_p1 = data_13_val[6:0];

assign trunc_ln46_32_fu_1378_p1 = data_14_val[6:0];

assign trunc_ln46_33_fu_1460_p1 = data_15_val[6:0];

assign trunc_ln46_34_fu_1542_p1 = data_16_val[6:0];

assign trunc_ln46_35_fu_1624_p1 = data_17_val[6:0];

assign trunc_ln46_36_fu_1706_p1 = data_18_val[6:0];

assign trunc_ln46_37_fu_1788_p1 = data_19_val[6:0];

assign trunc_ln46_3_fu_458_p4 = {{data_3_val[9:8]}};

assign trunc_ln46_4_fu_540_p4 = {{data_4_val[9:8]}};

assign trunc_ln46_5_fu_622_p4 = {{data_5_val[9:8]}};

assign trunc_ln46_6_fu_704_p4 = {{data_6_val[9:8]}};

assign trunc_ln46_7_fu_786_p4 = {{data_7_val[9:8]}};

assign trunc_ln46_8_fu_868_p4 = {{data_8_val[9:8]}};

assign trunc_ln46_9_fu_950_p4 = {{data_9_val[9:8]}};

assign trunc_ln46_fu_230_p1 = data_0_val[6:0];

assign trunc_ln46_s_fu_1032_p4 = {{data_10_val[9:8]}};

assign trunc_ln_fu_212_p4 = {{data_0_val[9:8]}};

assign xor_ln46_10_fu_2695_p2 = (empty_20_fu_2685_p2 ^ 1'd1);

assign xor_ln46_11_fu_2776_p2 = (empty_21_fu_2766_p2 ^ 1'd1);

assign xor_ln46_12_fu_2857_p2 = (empty_22_fu_2847_p2 ^ 1'd1);

assign xor_ln46_13_fu_2938_p2 = (empty_23_fu_2928_p2 ^ 1'd1);

assign xor_ln46_14_fu_3019_p2 = (empty_24_fu_3009_p2 ^ 1'd1);

assign xor_ln46_15_fu_3100_p2 = (empty_25_fu_3090_p2 ^ 1'd1);

assign xor_ln46_16_fu_3181_p2 = (empty_26_fu_3171_p2 ^ 1'd1);

assign xor_ln46_17_fu_3262_p2 = (empty_27_fu_3252_p2 ^ 1'd1);

assign xor_ln46_18_fu_3343_p2 = (empty_28_fu_3333_p2 ^ 1'd1);

assign xor_ln46_19_fu_3424_p2 = (empty_29_fu_3414_p2 ^ 1'd1);

assign xor_ln46_1_fu_1966_p2 = (empty_11_fu_1956_p2 ^ 1'd1);

assign xor_ln46_2_fu_2047_p2 = (empty_12_fu_2037_p2 ^ 1'd1);

assign xor_ln46_3_fu_2128_p2 = (empty_13_fu_2118_p2 ^ 1'd1);

assign xor_ln46_4_fu_2209_p2 = (empty_14_fu_2199_p2 ^ 1'd1);

assign xor_ln46_5_fu_2290_p2 = (empty_15_fu_2280_p2 ^ 1'd1);

assign xor_ln46_6_fu_2371_p2 = (empty_16_fu_2361_p2 ^ 1'd1);

assign xor_ln46_7_fu_2452_p2 = (empty_17_fu_2442_p2 ^ 1'd1);

assign xor_ln46_8_fu_2533_p2 = (empty_18_fu_2523_p2 ^ 1'd1);

assign xor_ln46_9_fu_2614_p2 = (empty_19_fu_2604_p2 ^ 1'd1);

assign xor_ln46_fu_1885_p2 = (empty_fu_1875_p2 ^ 1'd1);

assign zext_ln46_10_fu_1080_p1 = and_ln46_20_fu_1074_p2;

assign zext_ln46_11_fu_1162_p1 = and_ln46_22_fu_1156_p2;

assign zext_ln46_12_fu_1244_p1 = and_ln46_24_fu_1238_p2;

assign zext_ln46_13_fu_1326_p1 = and_ln46_26_fu_1320_p2;

assign zext_ln46_14_fu_1408_p1 = and_ln46_28_fu_1402_p2;

assign zext_ln46_15_fu_1490_p1 = and_ln46_30_fu_1484_p2;

assign zext_ln46_16_fu_1572_p1 = and_ln46_32_fu_1566_p2;

assign zext_ln46_17_fu_1654_p1 = and_ln46_34_fu_1648_p2;

assign zext_ln46_18_fu_1736_p1 = and_ln46_36_fu_1730_p2;

assign zext_ln46_19_fu_1818_p1 = and_ln46_38_fu_1812_p2;

assign zext_ln46_1_fu_342_p1 = and_ln46_2_fu_336_p2;

assign zext_ln46_2_fu_424_p1 = and_ln46_4_fu_418_p2;

assign zext_ln46_3_fu_506_p1 = and_ln46_6_fu_500_p2;

assign zext_ln46_4_fu_588_p1 = and_ln46_8_fu_582_p2;

assign zext_ln46_5_fu_670_p1 = and_ln46_10_fu_664_p2;

assign zext_ln46_6_fu_752_p1 = and_ln46_12_fu_746_p2;

assign zext_ln46_7_fu_834_p1 = and_ln46_14_fu_828_p2;

assign zext_ln46_8_fu_916_p1 = and_ln46_16_fu_910_p2;

assign zext_ln46_9_fu_998_p1 = and_ln46_18_fu_992_p2;

assign zext_ln46_fu_260_p1 = and_ln46_fu_254_p2;

endmodule //myproject_relu_ap_fixed_16_6_5_3_0_ap_ufixed_2_0_4_0_0_relu_config9_s
