// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_2_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_4_val,
        data_5_val,
        data_6_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [1:0] data_0_val;
input  [1:0] data_1_val;
input  [1:0] data_4_val;
input  [1:0] data_5_val;
input  [1:0] data_6_val;
output  [11:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [2:0] add_ln58_134_fu_82_p2;
reg   [2:0] add_ln58_134_reg_134;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] add_ln58_136_fu_98_p2;
reg   [3:0] add_ln58_136_reg_139;
wire    ap_block_pp0_stage0;
wire   [2:0] zext_ln70_fu_62_p1;
wire   [2:0] zext_ln70_17_fu_66_p1;
wire   [2:0] data_5_val_cast_fu_74_p1;
wire   [2:0] zext_ln58_fu_78_p1;
wire   [2:0] add_ln58_135_fu_88_p2;
wire   [3:0] zext_ln58_12_fu_94_p1;
wire   [3:0] data_0_val_cast_fu_70_p1;
wire   [3:0] zext_ln58_11_fu_104_p1;
wire   [3:0] sub_ln58_fu_107_p2;
wire   [4:0] zext_ln58_13_fu_117_p1;
wire  signed [4:0] sext_ln58_fu_113_p1;
wire   [4:0] add_ln58_fu_120_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_134_reg_134 <= add_ln58_134_fu_82_p2;
        add_ln58_136_reg_139 <= add_ln58_136_fu_98_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_134_fu_82_p2 = (zext_ln70_fu_62_p1 + zext_ln70_17_fu_66_p1);

assign add_ln58_135_fu_88_p2 = (data_5_val_cast_fu_74_p1 + zext_ln58_fu_78_p1);

assign add_ln58_136_fu_98_p2 = (zext_ln58_12_fu_94_p1 + data_0_val_cast_fu_70_p1);

assign add_ln58_fu_120_p2 = ($signed(zext_ln58_13_fu_117_p1) + $signed(sext_ln58_fu_113_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = {{add_ln58_fu_120_p2}, {7'd0}};

assign data_0_val_cast_fu_70_p1 = data_0_val;

assign data_5_val_cast_fu_74_p1 = data_5_val;

assign sext_ln58_fu_113_p1 = $signed(sub_ln58_fu_107_p2);

assign sub_ln58_fu_107_p2 = (4'd0 - zext_ln58_11_fu_104_p1);

assign zext_ln58_11_fu_104_p1 = add_ln58_134_reg_134;

assign zext_ln58_12_fu_94_p1 = add_ln58_135_fu_88_p2;

assign zext_ln58_13_fu_117_p1 = add_ln58_136_reg_139;

assign zext_ln58_fu_78_p1 = data_6_val;

assign zext_ln70_17_fu_66_p1 = data_4_val;

assign zext_ln70_fu_62_p1 = data_1_val;

endmodule //myproject_dense_latency_ap_ufixed_2_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s
