// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_2_0_4_0_0_ap_fixed_16_6_5_3_0_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [1:0] data_0_val;
input  [1:0] data_1_val;
input  [1:0] data_2_val;
input  [1:0] data_3_val;
input  [1:0] data_4_val;
input  [1:0] data_5_val;
input  [1:0] data_6_val;
input  [1:0] data_7_val;
input  [1:0] data_8_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire  signed [9:0] shl_ln42_s_fu_120_p3;
reg  signed [9:0] shl_ln42_s_reg_900;
wire    ap_block_pp0_stage0_11001;
wire  signed [10:0] shl_ln42_47_cast_fu_128_p1;
reg  signed [10:0] shl_ln42_47_cast_reg_905;
wire  signed [10:0] sext_ln42_fu_150_p1;
reg  signed [10:0] sext_ln42_reg_911;
wire   [8:0] shl_ln42_47_fu_154_p3;
reg   [8:0] shl_ln42_47_reg_917;
wire   [9:0] zext_ln73_19_fu_178_p1;
reg   [9:0] zext_ln73_19_reg_922;
wire   [2:0] sub_ln73_28_fu_182_p2;
reg   [2:0] sub_ln73_28_reg_927;
wire   [2:0] sub_ln73_29_fu_192_p2;
reg   [2:0] sub_ln73_29_reg_932;
wire   [8:0] shl_ln42_51_fu_198_p3;
reg   [8:0] shl_ln42_51_reg_937;
wire   [9:0] shl_ln42_53_cast_fu_206_p1;
reg   [9:0] shl_ln42_53_cast_reg_942;
wire   [8:0] shl_ln42_52_fu_214_p3;
reg   [8:0] shl_ln42_52_reg_947;
wire   [9:0] zext_ln73_21_fu_222_p1;
reg   [9:0] zext_ln73_21_reg_952;
wire   [2:0] sub_ln73_30_fu_226_p2;
reg   [2:0] sub_ln73_30_reg_957;
wire   [8:0] shl_ln42_54_fu_236_p3;
reg   [8:0] shl_ln42_54_reg_962;
wire  signed [9:0] shl_ln42_55_fu_254_p3;
reg  signed [9:0] shl_ln42_55_reg_967;
wire  signed [9:0] shl_ln42_59_fu_314_p3;
reg  signed [9:0] shl_ln42_59_reg_974;
wire  signed [9:0] shl_ln42_61_fu_344_p3;
reg  signed [9:0] shl_ln42_61_reg_979;
wire  signed [10:0] add_ln58_fu_352_p2;
reg  signed [10:0] add_ln58_reg_984;
wire   [9:0] add_ln58_161_fu_358_p2;
reg   [9:0] add_ln58_161_reg_990;
wire   [9:0] add_ln58_166_fu_364_p2;
reg   [9:0] add_ln58_166_reg_995;
wire   [9:0] add_ln58_169_fu_370_p2;
reg   [9:0] add_ln58_169_reg_1000;
wire   [9:0] add_ln58_174_fu_376_p2;
reg   [9:0] add_ln58_174_reg_1005;
wire   [9:0] add_ln58_176_fu_382_p2;
reg   [9:0] add_ln58_176_reg_1010;
wire   [9:0] add_ln58_177_fu_388_p2;
reg   [9:0] add_ln58_177_reg_1016;
wire   [9:0] add_ln58_180_fu_394_p2;
reg   [9:0] add_ln58_180_reg_1021;
wire   [9:0] add_ln58_181_fu_400_p2;
reg   [9:0] add_ln58_181_reg_1026;
wire   [9:0] add_ln58_185_fu_406_p2;
reg   [9:0] add_ln58_185_reg_1031;
wire  signed [9:0] add_ln58_189_fu_412_p2;
reg  signed [9:0] add_ln58_189_reg_1036;
wire   [9:0] add_ln58_195_fu_418_p2;
reg   [9:0] add_ln58_195_reg_1042;
wire   [9:0] add_ln58_199_fu_424_p2;
reg   [9:0] add_ln58_199_reg_1047;
wire    ap_block_pp0_stage0;
wire   [8:0] shl_ln_fu_102_p3;
wire   [2:0] zext_ln70_fu_98_p1;
wire   [2:0] sub_ln73_fu_114_p2;
wire   [2:0] zext_ln70_31_fu_132_p1;
wire   [2:0] sub_ln73_27_fu_136_p2;
wire   [9:0] shl_ln42_46_fu_142_p3;
wire   [8:0] shl_ln42_48_fu_170_p3;
wire   [2:0] zext_ln70_32_fu_166_p1;
wire   [2:0] zext_ln70_33_fu_188_p1;
wire   [2:0] zext_ln70_34_fu_210_p1;
wire   [2:0] zext_ln70_35_fu_232_p1;
wire   [2:0] sub_ln73_31_fu_248_p2;
wire   [8:0] shl_ln42_56_fu_266_p3;
wire   [2:0] zext_ln70_36_fu_262_p1;
wire   [2:0] sub_ln73_32_fu_278_p2;
wire   [8:0] shl_ln42_58_fu_296_p3;
wire   [2:0] zext_ln70_37_fu_292_p1;
wire   [2:0] sub_ln73_33_fu_308_p2;
wire   [8:0] shl_ln42_60_fu_326_p3;
wire   [2:0] zext_ln70_38_fu_322_p1;
wire   [2:0] sub_ln73_34_fu_338_p2;
wire   [9:0] zext_ln73_fu_110_p1;
wire   [9:0] zext_ln73_25_fu_304_p1;
wire   [9:0] shl_ln42_57_fu_284_p3;
wire   [9:0] shl_ln42_49_cast_fu_162_p1;
wire   [9:0] zext_ln73_23_fu_244_p1;
wire   [9:0] zext_ln73_24_fu_274_p1;
wire   [9:0] zext_ln73_26_fu_334_p1;
wire  signed [9:0] shl_ln42_49_fu_436_p3;
wire  signed [9:0] shl_ln42_50_fu_447_p3;
wire  signed [9:0] shl_ln42_53_fu_468_p3;
wire   [9:0] add_ln58_162_fu_501_p2;
wire   [9:0] add_ln58_163_fu_510_p2;
wire  signed [10:0] sext_ln58_127_fu_514_p1;
wire  signed [10:0] shl_ln42_55_cast_fu_479_p1;
wire   [10:0] add_ln58_164_fu_518_p2;
wire  signed [10:0] shl_ln42_51_cast_fu_443_p1;
wire   [10:0] zext_ln58_18_fu_533_p1;
wire   [10:0] add_ln58_165_fu_528_p2;
wire   [10:0] add_ln58_167_fu_536_p2;
wire   [9:0] add_ln58_168_fu_546_p2;
wire  signed [10:0] sext_ln58_131_fu_554_p1;
wire  signed [10:0] sext_ln58_130_fu_550_p1;
wire   [10:0] add_ln58_170_fu_557_p2;
wire  signed [10:0] shl_ln42_61_cast_fu_489_p1;
wire   [10:0] add_ln58_171_fu_567_p2;
wire   [10:0] shl_ln42_53_cast38_fu_462_p1;
wire   [10:0] add_ln58_172_fu_572_p2;
wire  signed [11:0] sext_ln42_12_fu_458_p1;
wire  signed [11:0] sext_ln58_125_fu_495_p1;
wire  signed [11:0] sext_ln58_134_fu_588_p1;
wire   [11:0] add_ln58_173_fu_582_p2;
wire   [11:0] add_ln58_175_fu_591_p2;
wire  signed [10:0] sext_ln58_136_fu_604_p1;
wire   [10:0] add_ln58_178_fu_607_p2;
wire  signed [11:0] sext_ln58_137_fu_613_p1;
wire   [11:0] zext_ln58_19_fu_601_p1;
wire   [11:0] add_ln58_179_fu_617_p2;
wire   [10:0] zext_ln58_21_fu_630_p1;
wire   [10:0] zext_ln73_20_fu_465_p1;
wire   [10:0] add_ln58_182_fu_633_p2;
wire   [10:0] zext_ln58_20_fu_627_p1;
wire   [10:0] add_ln58_183_fu_639_p2;
wire   [10:0] add_ln58_184_fu_649_p2;
wire  signed [10:0] sext_ln58_140_fu_658_p1;
wire   [10:0] zext_ln73_22_fu_483_p1;
wire   [10:0] add_ln58_186_fu_661_p2;
wire  signed [11:0] sext_ln58_141_fu_667_p1;
wire  signed [11:0] sext_ln58_139_fu_654_p1;
wire   [11:0] add_ln58_187_fu_671_p2;
wire   [10:0] add_ln58_188_fu_681_p2;
wire  signed [11:0] sext_ln58_144_fu_690_p1;
wire  signed [11:0] sext_ln58_143_fu_686_p1;
wire   [11:0] add_ln58_190_fu_693_p2;
wire   [10:0] zext_ln58_23_fu_703_p1;
wire   [10:0] add_ln58_191_fu_706_p2;
wire  signed [10:0] sext_ln58_147_fu_715_p1;
wire  signed [10:0] sext_ln42_11_fu_454_p1;
wire   [10:0] add_ln58_192_fu_718_p2;
wire  signed [11:0] sext_ln58_148_fu_724_p1;
wire  signed [11:0] sext_ln58_146_fu_711_p1;
wire   [11:0] add_ln58_193_fu_728_p2;
wire   [10:0] zext_ln58_fu_498_p1;
wire   [10:0] add_ln58_194_fu_738_p2;
wire  signed [11:0] sext_ln58_150_fu_748_p1;
wire   [11:0] zext_ln58_24_fu_744_p1;
wire   [11:0] add_ln58_196_fu_751_p2;
wire  signed [10:0] sext_ln58_fu_492_p1;
wire   [10:0] add_ln58_197_fu_761_p2;
wire   [10:0] shl_ln42_49_cast42_fu_433_p1;
wire   [10:0] add_ln58_198_fu_771_p2;
wire  signed [10:0] sext_ln58_153_fu_781_p1;
wire  signed [10:0] shl_ln42_57_cast_fu_486_p1;
wire   [10:0] add_ln58_200_fu_784_p2;
wire  signed [11:0] sext_ln58_154_fu_790_p1;
wire   [11:0] zext_ln58_25_fu_777_p1;
wire   [11:0] add_ln58_201_fu_794_p2;
wire   [15:0] zext_ln58_22_fu_645_p1;
wire  signed [15:0] sext_ln58_142_fu_677_p1;
wire  signed [15:0] sext_ln58_145_fu_699_p1;
wire  signed [15:0] sext_ln58_149_fu_734_p1;
wire  signed [15:0] sext_ln58_151_fu_757_p1;
wire  signed [15:0] sext_ln58_129_fu_542_p1;
wire  signed [15:0] sext_ln58_126_fu_506_p1;
wire  signed [15:0] shl_ln42_47_cast43_fu_430_p1;
wire  signed [15:0] sext_ln58_128_fu_524_p1;
wire  signed [15:0] shl_ln42_55_cast44_fu_475_p1;
wire  signed [15:0] sext_ln58_152_fu_767_p1;
wire  signed [15:0] sext_ln58_132_fu_563_p1;
wire  signed [15:0] sext_ln58_133_fu_578_p1;
wire  signed [15:0] sext_ln58_135_fu_597_p1;
wire  signed [15:0] sext_ln68_fu_800_p1;
wire  signed [15:0] sext_ln58_138_fu_623_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_161_reg_990[9 : 7] <= add_ln58_161_fu_358_p2[9 : 7];
        add_ln58_166_reg_995[9 : 7] <= add_ln58_166_fu_364_p2[9 : 7];
        add_ln58_169_reg_1000[9 : 7] <= add_ln58_169_fu_370_p2[9 : 7];
        add_ln58_174_reg_1005[9 : 7] <= add_ln58_174_fu_376_p2[9 : 7];
        add_ln58_176_reg_1010[9 : 7] <= add_ln58_176_fu_382_p2[9 : 7];
        add_ln58_177_reg_1016[9 : 7] <= add_ln58_177_fu_388_p2[9 : 7];
        add_ln58_180_reg_1021[9 : 7] <= add_ln58_180_fu_394_p2[9 : 7];
        add_ln58_181_reg_1026[9 : 7] <= add_ln58_181_fu_400_p2[9 : 7];
        add_ln58_185_reg_1031[9 : 7] <= add_ln58_185_fu_406_p2[9 : 7];
        add_ln58_189_reg_1036[9 : 7] <= add_ln58_189_fu_412_p2[9 : 7];
        add_ln58_195_reg_1042[9 : 7] <= add_ln58_195_fu_418_p2[9 : 7];
        add_ln58_199_reg_1047[9 : 7] <= add_ln58_199_fu_424_p2[9 : 7];
        add_ln58_reg_984[10 : 7] <= add_ln58_fu_352_p2[10 : 7];
        sext_ln42_reg_911[10 : 7] <= sext_ln42_fu_150_p1[10 : 7];
        shl_ln42_47_cast_reg_905[10 : 7] <= shl_ln42_47_cast_fu_128_p1[10 : 7];
        shl_ln42_47_reg_917[8 : 7] <= shl_ln42_47_fu_154_p3[8 : 7];
        shl_ln42_51_reg_937[8 : 7] <= shl_ln42_51_fu_198_p3[8 : 7];
        shl_ln42_52_reg_947[8 : 7] <= shl_ln42_52_fu_214_p3[8 : 7];
        shl_ln42_53_cast_reg_942[8 : 7] <= shl_ln42_53_cast_fu_206_p1[8 : 7];
        shl_ln42_54_reg_962[8 : 7] <= shl_ln42_54_fu_236_p3[8 : 7];
        shl_ln42_55_reg_967[9 : 7] <= shl_ln42_55_fu_254_p3[9 : 7];
        shl_ln42_59_reg_974[9 : 7] <= shl_ln42_59_fu_314_p3[9 : 7];
        shl_ln42_61_reg_979[9 : 7] <= shl_ln42_61_fu_344_p3[9 : 7];
        shl_ln42_s_reg_900[9 : 7] <= shl_ln42_s_fu_120_p3[9 : 7];
        sub_ln73_28_reg_927 <= sub_ln73_28_fu_182_p2;
        sub_ln73_29_reg_932 <= sub_ln73_29_fu_192_p2;
        sub_ln73_30_reg_957 <= sub_ln73_30_fu_226_p2;
        zext_ln73_19_reg_922[8 : 7] <= zext_ln73_19_fu_178_p1[8 : 7];
        zext_ln73_21_reg_952[8 : 7] <= zext_ln73_21_fu_222_p1[8 : 7];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_161_fu_358_p2 = (shl_ln42_53_cast_fu_206_p1 + zext_ln73_fu_110_p1);

assign add_ln58_162_fu_501_p2 = ($signed(shl_ln42_49_fu_436_p3) + $signed(shl_ln42_53_cast_reg_942));

assign add_ln58_163_fu_510_p2 = ($signed(zext_ln73_19_reg_922) + $signed(shl_ln42_55_reg_967));

assign add_ln58_164_fu_518_p2 = ($signed(sext_ln58_127_fu_514_p1) + $signed(shl_ln42_55_cast_fu_479_p1));

assign add_ln58_165_fu_528_p2 = ($signed(shl_ln42_51_cast_fu_443_p1) + $signed(shl_ln42_47_cast_reg_905));

assign add_ln58_166_fu_364_p2 = (zext_ln73_21_fu_222_p1 + zext_ln73_25_fu_304_p1);

assign add_ln58_167_fu_536_p2 = (zext_ln58_18_fu_533_p1 + add_ln58_165_fu_528_p2);

assign add_ln58_168_fu_546_p2 = ($signed(shl_ln42_55_reg_967) + $signed(zext_ln73_21_reg_952));

assign add_ln58_169_fu_370_p2 = (shl_ln42_57_fu_284_p3 + zext_ln73_25_fu_304_p1);

assign add_ln58_170_fu_557_p2 = ($signed(sext_ln58_131_fu_554_p1) + $signed(sext_ln58_130_fu_550_p1));

assign add_ln58_171_fu_567_p2 = ($signed(sext_ln42_reg_911) + $signed(shl_ln42_61_cast_fu_489_p1));

assign add_ln58_172_fu_572_p2 = (add_ln58_171_fu_567_p2 + shl_ln42_53_cast38_fu_462_p1);

assign add_ln58_173_fu_582_p2 = ($signed(sext_ln42_12_fu_458_p1) + $signed(sext_ln58_125_fu_495_p1));

assign add_ln58_174_fu_376_p2 = ($signed(shl_ln42_55_fu_254_p3) + $signed(zext_ln73_25_fu_304_p1));

assign add_ln58_175_fu_591_p2 = ($signed(sext_ln58_134_fu_588_p1) + $signed(add_ln58_173_fu_582_p2));

assign add_ln58_176_fu_382_p2 = (zext_ln73_19_fu_178_p1 + shl_ln42_49_cast_fu_162_p1);

assign add_ln58_177_fu_388_p2 = ($signed(zext_ln73_23_fu_244_p1) + $signed(shl_ln42_59_fu_314_p3));

assign add_ln58_178_fu_607_p2 = ($signed(sext_ln58_136_fu_604_p1) + $signed(shl_ln42_55_cast_fu_479_p1));

assign add_ln58_179_fu_617_p2 = ($signed(sext_ln58_137_fu_613_p1) + $signed(zext_ln58_19_fu_601_p1));

assign add_ln58_180_fu_394_p2 = (zext_ln73_19_fu_178_p1 + zext_ln73_fu_110_p1);

assign add_ln58_181_fu_400_p2 = (zext_ln73_24_fu_274_p1 + zext_ln73_26_fu_334_p1);

assign add_ln58_182_fu_633_p2 = (zext_ln58_21_fu_630_p1 + zext_ln73_20_fu_465_p1);

assign add_ln58_183_fu_639_p2 = (add_ln58_182_fu_633_p2 + zext_ln58_20_fu_627_p1);

assign add_ln58_184_fu_649_p2 = ($signed(shl_ln42_51_cast_fu_443_p1) + $signed(sext_ln42_reg_911));

assign add_ln58_185_fu_406_p2 = ($signed(zext_ln73_25_fu_304_p1) + $signed(shl_ln42_61_fu_344_p3));

assign add_ln58_186_fu_661_p2 = ($signed(sext_ln58_140_fu_658_p1) + $signed(zext_ln73_22_fu_483_p1));

assign add_ln58_187_fu_671_p2 = ($signed(sext_ln58_141_fu_667_p1) + $signed(sext_ln58_139_fu_654_p1));

assign add_ln58_188_fu_681_p2 = ($signed(zext_ln73_20_fu_465_p1) + $signed(add_ln58_reg_984));

assign add_ln58_189_fu_412_p2 = ($signed(shl_ln42_59_fu_314_p3) + $signed(zext_ln73_26_fu_334_p1));

assign add_ln58_190_fu_693_p2 = ($signed(sext_ln58_144_fu_690_p1) + $signed(sext_ln58_143_fu_686_p1));

assign add_ln58_191_fu_706_p2 = ($signed(zext_ln58_23_fu_703_p1) + $signed(shl_ln42_47_cast_reg_905));

assign add_ln58_192_fu_718_p2 = ($signed(sext_ln58_147_fu_715_p1) + $signed(sext_ln42_11_fu_454_p1));

assign add_ln58_193_fu_728_p2 = ($signed(sext_ln58_148_fu_724_p1) + $signed(sext_ln58_146_fu_711_p1));

assign add_ln58_194_fu_738_p2 = (zext_ln58_fu_498_p1 + zext_ln73_20_fu_465_p1);

assign add_ln58_195_fu_418_p2 = ($signed(zext_ln73_23_fu_244_p1) + $signed(shl_ln42_61_fu_344_p3));

assign add_ln58_196_fu_751_p2 = ($signed(sext_ln58_150_fu_748_p1) + $signed(zext_ln58_24_fu_744_p1));

assign add_ln58_197_fu_761_p2 = ($signed(sext_ln58_fu_492_p1) + $signed(zext_ln58_fu_498_p1));

assign add_ln58_198_fu_771_p2 = (zext_ln58_20_fu_627_p1 + shl_ln42_49_cast42_fu_433_p1);

assign add_ln58_199_fu_424_p2 = ($signed(zext_ln73_24_fu_274_p1) + $signed(shl_ln42_61_fu_344_p3));

assign add_ln58_200_fu_784_p2 = ($signed(sext_ln58_153_fu_781_p1) + $signed(shl_ln42_57_cast_fu_486_p1));

assign add_ln58_201_fu_794_p2 = ($signed(sext_ln58_154_fu_790_p1) + $signed(zext_ln58_25_fu_777_p1));

assign add_ln58_fu_352_p2 = ($signed(sext_ln42_fu_150_p1) + $signed(shl_ln42_47_cast_fu_128_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = zext_ln58_22_fu_645_p1;

assign ap_return_1 = sext_ln58_142_fu_677_p1;

assign ap_return_10 = sext_ln58_152_fu_767_p1;

assign ap_return_11 = sext_ln58_132_fu_563_p1;

assign ap_return_12 = sext_ln58_133_fu_578_p1;

assign ap_return_13 = sext_ln58_135_fu_597_p1;

assign ap_return_14 = sext_ln68_fu_800_p1;

assign ap_return_15 = sext_ln58_138_fu_623_p1;

assign ap_return_2 = sext_ln58_145_fu_699_p1;

assign ap_return_3 = sext_ln58_149_fu_734_p1;

assign ap_return_4 = sext_ln58_151_fu_757_p1;

assign ap_return_5 = sext_ln58_129_fu_542_p1;

assign ap_return_6 = sext_ln58_126_fu_506_p1;

assign ap_return_7 = shl_ln42_47_cast43_fu_430_p1;

assign ap_return_8 = sext_ln58_128_fu_524_p1;

assign ap_return_9 = shl_ln42_55_cast44_fu_475_p1;

assign sext_ln42_11_fu_454_p1 = shl_ln42_50_fu_447_p3;

assign sext_ln42_12_fu_458_p1 = shl_ln42_50_fu_447_p3;

assign sext_ln42_fu_150_p1 = $signed(shl_ln42_46_fu_142_p3);

assign sext_ln58_125_fu_495_p1 = add_ln58_reg_984;

assign sext_ln58_126_fu_506_p1 = $signed(add_ln58_162_fu_501_p2);

assign sext_ln58_127_fu_514_p1 = $signed(add_ln58_163_fu_510_p2);

assign sext_ln58_128_fu_524_p1 = $signed(add_ln58_164_fu_518_p2);

assign sext_ln58_129_fu_542_p1 = $signed(add_ln58_167_fu_536_p2);

assign sext_ln58_130_fu_550_p1 = $signed(add_ln58_168_fu_546_p2);

assign sext_ln58_131_fu_554_p1 = $signed(add_ln58_169_reg_1000);

assign sext_ln58_132_fu_563_p1 = $signed(add_ln58_170_fu_557_p2);

assign sext_ln58_133_fu_578_p1 = $signed(add_ln58_172_fu_572_p2);

assign sext_ln58_134_fu_588_p1 = $signed(add_ln58_174_reg_1005);

assign sext_ln58_135_fu_597_p1 = $signed(add_ln58_175_fu_591_p2);

assign sext_ln58_136_fu_604_p1 = $signed(add_ln58_177_reg_1016);

assign sext_ln58_137_fu_613_p1 = $signed(add_ln58_178_fu_607_p2);

assign sext_ln58_138_fu_623_p1 = $signed(add_ln58_179_fu_617_p2);

assign sext_ln58_139_fu_654_p1 = $signed(add_ln58_184_fu_649_p2);

assign sext_ln58_140_fu_658_p1 = $signed(add_ln58_185_reg_1031);

assign sext_ln58_141_fu_667_p1 = $signed(add_ln58_186_fu_661_p2);

assign sext_ln58_142_fu_677_p1 = $signed(add_ln58_187_fu_671_p2);

assign sext_ln58_143_fu_686_p1 = $signed(add_ln58_188_fu_681_p2);

assign sext_ln58_144_fu_690_p1 = add_ln58_189_reg_1036;

assign sext_ln58_145_fu_699_p1 = $signed(add_ln58_190_fu_693_p2);

assign sext_ln58_146_fu_711_p1 = $signed(add_ln58_191_fu_706_p2);

assign sext_ln58_147_fu_715_p1 = add_ln58_189_reg_1036;

assign sext_ln58_148_fu_724_p1 = $signed(add_ln58_192_fu_718_p2);

assign sext_ln58_149_fu_734_p1 = $signed(add_ln58_193_fu_728_p2);

assign sext_ln58_150_fu_748_p1 = $signed(add_ln58_195_reg_1042);

assign sext_ln58_151_fu_757_p1 = $signed(add_ln58_196_fu_751_p2);

assign sext_ln58_152_fu_767_p1 = $signed(add_ln58_197_fu_761_p2);

assign sext_ln58_153_fu_781_p1 = $signed(add_ln58_199_reg_1047);

assign sext_ln58_154_fu_790_p1 = $signed(add_ln58_200_fu_784_p2);

assign sext_ln58_fu_492_p1 = shl_ln42_61_reg_979;

assign sext_ln68_fu_800_p1 = $signed(add_ln58_201_fu_794_p2);

assign shl_ln42_46_fu_142_p3 = {{sub_ln73_27_fu_136_p2}, {7'd0}};

assign shl_ln42_47_cast43_fu_430_p1 = shl_ln42_s_reg_900;

assign shl_ln42_47_cast_fu_128_p1 = shl_ln42_s_fu_120_p3;

assign shl_ln42_47_fu_154_p3 = {{data_1_val}, {7'd0}};

assign shl_ln42_48_fu_170_p3 = {{data_2_val}, {7'd0}};

assign shl_ln42_49_cast42_fu_433_p1 = shl_ln42_47_reg_917;

assign shl_ln42_49_cast_fu_162_p1 = shl_ln42_47_fu_154_p3;

assign shl_ln42_49_fu_436_p3 = {{sub_ln73_28_reg_927}, {7'd0}};

assign shl_ln42_50_fu_447_p3 = {{sub_ln73_29_reg_932}, {7'd0}};

assign shl_ln42_51_cast_fu_443_p1 = shl_ln42_49_fu_436_p3;

assign shl_ln42_51_fu_198_p3 = {{data_3_val}, {7'd0}};

assign shl_ln42_52_fu_214_p3 = {{data_4_val}, {7'd0}};

assign shl_ln42_53_cast38_fu_462_p1 = shl_ln42_51_reg_937;

assign shl_ln42_53_cast_fu_206_p1 = shl_ln42_51_fu_198_p3;

assign shl_ln42_53_fu_468_p3 = {{sub_ln73_30_reg_957}, {7'd0}};

assign shl_ln42_54_fu_236_p3 = {{data_5_val}, {7'd0}};

assign shl_ln42_55_cast44_fu_475_p1 = shl_ln42_53_fu_468_p3;

assign shl_ln42_55_cast_fu_479_p1 = shl_ln42_53_fu_468_p3;

assign shl_ln42_55_fu_254_p3 = {{sub_ln73_31_fu_248_p2}, {7'd0}};

assign shl_ln42_56_fu_266_p3 = {{data_6_val}, {7'd0}};

assign shl_ln42_57_cast_fu_486_p1 = shl_ln42_55_reg_967;

assign shl_ln42_57_fu_284_p3 = {{sub_ln73_32_fu_278_p2}, {7'd0}};

assign shl_ln42_58_fu_296_p3 = {{data_7_val}, {7'd0}};

assign shl_ln42_59_fu_314_p3 = {{sub_ln73_33_fu_308_p2}, {7'd0}};

assign shl_ln42_60_fu_326_p3 = {{data_8_val}, {7'd0}};

assign shl_ln42_61_cast_fu_489_p1 = shl_ln42_59_reg_974;

assign shl_ln42_61_fu_344_p3 = {{sub_ln73_34_fu_338_p2}, {7'd0}};

assign shl_ln42_s_fu_120_p3 = {{sub_ln73_fu_114_p2}, {7'd0}};

assign shl_ln_fu_102_p3 = {{data_0_val}, {7'd0}};

assign sub_ln73_27_fu_136_p2 = (3'd0 - zext_ln70_31_fu_132_p1);

assign sub_ln73_28_fu_182_p2 = (3'd0 - zext_ln70_32_fu_166_p1);

assign sub_ln73_29_fu_192_p2 = (3'd0 - zext_ln70_33_fu_188_p1);

assign sub_ln73_30_fu_226_p2 = (3'd0 - zext_ln70_34_fu_210_p1);

assign sub_ln73_31_fu_248_p2 = (3'd0 - zext_ln70_35_fu_232_p1);

assign sub_ln73_32_fu_278_p2 = (3'd0 - zext_ln70_36_fu_262_p1);

assign sub_ln73_33_fu_308_p2 = (3'd0 - zext_ln70_37_fu_292_p1);

assign sub_ln73_34_fu_338_p2 = (3'd0 - zext_ln70_38_fu_322_p1);

assign sub_ln73_fu_114_p2 = (3'd0 - zext_ln70_fu_98_p1);

assign zext_ln58_18_fu_533_p1 = add_ln58_166_reg_995;

assign zext_ln58_19_fu_601_p1 = add_ln58_176_reg_1010;

assign zext_ln58_20_fu_627_p1 = add_ln58_180_reg_1021;

assign zext_ln58_21_fu_630_p1 = add_ln58_181_reg_1026;

assign zext_ln58_22_fu_645_p1 = add_ln58_183_fu_639_p2;

assign zext_ln58_23_fu_703_p1 = add_ln58_176_reg_1010;

assign zext_ln58_24_fu_744_p1 = add_ln58_194_fu_738_p2;

assign zext_ln58_25_fu_777_p1 = add_ln58_198_fu_771_p2;

assign zext_ln58_fu_498_p1 = add_ln58_161_reg_990;

assign zext_ln70_31_fu_132_p1 = data_1_val;

assign zext_ln70_32_fu_166_p1 = data_2_val;

assign zext_ln70_33_fu_188_p1 = data_3_val;

assign zext_ln70_34_fu_210_p1 = data_4_val;

assign zext_ln70_35_fu_232_p1 = data_5_val;

assign zext_ln70_36_fu_262_p1 = data_6_val;

assign zext_ln70_37_fu_292_p1 = data_7_val;

assign zext_ln70_38_fu_322_p1 = data_8_val;

assign zext_ln70_fu_98_p1 = data_0_val;

assign zext_ln73_19_fu_178_p1 = shl_ln42_48_fu_170_p3;

assign zext_ln73_20_fu_465_p1 = shl_ln42_52_reg_947;

assign zext_ln73_21_fu_222_p1 = shl_ln42_52_fu_214_p3;

assign zext_ln73_22_fu_483_p1 = shl_ln42_54_reg_962;

assign zext_ln73_23_fu_244_p1 = shl_ln42_54_fu_236_p3;

assign zext_ln73_24_fu_274_p1 = shl_ln42_56_fu_266_p3;

assign zext_ln73_25_fu_304_p1 = shl_ln42_58_fu_296_p3;

assign zext_ln73_26_fu_334_p1 = shl_ln42_60_fu_326_p3;

assign zext_ln73_fu_110_p1 = shl_ln_fu_102_p3;

always @ (posedge ap_clk) begin
    shl_ln42_s_reg_900[6:0] <= 7'b0000000;
    shl_ln42_47_cast_reg_905[6:0] <= 7'b0000000;
    sext_ln42_reg_911[6:0] <= 7'b0000000;
    shl_ln42_47_reg_917[6:0] <= 7'b0000000;
    zext_ln73_19_reg_922[6:0] <= 7'b0000000;
    zext_ln73_19_reg_922[9] <= 1'b0;
    shl_ln42_51_reg_937[6:0] <= 7'b0000000;
    shl_ln42_53_cast_reg_942[6:0] <= 7'b0000000;
    shl_ln42_53_cast_reg_942[9] <= 1'b0;
    shl_ln42_52_reg_947[6:0] <= 7'b0000000;
    zext_ln73_21_reg_952[6:0] <= 7'b0000000;
    zext_ln73_21_reg_952[9] <= 1'b0;
    shl_ln42_54_reg_962[6:0] <= 7'b0000000;
    shl_ln42_55_reg_967[6:0] <= 7'b0000000;
    shl_ln42_59_reg_974[6:0] <= 7'b0000000;
    shl_ln42_61_reg_979[6:0] <= 7'b0000000;
    add_ln58_reg_984[6:0] <= 7'b0000000;
    add_ln58_161_reg_990[6:0] <= 7'b0000000;
    add_ln58_166_reg_995[6:0] <= 7'b0000000;
    add_ln58_169_reg_1000[6:0] <= 7'b0000000;
    add_ln58_174_reg_1005[6:0] <= 7'b0000000;
    add_ln58_176_reg_1010[6:0] <= 7'b0000000;
    add_ln58_177_reg_1016[6:0] <= 7'b0000000;
    add_ln58_180_reg_1021[6:0] <= 7'b0000000;
    add_ln58_181_reg_1026[6:0] <= 7'b0000000;
    add_ln58_185_reg_1031[6:0] <= 7'b0000000;
    add_ln58_189_reg_1036[6:0] <= 7'b0000000;
    add_ln58_195_reg_1042[6:0] <= 7'b0000000;
    add_ln58_199_reg_1047[6:0] <= 7'b0000000;
end

endmodule //myproject_dense_latency_ap_ufixed_2_0_4_0_0_ap_fixed_16_6_5_3_0_config13_s
