-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln70_fu_44_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_fu_44_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln73_fu_48_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln42_1_fu_64_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_1_fu_64_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_1_fu_78_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_1_fu_78_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln73_49_fu_82_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln42_3_fu_98_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_3_fu_98_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_2_fu_88_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_54_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_14_fu_108_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_74_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_112_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_271_fu_118_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_272_fu_124_p2 : STD_LOGIC_VECTOR (15 downto 0);


begin



    add_ln58_271_fu_118_p2 <= std_logic_vector(signed(sext_ln42_14_fu_108_p1) + signed(sext_ln42_fu_74_p1));
    add_ln58_272_fu_124_p2 <= std_logic_vector(unsigned(trunc_ln_fu_54_p4) + unsigned(sext_ln42_14_fu_108_p1));
    add_ln58_fu_112_p2 <= std_logic_vector(unsigned(trunc_ln42_2_fu_88_p4) + unsigned(trunc_ln_fu_54_p4));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln58_fu_112_p2;
    ap_return_1 <= sub_ln73_49_fu_82_p2(16 downto 1);
    ap_return_10 <= sext_ln42_fu_74_p1;
    ap_return_11 <= add_ln58_271_fu_118_p2;
    ap_return_12 <= sext_ln42_14_fu_108_p1;
    ap_return_13 <= add_ln58_271_fu_118_p2;
    ap_return_14 <= sext_ln42_14_fu_108_p1;
    ap_return_15 <= add_ln58_272_fu_124_p2;
    ap_return_16 <= add_ln58_271_fu_118_p2;
    ap_return_2 <= sub_ln73_fu_48_p2(16 downto 1);
    ap_return_3 <= add_ln58_271_fu_118_p2;
    ap_return_4 <= add_ln58_271_fu_118_p2;
    ap_return_5 <= sext_ln42_14_fu_108_p1;
    ap_return_6 <= sub_ln73_fu_48_p2(16 downto 1);
    ap_return_7 <= add_ln58_fu_112_p2;
    ap_return_8 <= sext_ln42_fu_74_p1;
    ap_return_9 <= add_ln58_fu_112_p2;
        sext_ln42_14_fu_108_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_3_fu_98_p4),16));

        sext_ln42_fu_74_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_1_fu_64_p4),16));

    sext_ln70_1_fu_78_p0 <= data_1_val;
        sext_ln70_1_fu_78_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_1_fu_78_p0),17));

    sext_ln70_fu_44_p0 <= data_0_val;
        sext_ln70_fu_44_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_fu_44_p0),17));

    sub_ln73_49_fu_82_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln70_1_fu_78_p1));
    sub_ln73_fu_48_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln70_fu_44_p1));
    trunc_ln42_1_fu_64_p1 <= data_0_val;
    trunc_ln42_1_fu_64_p4 <= trunc_ln42_1_fu_64_p1(15 downto 1);
    trunc_ln42_2_fu_88_p4 <= sub_ln73_49_fu_82_p2(16 downto 1);
    trunc_ln42_3_fu_98_p1 <= data_1_val;
    trunc_ln42_3_fu_98_p4 <= trunc_ln42_3_fu_98_p1(15 downto 1);
    trunc_ln_fu_54_p4 <= sub_ln73_fu_48_p2(16 downto 1);
end behav;
