-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_ufixed_2_0_4_0_0_ap_fixed_16_6_5_3_0_config16_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (1 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (1 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_dense_latency_ap_ufixed_2_0_4_0_0_ap_fixed_16_6_5_3_0_config16_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal data_15_val_read_reg_803 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_14_val_read_reg_808 : STD_LOGIC_VECTOR (1 downto 0);
    signal data_8_val_read_reg_813 : STD_LOGIC_VECTOR (1 downto 0);
    signal data_5_val_read_reg_818 : STD_LOGIC_VECTOR (1 downto 0);
    signal data_2_val_read_reg_823 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln73_fu_160_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_reg_828 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_17_fu_170_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_17_reg_833 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_20_fu_184_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_20_reg_838 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln73_20_fu_204_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_20_reg_844 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_21_fu_218_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_21_reg_849 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_22_fu_232_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_22_reg_854 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_23_fu_242_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_23_reg_859 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_24_fu_252_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_24_reg_864 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_26_fu_272_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_26_reg_869 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp16_fu_282_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp16_reg_874 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp2914_fu_302_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp2914_reg_879 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp3112_fu_308_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp3112_reg_884 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp3310_fu_318_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp3310_reg_889 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln58_155_fu_324_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_155_reg_894 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_137_fu_522_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_137_reg_899 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_139_fu_538_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_139_reg_904 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_141_fu_555_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_141_reg_909 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_143_fu_581_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_143_reg_914 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_146_fu_607_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_146_reg_919 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_149_fu_622_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_149_reg_924 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_152_fu_648_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_152_reg_929 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_156_fu_674_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_156_reg_934 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_159_fu_700_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_159_reg_939 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln70_fu_156_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_18_fu_166_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln42_34_fu_176_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln42_35_fu_188_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_22_fu_200_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_24_fu_214_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_26_fu_228_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_27_fu_238_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_28_fu_248_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_29_fu_258_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_30_fu_268_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal data_3_val_cast_fu_278_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln70_25_fu_224_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_25_fu_262_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp4_fu_292_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp4_cast_fu_298_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln73_28_cast_fu_288_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln70_23_fu_210_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal data_10_val_cast_fu_314_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln42_36_cast_fu_196_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_330_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_s_fu_341_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_19_fu_352_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_18_fu_355_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln42_33_fu_361_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_21_fu_373_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln73_19_fu_376_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln42_36_fu_382_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_37_fu_394_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_38_fu_405_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln42_39_fu_424_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_40_fu_435_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_41_fu_446_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_42_fu_457_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_43_fu_468_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln42_44_fu_479_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln42_45_fu_490_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_501_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_cast_fu_337_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_37_cast_fu_401_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_fu_512_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_fu_518_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln42_fu_369_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln42_42_cast_fu_453_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_42_cast2_fu_464_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_138_fu_528_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_115_fu_534_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln58_113_fu_508_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_544_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_125_fu_551_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln73_fu_412_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_3_fu_561_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_17_fu_420_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_142_fu_572_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_fu_577_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_126_fu_568_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_144_fu_587_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_44_cast_fu_475_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_18_fu_486_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln58_145_fu_597_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln58_14_fu_603_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln58_128_fu_593_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln58_148_fu_613_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln58_117_fu_618_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_38_cast_fu_390_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_40_cast_fu_431_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_41_cast_fu_442_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_150_fu_628_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln42_46_cast_fu_497_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_151_fu_638_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln58_120_fu_644_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln58_119_fu_634_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp5_fu_654_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln42_33_cast_fu_348_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_16_fu_671_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_154_fu_665_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln73_16_fu_416_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln58_15_fu_661_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_157_fu_680_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln58_158_fu_690_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln58_123_fu_696_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln58_17_fu_686_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln58_116_fu_709_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_114_fu_706_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_140_fu_712_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_129_fu_728_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_127_fu_725_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_147_fu_731_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_121_fu_744_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_118_fu_741_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_153_fu_747_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_124_fu_760_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln58_122_fu_757_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_160_fu_763_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln58_140_cast_fu_718_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_141_cast_fu_722_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln58_130_fu_737_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_158_cast_fu_753_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_165_cast_fu_769_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    add_ln58_137_reg_899(11 downto 7) <= add_ln58_137_fu_522_p2(11 downto 7);
                    add_ln58_139_reg_904(11 downto 7) <= add_ln58_139_fu_538_p2(11 downto 7);
                    add_ln58_141_reg_909(11 downto 7) <= add_ln58_141_fu_555_p2(11 downto 7);
                    add_ln58_143_reg_914(10 downto 7) <= add_ln58_143_fu_581_p2(10 downto 7);
                    add_ln58_146_reg_919(11 downto 7) <= add_ln58_146_fu_607_p2(11 downto 7);
                    add_ln58_149_reg_924(10 downto 7) <= add_ln58_149_fu_622_p2(10 downto 7);
                    add_ln58_152_reg_929(11 downto 7) <= add_ln58_152_fu_648_p2(11 downto 7);
                    add_ln58_155_reg_894(9 downto 7) <= add_ln58_155_fu_324_p2(9 downto 7);
                    add_ln58_156_reg_934(10 downto 7) <= add_ln58_156_fu_674_p2(10 downto 7);
                    add_ln58_159_reg_939(11 downto 7) <= add_ln58_159_fu_700_p2(11 downto 7);
                data_14_val_read_reg_808 <= data_14_val;
                data_15_val_read_reg_803 <= data_15_val;
                data_2_val_read_reg_823 <= data_2_val;
                data_5_val_read_reg_818 <= data_5_val;
                data_8_val_read_reg_813 <= data_8_val;
                sub_ln73_17_reg_833 <= sub_ln73_17_fu_170_p2;
                sub_ln73_20_reg_844 <= sub_ln73_20_fu_204_p2;
                sub_ln73_21_reg_849 <= sub_ln73_21_fu_218_p2;
                sub_ln73_22_reg_854 <= sub_ln73_22_fu_232_p2;
                sub_ln73_23_reg_859 <= sub_ln73_23_fu_242_p2;
                sub_ln73_24_reg_864 <= sub_ln73_24_fu_252_p2;
                sub_ln73_26_reg_869 <= sub_ln73_26_fu_272_p2;
                sub_ln73_reg_828 <= sub_ln73_fu_160_p2;
                tmp16_reg_874 <= tmp16_fu_282_p2;
                tmp2914_reg_879 <= tmp2914_fu_302_p2;
                tmp3112_reg_884 <= tmp3112_fu_308_p2;
                tmp3310_reg_889 <= tmp3310_fu_318_p2;
                    zext_ln70_20_reg_838(8 downto 7) <= zext_ln70_20_fu_184_p1(8 downto 7);
            end if;
        end if;
    end process;
    zext_ln70_20_reg_838(6 downto 0) <= "0000000";
    zext_ln70_20_reg_838(9) <= '0';
    add_ln58_155_reg_894(6 downto 0) <= "0000000";
    add_ln58_137_reg_899(6 downto 0) <= "0000000";
    add_ln58_139_reg_904(6 downto 0) <= "0000000";
    add_ln58_141_reg_909(6 downto 0) <= "0000000";
    add_ln58_143_reg_914(6 downto 0) <= "0000000";
    add_ln58_146_reg_919(6 downto 0) <= "0000000";
    add_ln58_149_reg_924(6 downto 0) <= "0000000";
    add_ln58_152_reg_929(6 downto 0) <= "0000000";
    add_ln58_156_reg_934(6 downto 0) <= "0000000";
    add_ln58_159_reg_939(6 downto 0) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_137_fu_522_p2 <= std_logic_vector(signed(sext_ln58_fu_518_p1) + signed(sext_ln42_fu_369_p1));
    add_ln58_138_fu_528_p2 <= std_logic_vector(signed(shl_ln42_42_cast_fu_453_p1) + signed(shl_ln42_42_cast2_fu_464_p1));
    add_ln58_139_fu_538_p2 <= std_logic_vector(signed(sext_ln58_115_fu_534_p1) + signed(sext_ln58_113_fu_508_p1));
        add_ln58_140_cast_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_140_fu_712_p2),16));

    add_ln58_140_fu_712_p2 <= std_logic_vector(signed(sext_ln58_116_fu_709_p1) + signed(sext_ln58_114_fu_706_p1));
        add_ln58_141_cast_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_141_reg_909),16));

    add_ln58_141_fu_555_p2 <= std_logic_vector(signed(sext_ln58_125_fu_551_p1) + signed(zext_ln73_fu_412_p1));
    add_ln58_142_fu_572_p2 <= std_logic_vector(unsigned(zext_ln70_20_reg_838) + unsigned(zext_ln73_17_fu_420_p1));
    add_ln58_143_fu_581_p2 <= std_logic_vector(unsigned(zext_ln58_fu_577_p1) + unsigned(shl_ln42_37_cast_fu_401_p1));
    add_ln58_144_fu_587_p2 <= std_logic_vector(signed(sext_ln58_126_fu_568_p1) + signed(shl_ln42_42_cast2_fu_464_p1));
    add_ln58_145_fu_597_p2 <= std_logic_vector(unsigned(shl_ln42_44_cast_fu_475_p1) + unsigned(zext_ln73_18_fu_486_p1));
    add_ln58_146_fu_607_p2 <= std_logic_vector(unsigned(zext_ln58_14_fu_603_p1) + unsigned(sext_ln58_128_fu_593_p1));
    add_ln58_147_fu_731_p2 <= std_logic_vector(signed(sext_ln58_129_fu_728_p1) + signed(sext_ln58_127_fu_725_p1));
    add_ln58_148_fu_613_p2 <= std_logic_vector(unsigned(zext_ln70_20_reg_838) + unsigned(shl_ln42_37_fu_394_p3));
    add_ln58_149_fu_622_p2 <= std_logic_vector(signed(sext_ln58_117_fu_618_p1) + signed(shl_ln42_38_cast_fu_390_p1));
    add_ln58_150_fu_628_p2 <= std_logic_vector(signed(shl_ln42_40_cast_fu_431_p1) + signed(shl_ln42_41_cast_fu_442_p1));
    add_ln58_151_fu_638_p2 <= std_logic_vector(signed(shl_ln42_42_cast_fu_453_p1) + signed(shl_ln42_46_cast_fu_497_p1));
    add_ln58_152_fu_648_p2 <= std_logic_vector(signed(sext_ln58_120_fu_644_p1) + signed(sext_ln58_119_fu_634_p1));
    add_ln58_153_fu_747_p2 <= std_logic_vector(signed(sext_ln58_121_fu_744_p1) + signed(sext_ln58_118_fu_741_p1));
    add_ln58_154_fu_665_p2 <= std_logic_vector(signed(shl_ln42_33_cast_fu_348_p1) + signed(shl_ln42_cast_fu_337_p1));
    add_ln58_155_fu_324_p2 <= std_logic_vector(unsigned(zext_ln70_20_fu_184_p1) + unsigned(shl_ln42_36_cast_fu_196_p1));
    add_ln58_156_fu_674_p2 <= std_logic_vector(unsigned(zext_ln58_16_fu_671_p1) + unsigned(add_ln58_154_fu_665_p2));
    add_ln58_157_fu_680_p2 <= std_logic_vector(unsigned(zext_ln73_16_fu_416_p1) + unsigned(zext_ln58_15_fu_661_p1));
        add_ln58_158_cast_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_153_fu_747_p2),16));

    add_ln58_158_fu_690_p2 <= std_logic_vector(signed(shl_ln42_42_fu_457_p3) + signed(zext_ln73_18_fu_486_p1));
    add_ln58_159_fu_700_p2 <= std_logic_vector(signed(sext_ln58_123_fu_696_p1) + signed(zext_ln58_17_fu_686_p1));
    add_ln58_160_fu_763_p2 <= std_logic_vector(signed(sext_ln58_124_fu_760_p1) + signed(sext_ln58_122_fu_757_p1));
        add_ln58_165_cast_fu_769_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_160_fu_763_p2),16));

    add_ln58_fu_512_p2 <= std_logic_vector(signed(shl_ln42_cast_fu_337_p1) + signed(shl_ln42_37_cast_fu_401_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= (ap_const_logic_0 = ap_ce);
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln58_140_cast_fu_718_p1;
    ap_return_1 <= add_ln58_141_cast_fu_722_p1;
    ap_return_2 <= sext_ln58_130_fu_737_p1;
    ap_return_3 <= add_ln58_158_cast_fu_753_p1;
    ap_return_4 <= add_ln58_165_cast_fu_769_p1;
    data_10_val_cast_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_10_val),3));
    data_3_val_cast_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_3_val),3));
        sext_ln42_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_33_fu_361_p3),12));

        sext_ln58_113_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_501_p3),12));

        sext_ln58_114_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_137_reg_899),13));

        sext_ln58_115_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_138_fu_528_p2),12));

        sext_ln58_116_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_139_reg_904),13));

        sext_ln58_117_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_148_fu_613_p2),11));

        sext_ln58_118_fu_741_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_149_reg_924),13));

        sext_ln58_119_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_150_fu_628_p2),12));

        sext_ln58_120_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_151_fu_638_p2),12));

        sext_ln58_121_fu_744_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_152_reg_929),13));

        sext_ln58_122_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_156_reg_934),13));

        sext_ln58_123_fu_696_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_158_fu_690_p2),12));

        sext_ln58_124_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_159_reg_939),13));

        sext_ln58_125_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_544_p3),12));

        sext_ln58_126_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_561_p3),11));

        sext_ln58_127_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_143_reg_914),13));

        sext_ln58_128_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_144_fu_587_p2),12));

        sext_ln58_129_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_146_reg_919),13));

        sext_ln58_130_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_147_fu_731_p2),16));

        sext_ln58_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_fu_512_p2),12));

        shl_ln42_33_cast_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_s_fu_341_p3),11));

    shl_ln42_33_fu_361_p3 <= (sub_ln73_18_fu_355_p2 & ap_const_lv7_0);
    shl_ln42_34_fu_176_p3 <= (data_2_val & ap_const_lv7_0);
    shl_ln42_35_fu_188_p3 <= (data_4_val & ap_const_lv7_0);
    shl_ln42_36_cast_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_35_fu_188_p3),10));
    shl_ln42_36_fu_382_p3 <= (sub_ln73_19_fu_376_p2 & ap_const_lv7_0);
        shl_ln42_37_cast_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_37_fu_394_p3),11));

    shl_ln42_37_fu_394_p3 <= (sub_ln73_20_reg_844 & ap_const_lv7_0);
        shl_ln42_38_cast_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_36_fu_382_p3),11));

    shl_ln42_38_fu_405_p3 <= (data_8_val_read_reg_813 & ap_const_lv7_0);
    shl_ln42_39_fu_424_p3 <= (sub_ln73_21_reg_849 & ap_const_lv7_0);
        shl_ln42_40_cast_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_39_fu_424_p3),11));

    shl_ln42_40_fu_435_p3 <= (sub_ln73_22_reg_854 & ap_const_lv7_0);
        shl_ln42_41_cast_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_40_fu_435_p3),11));

    shl_ln42_41_fu_446_p3 <= (sub_ln73_23_reg_859 & ap_const_lv7_0);
        shl_ln42_42_cast2_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_42_fu_457_p3),11));

        shl_ln42_42_cast_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_41_fu_446_p3),11));

    shl_ln42_42_fu_457_p3 <= (sub_ln73_24_reg_864 & ap_const_lv7_0);
    shl_ln42_43_fu_468_p3 <= (data_14_val_read_reg_808 & ap_const_lv7_0);
    shl_ln42_44_cast_fu_475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_43_fu_468_p3),10));
    shl_ln42_44_fu_479_p3 <= (data_15_val_read_reg_803 & ap_const_lv7_0);
    shl_ln42_45_fu_490_p3 <= (sub_ln73_26_reg_869 & ap_const_lv7_0);
        shl_ln42_46_cast_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln42_45_fu_490_p3),11));

        shl_ln42_cast_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_330_p3),11));

    shl_ln42_s_fu_341_p3 <= (sub_ln73_17_reg_833 & ap_const_lv7_0);
    shl_ln_fu_330_p3 <= (sub_ln73_reg_828 & ap_const_lv7_0);
    sub_ln73_17_fu_170_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_18_fu_166_p1));
    sub_ln73_18_fu_355_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_19_fu_352_p1));
    sub_ln73_19_fu_376_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_21_fu_373_p1));
    sub_ln73_20_fu_204_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_22_fu_200_p1));
    sub_ln73_21_fu_218_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_24_fu_214_p1));
    sub_ln73_22_fu_232_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_26_fu_228_p1));
    sub_ln73_23_fu_242_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_27_fu_238_p1));
    sub_ln73_24_fu_252_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_28_fu_248_p1));
    sub_ln73_25_fu_262_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_29_fu_258_p1));
    sub_ln73_26_fu_272_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_30_fu_268_p1));
        sub_ln73_28_cast_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln73_25_fu_262_p2),4));

    sub_ln73_fu_160_p2 <= std_logic_vector(unsigned(ap_const_lv3_0) - unsigned(zext_ln70_fu_156_p1));
    tmp16_fu_282_p2 <= std_logic_vector(unsigned(data_3_val_cast_fu_278_p1) - unsigned(zext_ln70_25_fu_224_p1));
    tmp2914_fu_302_p2 <= std_logic_vector(unsigned(tmp4_cast_fu_298_p1) + unsigned(sub_ln73_28_cast_fu_288_p1));
    tmp3112_fu_308_p2 <= std_logic_vector(unsigned(zext_ln70_18_fu_166_p1) - unsigned(zext_ln70_23_fu_210_p1));
    tmp3310_fu_318_p2 <= std_logic_vector(unsigned(zext_ln70_27_fu_238_p1) + unsigned(data_10_val_cast_fu_314_p1));
    tmp4_cast_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_fu_292_p2),4));
    tmp4_fu_292_p2 <= std_logic_vector(unsigned(zext_ln70_22_fu_200_p1) + unsigned(zext_ln70_fu_156_p1));
    tmp5_fu_654_p3 <= (tmp3310_reg_889 & ap_const_lv7_0);
    tmp_2_fu_544_p3 <= (tmp2914_reg_879 & ap_const_lv7_0);
    tmp_3_fu_561_p3 <= (tmp3112_reg_884 & ap_const_lv7_0);
    tmp_fu_501_p3 <= (tmp16_reg_874 & ap_const_lv7_0);
    zext_ln58_14_fu_603_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_145_fu_597_p2),12));
    zext_ln58_15_fu_661_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_654_p3),11));
    zext_ln58_16_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_155_reg_894),11));
    zext_ln58_17_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_157_fu_680_p2),12));
    zext_ln58_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln58_142_fu_572_p2),11));
    zext_ln70_18_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_1_val),3));
    zext_ln70_19_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_2_val_read_reg_823),3));
    zext_ln70_20_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_34_fu_176_p3),10));
    zext_ln70_21_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_5_val_read_reg_818),3));
    zext_ln70_22_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_6_val),3));
    zext_ln70_23_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_7_val),3));
    zext_ln70_24_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_8_val),3));
    zext_ln70_25_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_9_val),3));
    zext_ln70_26_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_11_val),3));
    zext_ln70_27_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_12_val),3));
    zext_ln70_28_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_13_val),3));
    zext_ln70_29_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_14_val),3));
    zext_ln70_30_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_15_val),3));
    zext_ln70_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(data_0_val),3));
    zext_ln73_16_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_38_fu_405_p3),11));
    zext_ln73_17_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_38_fu_405_p3),10));
    zext_ln73_18_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_44_fu_479_p3),10));
    zext_ln73_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln42_38_fu_405_p3),12));
end behav;
